
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `actors_hero` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model actors_hero
 * 
 */
export type actors_heroModel = runtime.Types.Result.DefaultSelection<Prisma.$actors_heroPayload>

export type AggregateActors_hero = {
  _count: Actors_heroCountAggregateOutputType | null
  _avg: Actors_heroAvgAggregateOutputType | null
  _sum: Actors_heroSumAggregateOutputType | null
  _min: Actors_heroMinAggregateOutputType | null
  _max: Actors_heroMaxAggregateOutputType | null
}

export type Actors_heroAvgAggregateOutputType = {
  ID_actor: number | null
  ID_hero: number | null
}

export type Actors_heroSumAggregateOutputType = {
  ID_actor: number | null
  ID_hero: number | null
}

export type Actors_heroMinAggregateOutputType = {
  ID_actor: number | null
  ID_hero: number | null
  is_playing: boolean | null
}

export type Actors_heroMaxAggregateOutputType = {
  ID_actor: number | null
  ID_hero: number | null
  is_playing: boolean | null
}

export type Actors_heroCountAggregateOutputType = {
  ID_actor: number
  ID_hero: number
  is_playing: number
  _all: number
}


export type Actors_heroAvgAggregateInputType = {
  ID_actor?: true
  ID_hero?: true
}

export type Actors_heroSumAggregateInputType = {
  ID_actor?: true
  ID_hero?: true
}

export type Actors_heroMinAggregateInputType = {
  ID_actor?: true
  ID_hero?: true
  is_playing?: true
}

export type Actors_heroMaxAggregateInputType = {
  ID_actor?: true
  ID_hero?: true
  is_playing?: true
}

export type Actors_heroCountAggregateInputType = {
  ID_actor?: true
  ID_hero?: true
  is_playing?: true
  _all?: true
}

export type Actors_heroAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which actors_hero to aggregate.
   */
  where?: Prisma.actors_heroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of actors_heroes to fetch.
   */
  orderBy?: Prisma.actors_heroOrderByWithRelationInput | Prisma.actors_heroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.actors_heroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` actors_heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` actors_heroes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned actors_heroes
  **/
  _count?: true | Actors_heroCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Actors_heroAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Actors_heroSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Actors_heroMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Actors_heroMaxAggregateInputType
}

export type GetActors_heroAggregateType<T extends Actors_heroAggregateArgs> = {
      [P in keyof T & keyof AggregateActors_hero]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActors_hero[P]>
    : Prisma.GetScalarType<T[P], AggregateActors_hero[P]>
}




export type actors_heroGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.actors_heroWhereInput
  orderBy?: Prisma.actors_heroOrderByWithAggregationInput | Prisma.actors_heroOrderByWithAggregationInput[]
  by: Prisma.Actors_heroScalarFieldEnum[] | Prisma.Actors_heroScalarFieldEnum
  having?: Prisma.actors_heroScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Actors_heroCountAggregateInputType | true
  _avg?: Actors_heroAvgAggregateInputType
  _sum?: Actors_heroSumAggregateInputType
  _min?: Actors_heroMinAggregateInputType
  _max?: Actors_heroMaxAggregateInputType
}

export type Actors_heroGroupByOutputType = {
  ID_actor: number
  ID_hero: number
  is_playing: boolean | null
  _count: Actors_heroCountAggregateOutputType | null
  _avg: Actors_heroAvgAggregateOutputType | null
  _sum: Actors_heroSumAggregateOutputType | null
  _min: Actors_heroMinAggregateOutputType | null
  _max: Actors_heroMaxAggregateOutputType | null
}

type GetActors_heroGroupByPayload<T extends actors_heroGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Actors_heroGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Actors_heroGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Actors_heroGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Actors_heroGroupByOutputType[P]>
      }
    >
  >



export type actors_heroWhereInput = {
  AND?: Prisma.actors_heroWhereInput | Prisma.actors_heroWhereInput[]
  OR?: Prisma.actors_heroWhereInput[]
  NOT?: Prisma.actors_heroWhereInput | Prisma.actors_heroWhereInput[]
  ID_actor?: Prisma.IntFilter<"actors_hero"> | number
  ID_hero?: Prisma.IntFilter<"actors_hero"> | number
  is_playing?: Prisma.BoolNullableFilter<"actors_hero"> | boolean | null
  actor?: Prisma.XOR<Prisma.ActorScalarRelationFilter, Prisma.actorWhereInput>
  hero?: Prisma.XOR<Prisma.HeroScalarRelationFilter, Prisma.heroWhereInput>
}

export type actors_heroOrderByWithRelationInput = {
  ID_actor?: Prisma.SortOrder
  ID_hero?: Prisma.SortOrder
  is_playing?: Prisma.SortOrderInput | Prisma.SortOrder
  actor?: Prisma.actorOrderByWithRelationInput
  hero?: Prisma.heroOrderByWithRelationInput
}

export type actors_heroWhereUniqueInput = Prisma.AtLeast<{
  ID_actor_ID_hero?: Prisma.actors_heroID_actorID_heroCompoundUniqueInput
  AND?: Prisma.actors_heroWhereInput | Prisma.actors_heroWhereInput[]
  OR?: Prisma.actors_heroWhereInput[]
  NOT?: Prisma.actors_heroWhereInput | Prisma.actors_heroWhereInput[]
  ID_actor?: Prisma.IntFilter<"actors_hero"> | number
  ID_hero?: Prisma.IntFilter<"actors_hero"> | number
  is_playing?: Prisma.BoolNullableFilter<"actors_hero"> | boolean | null
  actor?: Prisma.XOR<Prisma.ActorScalarRelationFilter, Prisma.actorWhereInput>
  hero?: Prisma.XOR<Prisma.HeroScalarRelationFilter, Prisma.heroWhereInput>
}, "ID_actor_ID_hero">

export type actors_heroOrderByWithAggregationInput = {
  ID_actor?: Prisma.SortOrder
  ID_hero?: Prisma.SortOrder
  is_playing?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.actors_heroCountOrderByAggregateInput
  _avg?: Prisma.actors_heroAvgOrderByAggregateInput
  _max?: Prisma.actors_heroMaxOrderByAggregateInput
  _min?: Prisma.actors_heroMinOrderByAggregateInput
  _sum?: Prisma.actors_heroSumOrderByAggregateInput
}

export type actors_heroScalarWhereWithAggregatesInput = {
  AND?: Prisma.actors_heroScalarWhereWithAggregatesInput | Prisma.actors_heroScalarWhereWithAggregatesInput[]
  OR?: Prisma.actors_heroScalarWhereWithAggregatesInput[]
  NOT?: Prisma.actors_heroScalarWhereWithAggregatesInput | Prisma.actors_heroScalarWhereWithAggregatesInput[]
  ID_actor?: Prisma.IntWithAggregatesFilter<"actors_hero"> | number
  ID_hero?: Prisma.IntWithAggregatesFilter<"actors_hero"> | number
  is_playing?: Prisma.BoolNullableWithAggregatesFilter<"actors_hero"> | boolean | null
}

export type actors_heroCreateInput = {
  is_playing?: boolean | null
  actor: Prisma.actorCreateNestedOneWithoutActors_heroInput
  hero: Prisma.heroCreateNestedOneWithoutActors_heroInput
}

export type actors_heroUncheckedCreateInput = {
  ID_actor: number
  ID_hero: number
  is_playing?: boolean | null
}

export type actors_heroUpdateInput = {
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  actor?: Prisma.actorUpdateOneRequiredWithoutActors_heroNestedInput
  hero?: Prisma.heroUpdateOneRequiredWithoutActors_heroNestedInput
}

export type actors_heroUncheckedUpdateInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type actors_heroCreateManyInput = {
  ID_actor: number
  ID_hero: number
  is_playing?: boolean | null
}

export type actors_heroUpdateManyMutationInput = {
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type actors_heroUncheckedUpdateManyInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type Actors_heroListRelationFilter = {
  every?: Prisma.actors_heroWhereInput
  some?: Prisma.actors_heroWhereInput
  none?: Prisma.actors_heroWhereInput
}

export type actors_heroOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type actors_heroID_actorID_heroCompoundUniqueInput = {
  ID_actor: number
  ID_hero: number
}

export type actors_heroCountOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
  ID_hero?: Prisma.SortOrder
  is_playing?: Prisma.SortOrder
}

export type actors_heroAvgOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
  ID_hero?: Prisma.SortOrder
}

export type actors_heroMaxOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
  ID_hero?: Prisma.SortOrder
  is_playing?: Prisma.SortOrder
}

export type actors_heroMinOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
  ID_hero?: Prisma.SortOrder
  is_playing?: Prisma.SortOrder
}

export type actors_heroSumOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
  ID_hero?: Prisma.SortOrder
}

export type actors_heroCreateNestedManyWithoutActorInput = {
  create?: Prisma.XOR<Prisma.actors_heroCreateWithoutActorInput, Prisma.actors_heroUncheckedCreateWithoutActorInput> | Prisma.actors_heroCreateWithoutActorInput[] | Prisma.actors_heroUncheckedCreateWithoutActorInput[]
  connectOrCreate?: Prisma.actors_heroCreateOrConnectWithoutActorInput | Prisma.actors_heroCreateOrConnectWithoutActorInput[]
  createMany?: Prisma.actors_heroCreateManyActorInputEnvelope
  connect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
}

export type actors_heroUncheckedCreateNestedManyWithoutActorInput = {
  create?: Prisma.XOR<Prisma.actors_heroCreateWithoutActorInput, Prisma.actors_heroUncheckedCreateWithoutActorInput> | Prisma.actors_heroCreateWithoutActorInput[] | Prisma.actors_heroUncheckedCreateWithoutActorInput[]
  connectOrCreate?: Prisma.actors_heroCreateOrConnectWithoutActorInput | Prisma.actors_heroCreateOrConnectWithoutActorInput[]
  createMany?: Prisma.actors_heroCreateManyActorInputEnvelope
  connect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
}

export type actors_heroUpdateManyWithoutActorNestedInput = {
  create?: Prisma.XOR<Prisma.actors_heroCreateWithoutActorInput, Prisma.actors_heroUncheckedCreateWithoutActorInput> | Prisma.actors_heroCreateWithoutActorInput[] | Prisma.actors_heroUncheckedCreateWithoutActorInput[]
  connectOrCreate?: Prisma.actors_heroCreateOrConnectWithoutActorInput | Prisma.actors_heroCreateOrConnectWithoutActorInput[]
  upsert?: Prisma.actors_heroUpsertWithWhereUniqueWithoutActorInput | Prisma.actors_heroUpsertWithWhereUniqueWithoutActorInput[]
  createMany?: Prisma.actors_heroCreateManyActorInputEnvelope
  set?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  disconnect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  delete?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  connect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  update?: Prisma.actors_heroUpdateWithWhereUniqueWithoutActorInput | Prisma.actors_heroUpdateWithWhereUniqueWithoutActorInput[]
  updateMany?: Prisma.actors_heroUpdateManyWithWhereWithoutActorInput | Prisma.actors_heroUpdateManyWithWhereWithoutActorInput[]
  deleteMany?: Prisma.actors_heroScalarWhereInput | Prisma.actors_heroScalarWhereInput[]
}

export type actors_heroUncheckedUpdateManyWithoutActorNestedInput = {
  create?: Prisma.XOR<Prisma.actors_heroCreateWithoutActorInput, Prisma.actors_heroUncheckedCreateWithoutActorInput> | Prisma.actors_heroCreateWithoutActorInput[] | Prisma.actors_heroUncheckedCreateWithoutActorInput[]
  connectOrCreate?: Prisma.actors_heroCreateOrConnectWithoutActorInput | Prisma.actors_heroCreateOrConnectWithoutActorInput[]
  upsert?: Prisma.actors_heroUpsertWithWhereUniqueWithoutActorInput | Prisma.actors_heroUpsertWithWhereUniqueWithoutActorInput[]
  createMany?: Prisma.actors_heroCreateManyActorInputEnvelope
  set?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  disconnect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  delete?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  connect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  update?: Prisma.actors_heroUpdateWithWhereUniqueWithoutActorInput | Prisma.actors_heroUpdateWithWhereUniqueWithoutActorInput[]
  updateMany?: Prisma.actors_heroUpdateManyWithWhereWithoutActorInput | Prisma.actors_heroUpdateManyWithWhereWithoutActorInput[]
  deleteMany?: Prisma.actors_heroScalarWhereInput | Prisma.actors_heroScalarWhereInput[]
}

export type NullableBoolFieldUpdateOperationsInput = {
  set?: boolean | null
}

export type actors_heroCreateNestedManyWithoutHeroInput = {
  create?: Prisma.XOR<Prisma.actors_heroCreateWithoutHeroInput, Prisma.actors_heroUncheckedCreateWithoutHeroInput> | Prisma.actors_heroCreateWithoutHeroInput[] | Prisma.actors_heroUncheckedCreateWithoutHeroInput[]
  connectOrCreate?: Prisma.actors_heroCreateOrConnectWithoutHeroInput | Prisma.actors_heroCreateOrConnectWithoutHeroInput[]
  createMany?: Prisma.actors_heroCreateManyHeroInputEnvelope
  connect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
}

export type actors_heroUncheckedCreateNestedManyWithoutHeroInput = {
  create?: Prisma.XOR<Prisma.actors_heroCreateWithoutHeroInput, Prisma.actors_heroUncheckedCreateWithoutHeroInput> | Prisma.actors_heroCreateWithoutHeroInput[] | Prisma.actors_heroUncheckedCreateWithoutHeroInput[]
  connectOrCreate?: Prisma.actors_heroCreateOrConnectWithoutHeroInput | Prisma.actors_heroCreateOrConnectWithoutHeroInput[]
  createMany?: Prisma.actors_heroCreateManyHeroInputEnvelope
  connect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
}

export type actors_heroUpdateManyWithoutHeroNestedInput = {
  create?: Prisma.XOR<Prisma.actors_heroCreateWithoutHeroInput, Prisma.actors_heroUncheckedCreateWithoutHeroInput> | Prisma.actors_heroCreateWithoutHeroInput[] | Prisma.actors_heroUncheckedCreateWithoutHeroInput[]
  connectOrCreate?: Prisma.actors_heroCreateOrConnectWithoutHeroInput | Prisma.actors_heroCreateOrConnectWithoutHeroInput[]
  upsert?: Prisma.actors_heroUpsertWithWhereUniqueWithoutHeroInput | Prisma.actors_heroUpsertWithWhereUniqueWithoutHeroInput[]
  createMany?: Prisma.actors_heroCreateManyHeroInputEnvelope
  set?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  disconnect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  delete?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  connect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  update?: Prisma.actors_heroUpdateWithWhereUniqueWithoutHeroInput | Prisma.actors_heroUpdateWithWhereUniqueWithoutHeroInput[]
  updateMany?: Prisma.actors_heroUpdateManyWithWhereWithoutHeroInput | Prisma.actors_heroUpdateManyWithWhereWithoutHeroInput[]
  deleteMany?: Prisma.actors_heroScalarWhereInput | Prisma.actors_heroScalarWhereInput[]
}

export type actors_heroUncheckedUpdateManyWithoutHeroNestedInput = {
  create?: Prisma.XOR<Prisma.actors_heroCreateWithoutHeroInput, Prisma.actors_heroUncheckedCreateWithoutHeroInput> | Prisma.actors_heroCreateWithoutHeroInput[] | Prisma.actors_heroUncheckedCreateWithoutHeroInput[]
  connectOrCreate?: Prisma.actors_heroCreateOrConnectWithoutHeroInput | Prisma.actors_heroCreateOrConnectWithoutHeroInput[]
  upsert?: Prisma.actors_heroUpsertWithWhereUniqueWithoutHeroInput | Prisma.actors_heroUpsertWithWhereUniqueWithoutHeroInput[]
  createMany?: Prisma.actors_heroCreateManyHeroInputEnvelope
  set?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  disconnect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  delete?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  connect?: Prisma.actors_heroWhereUniqueInput | Prisma.actors_heroWhereUniqueInput[]
  update?: Prisma.actors_heroUpdateWithWhereUniqueWithoutHeroInput | Prisma.actors_heroUpdateWithWhereUniqueWithoutHeroInput[]
  updateMany?: Prisma.actors_heroUpdateManyWithWhereWithoutHeroInput | Prisma.actors_heroUpdateManyWithWhereWithoutHeroInput[]
  deleteMany?: Prisma.actors_heroScalarWhereInput | Prisma.actors_heroScalarWhereInput[]
}

export type actors_heroCreateWithoutActorInput = {
  is_playing?: boolean | null
  hero: Prisma.heroCreateNestedOneWithoutActors_heroInput
}

export type actors_heroUncheckedCreateWithoutActorInput = {
  ID_hero: number
  is_playing?: boolean | null
}

export type actors_heroCreateOrConnectWithoutActorInput = {
  where: Prisma.actors_heroWhereUniqueInput
  create: Prisma.XOR<Prisma.actors_heroCreateWithoutActorInput, Prisma.actors_heroUncheckedCreateWithoutActorInput>
}

export type actors_heroCreateManyActorInputEnvelope = {
  data: Prisma.actors_heroCreateManyActorInput | Prisma.actors_heroCreateManyActorInput[]
  skipDuplicates?: boolean
}

export type actors_heroUpsertWithWhereUniqueWithoutActorInput = {
  where: Prisma.actors_heroWhereUniqueInput
  update: Prisma.XOR<Prisma.actors_heroUpdateWithoutActorInput, Prisma.actors_heroUncheckedUpdateWithoutActorInput>
  create: Prisma.XOR<Prisma.actors_heroCreateWithoutActorInput, Prisma.actors_heroUncheckedCreateWithoutActorInput>
}

export type actors_heroUpdateWithWhereUniqueWithoutActorInput = {
  where: Prisma.actors_heroWhereUniqueInput
  data: Prisma.XOR<Prisma.actors_heroUpdateWithoutActorInput, Prisma.actors_heroUncheckedUpdateWithoutActorInput>
}

export type actors_heroUpdateManyWithWhereWithoutActorInput = {
  where: Prisma.actors_heroScalarWhereInput
  data: Prisma.XOR<Prisma.actors_heroUpdateManyMutationInput, Prisma.actors_heroUncheckedUpdateManyWithoutActorInput>
}

export type actors_heroScalarWhereInput = {
  AND?: Prisma.actors_heroScalarWhereInput | Prisma.actors_heroScalarWhereInput[]
  OR?: Prisma.actors_heroScalarWhereInput[]
  NOT?: Prisma.actors_heroScalarWhereInput | Prisma.actors_heroScalarWhereInput[]
  ID_actor?: Prisma.IntFilter<"actors_hero"> | number
  ID_hero?: Prisma.IntFilter<"actors_hero"> | number
  is_playing?: Prisma.BoolNullableFilter<"actors_hero"> | boolean | null
}

export type actors_heroCreateWithoutHeroInput = {
  is_playing?: boolean | null
  actor: Prisma.actorCreateNestedOneWithoutActors_heroInput
}

export type actors_heroUncheckedCreateWithoutHeroInput = {
  ID_actor: number
  is_playing?: boolean | null
}

export type actors_heroCreateOrConnectWithoutHeroInput = {
  where: Prisma.actors_heroWhereUniqueInput
  create: Prisma.XOR<Prisma.actors_heroCreateWithoutHeroInput, Prisma.actors_heroUncheckedCreateWithoutHeroInput>
}

export type actors_heroCreateManyHeroInputEnvelope = {
  data: Prisma.actors_heroCreateManyHeroInput | Prisma.actors_heroCreateManyHeroInput[]
  skipDuplicates?: boolean
}

export type actors_heroUpsertWithWhereUniqueWithoutHeroInput = {
  where: Prisma.actors_heroWhereUniqueInput
  update: Prisma.XOR<Prisma.actors_heroUpdateWithoutHeroInput, Prisma.actors_heroUncheckedUpdateWithoutHeroInput>
  create: Prisma.XOR<Prisma.actors_heroCreateWithoutHeroInput, Prisma.actors_heroUncheckedCreateWithoutHeroInput>
}

export type actors_heroUpdateWithWhereUniqueWithoutHeroInput = {
  where: Prisma.actors_heroWhereUniqueInput
  data: Prisma.XOR<Prisma.actors_heroUpdateWithoutHeroInput, Prisma.actors_heroUncheckedUpdateWithoutHeroInput>
}

export type actors_heroUpdateManyWithWhereWithoutHeroInput = {
  where: Prisma.actors_heroScalarWhereInput
  data: Prisma.XOR<Prisma.actors_heroUpdateManyMutationInput, Prisma.actors_heroUncheckedUpdateManyWithoutHeroInput>
}

export type actors_heroCreateManyActorInput = {
  ID_hero: number
  is_playing?: boolean | null
}

export type actors_heroUpdateWithoutActorInput = {
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  hero?: Prisma.heroUpdateOneRequiredWithoutActors_heroNestedInput
}

export type actors_heroUncheckedUpdateWithoutActorInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type actors_heroUncheckedUpdateManyWithoutActorInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type actors_heroCreateManyHeroInput = {
  ID_actor: number
  is_playing?: boolean | null
}

export type actors_heroUpdateWithoutHeroInput = {
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
  actor?: Prisma.actorUpdateOneRequiredWithoutActors_heroNestedInput
}

export type actors_heroUncheckedUpdateWithoutHeroInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}

export type actors_heroUncheckedUpdateManyWithoutHeroInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  is_playing?: Prisma.NullableBoolFieldUpdateOperationsInput | boolean | null
}



export type actors_heroSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  ID_actor?: boolean
  ID_hero?: boolean
  is_playing?: boolean
  actor?: boolean | Prisma.actorDefaultArgs<ExtArgs>
  hero?: boolean | Prisma.heroDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actors_hero"]>



export type actors_heroSelectScalar = {
  ID_actor?: boolean
  ID_hero?: boolean
  is_playing?: boolean
}

export type actors_heroOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"ID_actor" | "ID_hero" | "is_playing", ExtArgs["result"]["actors_hero"]>
export type actors_heroInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actor?: boolean | Prisma.actorDefaultArgs<ExtArgs>
  hero?: boolean | Prisma.heroDefaultArgs<ExtArgs>
}

export type $actors_heroPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "actors_hero"
  objects: {
    actor: Prisma.$actorPayload<ExtArgs>
    hero: Prisma.$heroPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    ID_actor: number
    ID_hero: number
    is_playing: boolean | null
  }, ExtArgs["result"]["actors_hero"]>
  composites: {}
}

export type actors_heroGetPayload<S extends boolean | null | undefined | actors_heroDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$actors_heroPayload, S>

export type actors_heroCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<actors_heroFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Actors_heroCountAggregateInputType | true
  }

export interface actors_heroDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['actors_hero'], meta: { name: 'actors_hero' } }
  /**
   * Find zero or one Actors_hero that matches the filter.
   * @param {actors_heroFindUniqueArgs} args - Arguments to find a Actors_hero
   * @example
   * // Get one Actors_hero
   * const actors_hero = await prisma.actors_hero.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends actors_heroFindUniqueArgs>(args: Prisma.SelectSubset<T, actors_heroFindUniqueArgs<ExtArgs>>): Prisma.Prisma__actors_heroClient<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Actors_hero that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {actors_heroFindUniqueOrThrowArgs} args - Arguments to find a Actors_hero
   * @example
   * // Get one Actors_hero
   * const actors_hero = await prisma.actors_hero.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends actors_heroFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, actors_heroFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__actors_heroClient<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Actors_hero that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actors_heroFindFirstArgs} args - Arguments to find a Actors_hero
   * @example
   * // Get one Actors_hero
   * const actors_hero = await prisma.actors_hero.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends actors_heroFindFirstArgs>(args?: Prisma.SelectSubset<T, actors_heroFindFirstArgs<ExtArgs>>): Prisma.Prisma__actors_heroClient<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Actors_hero that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actors_heroFindFirstOrThrowArgs} args - Arguments to find a Actors_hero
   * @example
   * // Get one Actors_hero
   * const actors_hero = await prisma.actors_hero.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends actors_heroFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, actors_heroFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__actors_heroClient<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Actors_heroes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actors_heroFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Actors_heroes
   * const actors_heroes = await prisma.actors_hero.findMany()
   * 
   * // Get first 10 Actors_heroes
   * const actors_heroes = await prisma.actors_hero.findMany({ take: 10 })
   * 
   * // Only select the `ID_actor`
   * const actors_heroWithID_actorOnly = await prisma.actors_hero.findMany({ select: { ID_actor: true } })
   * 
   */
  findMany<T extends actors_heroFindManyArgs>(args?: Prisma.SelectSubset<T, actors_heroFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Actors_hero.
   * @param {actors_heroCreateArgs} args - Arguments to create a Actors_hero.
   * @example
   * // Create one Actors_hero
   * const Actors_hero = await prisma.actors_hero.create({
   *   data: {
   *     // ... data to create a Actors_hero
   *   }
   * })
   * 
   */
  create<T extends actors_heroCreateArgs>(args: Prisma.SelectSubset<T, actors_heroCreateArgs<ExtArgs>>): Prisma.Prisma__actors_heroClient<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Actors_heroes.
   * @param {actors_heroCreateManyArgs} args - Arguments to create many Actors_heroes.
   * @example
   * // Create many Actors_heroes
   * const actors_hero = await prisma.actors_hero.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends actors_heroCreateManyArgs>(args?: Prisma.SelectSubset<T, actors_heroCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Actors_hero.
   * @param {actors_heroDeleteArgs} args - Arguments to delete one Actors_hero.
   * @example
   * // Delete one Actors_hero
   * const Actors_hero = await prisma.actors_hero.delete({
   *   where: {
   *     // ... filter to delete one Actors_hero
   *   }
   * })
   * 
   */
  delete<T extends actors_heroDeleteArgs>(args: Prisma.SelectSubset<T, actors_heroDeleteArgs<ExtArgs>>): Prisma.Prisma__actors_heroClient<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Actors_hero.
   * @param {actors_heroUpdateArgs} args - Arguments to update one Actors_hero.
   * @example
   * // Update one Actors_hero
   * const actors_hero = await prisma.actors_hero.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends actors_heroUpdateArgs>(args: Prisma.SelectSubset<T, actors_heroUpdateArgs<ExtArgs>>): Prisma.Prisma__actors_heroClient<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Actors_heroes.
   * @param {actors_heroDeleteManyArgs} args - Arguments to filter Actors_heroes to delete.
   * @example
   * // Delete a few Actors_heroes
   * const { count } = await prisma.actors_hero.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends actors_heroDeleteManyArgs>(args?: Prisma.SelectSubset<T, actors_heroDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Actors_heroes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actors_heroUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Actors_heroes
   * const actors_hero = await prisma.actors_hero.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends actors_heroUpdateManyArgs>(args: Prisma.SelectSubset<T, actors_heroUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Actors_hero.
   * @param {actors_heroUpsertArgs} args - Arguments to update or create a Actors_hero.
   * @example
   * // Update or create a Actors_hero
   * const actors_hero = await prisma.actors_hero.upsert({
   *   create: {
   *     // ... data to create a Actors_hero
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Actors_hero we want to update
   *   }
   * })
   */
  upsert<T extends actors_heroUpsertArgs>(args: Prisma.SelectSubset<T, actors_heroUpsertArgs<ExtArgs>>): Prisma.Prisma__actors_heroClient<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Actors_heroes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actors_heroCountArgs} args - Arguments to filter Actors_heroes to count.
   * @example
   * // Count the number of Actors_heroes
   * const count = await prisma.actors_hero.count({
   *   where: {
   *     // ... the filter for the Actors_heroes we want to count
   *   }
   * })
  **/
  count<T extends actors_heroCountArgs>(
    args?: Prisma.Subset<T, actors_heroCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Actors_heroCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Actors_hero.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Actors_heroAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Actors_heroAggregateArgs>(args: Prisma.Subset<T, Actors_heroAggregateArgs>): Prisma.PrismaPromise<GetActors_heroAggregateType<T>>

  /**
   * Group by Actors_hero.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actors_heroGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends actors_heroGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: actors_heroGroupByArgs['orderBy'] }
      : { orderBy?: actors_heroGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, actors_heroGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActors_heroGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the actors_hero model
 */
readonly fields: actors_heroFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for actors_hero.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__actors_heroClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  actor<T extends Prisma.actorDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.actorDefaultArgs<ExtArgs>>): Prisma.Prisma__actorClient<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  hero<T extends Prisma.heroDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.heroDefaultArgs<ExtArgs>>): Prisma.Prisma__heroClient<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the actors_hero model
 */
export interface actors_heroFieldRefs {
  readonly ID_actor: Prisma.FieldRef<"actors_hero", 'Int'>
  readonly ID_hero: Prisma.FieldRef<"actors_hero", 'Int'>
  readonly is_playing: Prisma.FieldRef<"actors_hero", 'Boolean'>
}
    

// Custom InputTypes
/**
 * actors_hero findUnique
 */
export type actors_heroFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  /**
   * Filter, which actors_hero to fetch.
   */
  where: Prisma.actors_heroWhereUniqueInput
}

/**
 * actors_hero findUniqueOrThrow
 */
export type actors_heroFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  /**
   * Filter, which actors_hero to fetch.
   */
  where: Prisma.actors_heroWhereUniqueInput
}

/**
 * actors_hero findFirst
 */
export type actors_heroFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  /**
   * Filter, which actors_hero to fetch.
   */
  where?: Prisma.actors_heroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of actors_heroes to fetch.
   */
  orderBy?: Prisma.actors_heroOrderByWithRelationInput | Prisma.actors_heroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for actors_heroes.
   */
  cursor?: Prisma.actors_heroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` actors_heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` actors_heroes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of actors_heroes.
   */
  distinct?: Prisma.Actors_heroScalarFieldEnum | Prisma.Actors_heroScalarFieldEnum[]
}

/**
 * actors_hero findFirstOrThrow
 */
export type actors_heroFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  /**
   * Filter, which actors_hero to fetch.
   */
  where?: Prisma.actors_heroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of actors_heroes to fetch.
   */
  orderBy?: Prisma.actors_heroOrderByWithRelationInput | Prisma.actors_heroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for actors_heroes.
   */
  cursor?: Prisma.actors_heroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` actors_heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` actors_heroes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of actors_heroes.
   */
  distinct?: Prisma.Actors_heroScalarFieldEnum | Prisma.Actors_heroScalarFieldEnum[]
}

/**
 * actors_hero findMany
 */
export type actors_heroFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  /**
   * Filter, which actors_heroes to fetch.
   */
  where?: Prisma.actors_heroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of actors_heroes to fetch.
   */
  orderBy?: Prisma.actors_heroOrderByWithRelationInput | Prisma.actors_heroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing actors_heroes.
   */
  cursor?: Prisma.actors_heroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` actors_heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` actors_heroes.
   */
  skip?: number
  distinct?: Prisma.Actors_heroScalarFieldEnum | Prisma.Actors_heroScalarFieldEnum[]
}

/**
 * actors_hero create
 */
export type actors_heroCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  /**
   * The data needed to create a actors_hero.
   */
  data: Prisma.XOR<Prisma.actors_heroCreateInput, Prisma.actors_heroUncheckedCreateInput>
}

/**
 * actors_hero createMany
 */
export type actors_heroCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many actors_heroes.
   */
  data: Prisma.actors_heroCreateManyInput | Prisma.actors_heroCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * actors_hero update
 */
export type actors_heroUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  /**
   * The data needed to update a actors_hero.
   */
  data: Prisma.XOR<Prisma.actors_heroUpdateInput, Prisma.actors_heroUncheckedUpdateInput>
  /**
   * Choose, which actors_hero to update.
   */
  where: Prisma.actors_heroWhereUniqueInput
}

/**
 * actors_hero updateMany
 */
export type actors_heroUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update actors_heroes.
   */
  data: Prisma.XOR<Prisma.actors_heroUpdateManyMutationInput, Prisma.actors_heroUncheckedUpdateManyInput>
  /**
   * Filter which actors_heroes to update
   */
  where?: Prisma.actors_heroWhereInput
  /**
   * Limit how many actors_heroes to update.
   */
  limit?: number
}

/**
 * actors_hero upsert
 */
export type actors_heroUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  /**
   * The filter to search for the actors_hero to update in case it exists.
   */
  where: Prisma.actors_heroWhereUniqueInput
  /**
   * In case the actors_hero found by the `where` argument doesn't exist, create a new actors_hero with this data.
   */
  create: Prisma.XOR<Prisma.actors_heroCreateInput, Prisma.actors_heroUncheckedCreateInput>
  /**
   * In case the actors_hero was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.actors_heroUpdateInput, Prisma.actors_heroUncheckedUpdateInput>
}

/**
 * actors_hero delete
 */
export type actors_heroDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  /**
   * Filter which actors_hero to delete.
   */
  where: Prisma.actors_heroWhereUniqueInput
}

/**
 * actors_hero deleteMany
 */
export type actors_heroDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which actors_heroes to delete
   */
  where?: Prisma.actors_heroWhereInput
  /**
   * Limit how many actors_heroes to delete.
   */
  limit?: number
}

/**
 * actors_hero without action
 */
export type actors_heroDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
}
