
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `actor` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model actor
 * 
 */
export type actorModel = runtime.Types.Result.DefaultSelection<Prisma.$actorPayload>

export type AggregateActor = {
  _count: ActorCountAggregateOutputType | null
  _avg: ActorAvgAggregateOutputType | null
  _sum: ActorSumAggregateOutputType | null
  _min: ActorMinAggregateOutputType | null
  _max: ActorMaxAggregateOutputType | null
}

export type ActorAvgAggregateOutputType = {
  ID_actor: number | null
}

export type ActorSumAggregateOutputType = {
  ID_actor: number | null
}

export type ActorMinAggregateOutputType = {
  ID_actor: number | null
  actor_full_name: string | null
  actor_text: string | null
}

export type ActorMaxAggregateOutputType = {
  ID_actor: number | null
  actor_full_name: string | null
  actor_text: string | null
}

export type ActorCountAggregateOutputType = {
  ID_actor: number
  actor_full_name: number
  actor_text: number
  _all: number
}


export type ActorAvgAggregateInputType = {
  ID_actor?: true
}

export type ActorSumAggregateInputType = {
  ID_actor?: true
}

export type ActorMinAggregateInputType = {
  ID_actor?: true
  actor_full_name?: true
  actor_text?: true
}

export type ActorMaxAggregateInputType = {
  ID_actor?: true
  actor_full_name?: true
  actor_text?: true
}

export type ActorCountAggregateInputType = {
  ID_actor?: true
  actor_full_name?: true
  actor_text?: true
  _all?: true
}

export type ActorAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which actor to aggregate.
   */
  where?: Prisma.actorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of actors to fetch.
   */
  orderBy?: Prisma.actorOrderByWithRelationInput | Prisma.actorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.actorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` actors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` actors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned actors
  **/
  _count?: true | ActorCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ActorAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ActorSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ActorMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ActorMaxAggregateInputType
}

export type GetActorAggregateType<T extends ActorAggregateArgs> = {
      [P in keyof T & keyof AggregateActor]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateActor[P]>
    : Prisma.GetScalarType<T[P], AggregateActor[P]>
}




export type actorGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.actorWhereInput
  orderBy?: Prisma.actorOrderByWithAggregationInput | Prisma.actorOrderByWithAggregationInput[]
  by: Prisma.ActorScalarFieldEnum[] | Prisma.ActorScalarFieldEnum
  having?: Prisma.actorScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ActorCountAggregateInputType | true
  _avg?: ActorAvgAggregateInputType
  _sum?: ActorSumAggregateInputType
  _min?: ActorMinAggregateInputType
  _max?: ActorMaxAggregateInputType
}

export type ActorGroupByOutputType = {
  ID_actor: number
  actor_full_name: string | null
  actor_text: string | null
  _count: ActorCountAggregateOutputType | null
  _avg: ActorAvgAggregateOutputType | null
  _sum: ActorSumAggregateOutputType | null
  _min: ActorMinAggregateOutputType | null
  _max: ActorMaxAggregateOutputType | null
}

type GetActorGroupByPayload<T extends actorGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ActorGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ActorGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ActorGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ActorGroupByOutputType[P]>
      }
    >
  >



export type actorWhereInput = {
  AND?: Prisma.actorWhereInput | Prisma.actorWhereInput[]
  OR?: Prisma.actorWhereInput[]
  NOT?: Prisma.actorWhereInput | Prisma.actorWhereInput[]
  ID_actor?: Prisma.IntFilter<"actor"> | number
  actor_full_name?: Prisma.StringNullableFilter<"actor"> | string | null
  actor_text?: Prisma.StringNullableFilter<"actor"> | string | null
  actors_hero?: Prisma.Actors_heroListRelationFilter
}

export type actorOrderByWithRelationInput = {
  ID_actor?: Prisma.SortOrder
  actor_full_name?: Prisma.SortOrderInput | Prisma.SortOrder
  actor_text?: Prisma.SortOrderInput | Prisma.SortOrder
  actors_hero?: Prisma.actors_heroOrderByRelationAggregateInput
  _relevance?: Prisma.actorOrderByRelevanceInput
}

export type actorWhereUniqueInput = Prisma.AtLeast<{
  ID_actor?: number
  AND?: Prisma.actorWhereInput | Prisma.actorWhereInput[]
  OR?: Prisma.actorWhereInput[]
  NOT?: Prisma.actorWhereInput | Prisma.actorWhereInput[]
  actor_full_name?: Prisma.StringNullableFilter<"actor"> | string | null
  actor_text?: Prisma.StringNullableFilter<"actor"> | string | null
  actors_hero?: Prisma.Actors_heroListRelationFilter
}, "ID_actor">

export type actorOrderByWithAggregationInput = {
  ID_actor?: Prisma.SortOrder
  actor_full_name?: Prisma.SortOrderInput | Prisma.SortOrder
  actor_text?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.actorCountOrderByAggregateInput
  _avg?: Prisma.actorAvgOrderByAggregateInput
  _max?: Prisma.actorMaxOrderByAggregateInput
  _min?: Prisma.actorMinOrderByAggregateInput
  _sum?: Prisma.actorSumOrderByAggregateInput
}

export type actorScalarWhereWithAggregatesInput = {
  AND?: Prisma.actorScalarWhereWithAggregatesInput | Prisma.actorScalarWhereWithAggregatesInput[]
  OR?: Prisma.actorScalarWhereWithAggregatesInput[]
  NOT?: Prisma.actorScalarWhereWithAggregatesInput | Prisma.actorScalarWhereWithAggregatesInput[]
  ID_actor?: Prisma.IntWithAggregatesFilter<"actor"> | number
  actor_full_name?: Prisma.StringNullableWithAggregatesFilter<"actor"> | string | null
  actor_text?: Prisma.StringNullableWithAggregatesFilter<"actor"> | string | null
}

export type actorCreateInput = {
  ID_actor: number
  actor_full_name?: string | null
  actor_text?: string | null
  actors_hero?: Prisma.actors_heroCreateNestedManyWithoutActorInput
}

export type actorUncheckedCreateInput = {
  ID_actor: number
  actor_full_name?: string | null
  actor_text?: string | null
  actors_hero?: Prisma.actors_heroUncheckedCreateNestedManyWithoutActorInput
}

export type actorUpdateInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  actor_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actor_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actors_hero?: Prisma.actors_heroUpdateManyWithoutActorNestedInput
}

export type actorUncheckedUpdateInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  actor_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actor_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actors_hero?: Prisma.actors_heroUncheckedUpdateManyWithoutActorNestedInput
}

export type actorCreateManyInput = {
  ID_actor: number
  actor_full_name?: string | null
  actor_text?: string | null
}

export type actorUpdateManyMutationInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  actor_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actor_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type actorUncheckedUpdateManyInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  actor_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actor_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type actorOrderByRelevanceInput = {
  fields: Prisma.actorOrderByRelevanceFieldEnum | Prisma.actorOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type actorCountOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
  actor_full_name?: Prisma.SortOrder
  actor_text?: Prisma.SortOrder
}

export type actorAvgOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
}

export type actorMaxOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
  actor_full_name?: Prisma.SortOrder
  actor_text?: Prisma.SortOrder
}

export type actorMinOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
  actor_full_name?: Prisma.SortOrder
  actor_text?: Prisma.SortOrder
}

export type actorSumOrderByAggregateInput = {
  ID_actor?: Prisma.SortOrder
}

export type ActorScalarRelationFilter = {
  is?: Prisma.actorWhereInput
  isNot?: Prisma.actorWhereInput
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type actorCreateNestedOneWithoutActors_heroInput = {
  create?: Prisma.XOR<Prisma.actorCreateWithoutActors_heroInput, Prisma.actorUncheckedCreateWithoutActors_heroInput>
  connectOrCreate?: Prisma.actorCreateOrConnectWithoutActors_heroInput
  connect?: Prisma.actorWhereUniqueInput
}

export type actorUpdateOneRequiredWithoutActors_heroNestedInput = {
  create?: Prisma.XOR<Prisma.actorCreateWithoutActors_heroInput, Prisma.actorUncheckedCreateWithoutActors_heroInput>
  connectOrCreate?: Prisma.actorCreateOrConnectWithoutActors_heroInput
  upsert?: Prisma.actorUpsertWithoutActors_heroInput
  connect?: Prisma.actorWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.actorUpdateToOneWithWhereWithoutActors_heroInput, Prisma.actorUpdateWithoutActors_heroInput>, Prisma.actorUncheckedUpdateWithoutActors_heroInput>
}

export type actorCreateWithoutActors_heroInput = {
  ID_actor: number
  actor_full_name?: string | null
  actor_text?: string | null
}

export type actorUncheckedCreateWithoutActors_heroInput = {
  ID_actor: number
  actor_full_name?: string | null
  actor_text?: string | null
}

export type actorCreateOrConnectWithoutActors_heroInput = {
  where: Prisma.actorWhereUniqueInput
  create: Prisma.XOR<Prisma.actorCreateWithoutActors_heroInput, Prisma.actorUncheckedCreateWithoutActors_heroInput>
}

export type actorUpsertWithoutActors_heroInput = {
  update: Prisma.XOR<Prisma.actorUpdateWithoutActors_heroInput, Prisma.actorUncheckedUpdateWithoutActors_heroInput>
  create: Prisma.XOR<Prisma.actorCreateWithoutActors_heroInput, Prisma.actorUncheckedCreateWithoutActors_heroInput>
  where?: Prisma.actorWhereInput
}

export type actorUpdateToOneWithWhereWithoutActors_heroInput = {
  where?: Prisma.actorWhereInput
  data: Prisma.XOR<Prisma.actorUpdateWithoutActors_heroInput, Prisma.actorUncheckedUpdateWithoutActors_heroInput>
}

export type actorUpdateWithoutActors_heroInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  actor_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actor_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type actorUncheckedUpdateWithoutActors_heroInput = {
  ID_actor?: Prisma.IntFieldUpdateOperationsInput | number
  actor_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  actor_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type ActorCountOutputType
 */

export type ActorCountOutputType = {
  actors_hero: number
}

export type ActorCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actors_hero?: boolean | ActorCountOutputTypeCountActors_heroArgs
}

/**
 * ActorCountOutputType without action
 */
export type ActorCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ActorCountOutputType
   */
  select?: Prisma.ActorCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ActorCountOutputType without action
 */
export type ActorCountOutputTypeCountActors_heroArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.actors_heroWhereInput
}


export type actorSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  ID_actor?: boolean
  actor_full_name?: boolean
  actor_text?: boolean
  actors_hero?: boolean | Prisma.actor$actors_heroArgs<ExtArgs>
  _count?: boolean | Prisma.ActorCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["actor"]>



export type actorSelectScalar = {
  ID_actor?: boolean
  actor_full_name?: boolean
  actor_text?: boolean
}

export type actorOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"ID_actor" | "actor_full_name" | "actor_text", ExtArgs["result"]["actor"]>
export type actorInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actors_hero?: boolean | Prisma.actor$actors_heroArgs<ExtArgs>
  _count?: boolean | Prisma.ActorCountOutputTypeDefaultArgs<ExtArgs>
}

export type $actorPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "actor"
  objects: {
    actors_hero: Prisma.$actors_heroPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    ID_actor: number
    actor_full_name: string | null
    actor_text: string | null
  }, ExtArgs["result"]["actor"]>
  composites: {}
}

export type actorGetPayload<S extends boolean | null | undefined | actorDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$actorPayload, S>

export type actorCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<actorFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ActorCountAggregateInputType | true
  }

export interface actorDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['actor'], meta: { name: 'actor' } }
  /**
   * Find zero or one Actor that matches the filter.
   * @param {actorFindUniqueArgs} args - Arguments to find a Actor
   * @example
   * // Get one Actor
   * const actor = await prisma.actor.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends actorFindUniqueArgs>(args: Prisma.SelectSubset<T, actorFindUniqueArgs<ExtArgs>>): Prisma.Prisma__actorClient<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Actor that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {actorFindUniqueOrThrowArgs} args - Arguments to find a Actor
   * @example
   * // Get one Actor
   * const actor = await prisma.actor.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends actorFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, actorFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__actorClient<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Actor that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actorFindFirstArgs} args - Arguments to find a Actor
   * @example
   * // Get one Actor
   * const actor = await prisma.actor.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends actorFindFirstArgs>(args?: Prisma.SelectSubset<T, actorFindFirstArgs<ExtArgs>>): Prisma.Prisma__actorClient<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Actor that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actorFindFirstOrThrowArgs} args - Arguments to find a Actor
   * @example
   * // Get one Actor
   * const actor = await prisma.actor.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends actorFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, actorFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__actorClient<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Actors that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actorFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Actors
   * const actors = await prisma.actor.findMany()
   * 
   * // Get first 10 Actors
   * const actors = await prisma.actor.findMany({ take: 10 })
   * 
   * // Only select the `ID_actor`
   * const actorWithID_actorOnly = await prisma.actor.findMany({ select: { ID_actor: true } })
   * 
   */
  findMany<T extends actorFindManyArgs>(args?: Prisma.SelectSubset<T, actorFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Actor.
   * @param {actorCreateArgs} args - Arguments to create a Actor.
   * @example
   * // Create one Actor
   * const Actor = await prisma.actor.create({
   *   data: {
   *     // ... data to create a Actor
   *   }
   * })
   * 
   */
  create<T extends actorCreateArgs>(args: Prisma.SelectSubset<T, actorCreateArgs<ExtArgs>>): Prisma.Prisma__actorClient<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Actors.
   * @param {actorCreateManyArgs} args - Arguments to create many Actors.
   * @example
   * // Create many Actors
   * const actor = await prisma.actor.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends actorCreateManyArgs>(args?: Prisma.SelectSubset<T, actorCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Actor.
   * @param {actorDeleteArgs} args - Arguments to delete one Actor.
   * @example
   * // Delete one Actor
   * const Actor = await prisma.actor.delete({
   *   where: {
   *     // ... filter to delete one Actor
   *   }
   * })
   * 
   */
  delete<T extends actorDeleteArgs>(args: Prisma.SelectSubset<T, actorDeleteArgs<ExtArgs>>): Prisma.Prisma__actorClient<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Actor.
   * @param {actorUpdateArgs} args - Arguments to update one Actor.
   * @example
   * // Update one Actor
   * const actor = await prisma.actor.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends actorUpdateArgs>(args: Prisma.SelectSubset<T, actorUpdateArgs<ExtArgs>>): Prisma.Prisma__actorClient<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Actors.
   * @param {actorDeleteManyArgs} args - Arguments to filter Actors to delete.
   * @example
   * // Delete a few Actors
   * const { count } = await prisma.actor.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends actorDeleteManyArgs>(args?: Prisma.SelectSubset<T, actorDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Actors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actorUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Actors
   * const actor = await prisma.actor.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends actorUpdateManyArgs>(args: Prisma.SelectSubset<T, actorUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Actor.
   * @param {actorUpsertArgs} args - Arguments to update or create a Actor.
   * @example
   * // Update or create a Actor
   * const actor = await prisma.actor.upsert({
   *   create: {
   *     // ... data to create a Actor
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Actor we want to update
   *   }
   * })
   */
  upsert<T extends actorUpsertArgs>(args: Prisma.SelectSubset<T, actorUpsertArgs<ExtArgs>>): Prisma.Prisma__actorClient<runtime.Types.Result.GetResult<Prisma.$actorPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Actors.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actorCountArgs} args - Arguments to filter Actors to count.
   * @example
   * // Count the number of Actors
   * const count = await prisma.actor.count({
   *   where: {
   *     // ... the filter for the Actors we want to count
   *   }
   * })
  **/
  count<T extends actorCountArgs>(
    args?: Prisma.Subset<T, actorCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ActorCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Actor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ActorAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ActorAggregateArgs>(args: Prisma.Subset<T, ActorAggregateArgs>): Prisma.PrismaPromise<GetActorAggregateType<T>>

  /**
   * Group by Actor.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {actorGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends actorGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: actorGroupByArgs['orderBy'] }
      : { orderBy?: actorGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, actorGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetActorGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the actor model
 */
readonly fields: actorFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for actor.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__actorClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  actors_hero<T extends Prisma.actor$actors_heroArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.actor$actors_heroArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the actor model
 */
export interface actorFieldRefs {
  readonly ID_actor: Prisma.FieldRef<"actor", 'Int'>
  readonly actor_full_name: Prisma.FieldRef<"actor", 'String'>
  readonly actor_text: Prisma.FieldRef<"actor", 'String'>
}
    

// Custom InputTypes
/**
 * actor findUnique
 */
export type actorFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
  /**
   * Filter, which actor to fetch.
   */
  where: Prisma.actorWhereUniqueInput
}

/**
 * actor findUniqueOrThrow
 */
export type actorFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
  /**
   * Filter, which actor to fetch.
   */
  where: Prisma.actorWhereUniqueInput
}

/**
 * actor findFirst
 */
export type actorFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
  /**
   * Filter, which actor to fetch.
   */
  where?: Prisma.actorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of actors to fetch.
   */
  orderBy?: Prisma.actorOrderByWithRelationInput | Prisma.actorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for actors.
   */
  cursor?: Prisma.actorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` actors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` actors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of actors.
   */
  distinct?: Prisma.ActorScalarFieldEnum | Prisma.ActorScalarFieldEnum[]
}

/**
 * actor findFirstOrThrow
 */
export type actorFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
  /**
   * Filter, which actor to fetch.
   */
  where?: Prisma.actorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of actors to fetch.
   */
  orderBy?: Prisma.actorOrderByWithRelationInput | Prisma.actorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for actors.
   */
  cursor?: Prisma.actorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` actors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` actors.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of actors.
   */
  distinct?: Prisma.ActorScalarFieldEnum | Prisma.ActorScalarFieldEnum[]
}

/**
 * actor findMany
 */
export type actorFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
  /**
   * Filter, which actors to fetch.
   */
  where?: Prisma.actorWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of actors to fetch.
   */
  orderBy?: Prisma.actorOrderByWithRelationInput | Prisma.actorOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing actors.
   */
  cursor?: Prisma.actorWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` actors from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` actors.
   */
  skip?: number
  distinct?: Prisma.ActorScalarFieldEnum | Prisma.ActorScalarFieldEnum[]
}

/**
 * actor create
 */
export type actorCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
  /**
   * The data needed to create a actor.
   */
  data: Prisma.XOR<Prisma.actorCreateInput, Prisma.actorUncheckedCreateInput>
}

/**
 * actor createMany
 */
export type actorCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many actors.
   */
  data: Prisma.actorCreateManyInput | Prisma.actorCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * actor update
 */
export type actorUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
  /**
   * The data needed to update a actor.
   */
  data: Prisma.XOR<Prisma.actorUpdateInput, Prisma.actorUncheckedUpdateInput>
  /**
   * Choose, which actor to update.
   */
  where: Prisma.actorWhereUniqueInput
}

/**
 * actor updateMany
 */
export type actorUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update actors.
   */
  data: Prisma.XOR<Prisma.actorUpdateManyMutationInput, Prisma.actorUncheckedUpdateManyInput>
  /**
   * Filter which actors to update
   */
  where?: Prisma.actorWhereInput
  /**
   * Limit how many actors to update.
   */
  limit?: number
}

/**
 * actor upsert
 */
export type actorUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
  /**
   * The filter to search for the actor to update in case it exists.
   */
  where: Prisma.actorWhereUniqueInput
  /**
   * In case the actor found by the `where` argument doesn't exist, create a new actor with this data.
   */
  create: Prisma.XOR<Prisma.actorCreateInput, Prisma.actorUncheckedCreateInput>
  /**
   * In case the actor was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.actorUpdateInput, Prisma.actorUncheckedUpdateInput>
}

/**
 * actor delete
 */
export type actorDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
  /**
   * Filter which actor to delete.
   */
  where: Prisma.actorWhereUniqueInput
}

/**
 * actor deleteMany
 */
export type actorDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which actors to delete
   */
  where?: Prisma.actorWhereInput
  /**
   * Limit how many actors to delete.
   */
  limit?: number
}

/**
 * actor.actors_hero
 */
export type actor$actors_heroArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  where?: Prisma.actors_heroWhereInput
  orderBy?: Prisma.actors_heroOrderByWithRelationInput | Prisma.actors_heroOrderByWithRelationInput[]
  cursor?: Prisma.actors_heroWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Actors_heroScalarFieldEnum | Prisma.Actors_heroScalarFieldEnum[]
}

/**
 * actor without action
 */
export type actorDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actor
   */
  select?: Prisma.actorSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actor
   */
  omit?: Prisma.actorOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actorInclude<ExtArgs> | null
}
