
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `hall` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model hall
 * 
 */
export type hallModel = runtime.Types.Result.DefaultSelection<Prisma.$hallPayload>

export type AggregateHall = {
  _count: HallCountAggregateOutputType | null
  _avg: HallAvgAggregateOutputType | null
  _sum: HallSumAggregateOutputType | null
  _min: HallMinAggregateOutputType | null
  _max: HallMaxAggregateOutputType | null
}

export type HallAvgAggregateOutputType = {
  ID_hall: number | null
  hall_additional_seats: number | null
}

export type HallSumAggregateOutputType = {
  ID_hall: number | null
  hall_additional_seats: number | null
}

export type HallMinAggregateOutputType = {
  ID_hall: number | null
  hall_type_of: boolean | null
  hall_address: string | null
  hall_additional_seats: number | null
}

export type HallMaxAggregateOutputType = {
  ID_hall: number | null
  hall_type_of: boolean | null
  hall_address: string | null
  hall_additional_seats: number | null
}

export type HallCountAggregateOutputType = {
  ID_hall: number
  hall_type_of: number
  hall_address: number
  hall_additional_seats: number
  _all: number
}


export type HallAvgAggregateInputType = {
  ID_hall?: true
  hall_additional_seats?: true
}

export type HallSumAggregateInputType = {
  ID_hall?: true
  hall_additional_seats?: true
}

export type HallMinAggregateInputType = {
  ID_hall?: true
  hall_type_of?: true
  hall_address?: true
  hall_additional_seats?: true
}

export type HallMaxAggregateInputType = {
  ID_hall?: true
  hall_type_of?: true
  hall_address?: true
  hall_additional_seats?: true
}

export type HallCountAggregateInputType = {
  ID_hall?: true
  hall_type_of?: true
  hall_address?: true
  hall_additional_seats?: true
  _all?: true
}

export type HallAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which hall to aggregate.
   */
  where?: Prisma.hallWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of halls to fetch.
   */
  orderBy?: Prisma.hallOrderByWithRelationInput | Prisma.hallOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.hallWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` halls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` halls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned halls
  **/
  _count?: true | HallCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HallAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HallSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HallMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HallMaxAggregateInputType
}

export type GetHallAggregateType<T extends HallAggregateArgs> = {
      [P in keyof T & keyof AggregateHall]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHall[P]>
    : Prisma.GetScalarType<T[P], AggregateHall[P]>
}




export type hallGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.hallWhereInput
  orderBy?: Prisma.hallOrderByWithAggregationInput | Prisma.hallOrderByWithAggregationInput[]
  by: Prisma.HallScalarFieldEnum[] | Prisma.HallScalarFieldEnum
  having?: Prisma.hallScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HallCountAggregateInputType | true
  _avg?: HallAvgAggregateInputType
  _sum?: HallSumAggregateInputType
  _min?: HallMinAggregateInputType
  _max?: HallMaxAggregateInputType
}

export type HallGroupByOutputType = {
  ID_hall: number
  hall_type_of: boolean
  hall_address: string
  hall_additional_seats: number | null
  _count: HallCountAggregateOutputType | null
  _avg: HallAvgAggregateOutputType | null
  _sum: HallSumAggregateOutputType | null
  _min: HallMinAggregateOutputType | null
  _max: HallMaxAggregateOutputType | null
}

type GetHallGroupByPayload<T extends hallGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HallGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HallGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HallGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HallGroupByOutputType[P]>
      }
    >
  >



export type hallWhereInput = {
  AND?: Prisma.hallWhereInput | Prisma.hallWhereInput[]
  OR?: Prisma.hallWhereInput[]
  NOT?: Prisma.hallWhereInput | Prisma.hallWhereInput[]
  ID_hall?: Prisma.IntFilter<"hall"> | number
  hall_type_of?: Prisma.BoolFilter<"hall"> | boolean
  hall_address?: Prisma.StringFilter<"hall"> | string
  hall_additional_seats?: Prisma.IntNullableFilter<"hall"> | number | null
  seance?: Prisma.SeanceListRelationFilter
  seat?: Prisma.SeatListRelationFilter
}

export type hallOrderByWithRelationInput = {
  ID_hall?: Prisma.SortOrder
  hall_type_of?: Prisma.SortOrder
  hall_address?: Prisma.SortOrder
  hall_additional_seats?: Prisma.SortOrderInput | Prisma.SortOrder
  seance?: Prisma.seanceOrderByRelationAggregateInput
  seat?: Prisma.seatOrderByRelationAggregateInput
  _relevance?: Prisma.hallOrderByRelevanceInput
}

export type hallWhereUniqueInput = Prisma.AtLeast<{
  ID_hall?: number
  AND?: Prisma.hallWhereInput | Prisma.hallWhereInput[]
  OR?: Prisma.hallWhereInput[]
  NOT?: Prisma.hallWhereInput | Prisma.hallWhereInput[]
  hall_type_of?: Prisma.BoolFilter<"hall"> | boolean
  hall_address?: Prisma.StringFilter<"hall"> | string
  hall_additional_seats?: Prisma.IntNullableFilter<"hall"> | number | null
  seance?: Prisma.SeanceListRelationFilter
  seat?: Prisma.SeatListRelationFilter
}, "ID_hall">

export type hallOrderByWithAggregationInput = {
  ID_hall?: Prisma.SortOrder
  hall_type_of?: Prisma.SortOrder
  hall_address?: Prisma.SortOrder
  hall_additional_seats?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.hallCountOrderByAggregateInput
  _avg?: Prisma.hallAvgOrderByAggregateInput
  _max?: Prisma.hallMaxOrderByAggregateInput
  _min?: Prisma.hallMinOrderByAggregateInput
  _sum?: Prisma.hallSumOrderByAggregateInput
}

export type hallScalarWhereWithAggregatesInput = {
  AND?: Prisma.hallScalarWhereWithAggregatesInput | Prisma.hallScalarWhereWithAggregatesInput[]
  OR?: Prisma.hallScalarWhereWithAggregatesInput[]
  NOT?: Prisma.hallScalarWhereWithAggregatesInput | Prisma.hallScalarWhereWithAggregatesInput[]
  ID_hall?: Prisma.IntWithAggregatesFilter<"hall"> | number
  hall_type_of?: Prisma.BoolWithAggregatesFilter<"hall"> | boolean
  hall_address?: Prisma.StringWithAggregatesFilter<"hall"> | string
  hall_additional_seats?: Prisma.IntNullableWithAggregatesFilter<"hall"> | number | null
}

export type hallCreateInput = {
  ID_hall: number
  hall_type_of: boolean
  hall_address: string
  hall_additional_seats?: number | null
  seance?: Prisma.seanceCreateNestedManyWithoutHallInput
  seat?: Prisma.seatCreateNestedManyWithoutHallInput
}

export type hallUncheckedCreateInput = {
  ID_hall: number
  hall_type_of: boolean
  hall_address: string
  hall_additional_seats?: number | null
  seance?: Prisma.seanceUncheckedCreateNestedManyWithoutHallInput
  seat?: Prisma.seatUncheckedCreateNestedManyWithoutHallInput
}

export type hallUpdateInput = {
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  hall_type_of?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hall_address?: Prisma.StringFieldUpdateOperationsInput | string
  hall_additional_seats?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  seance?: Prisma.seanceUpdateManyWithoutHallNestedInput
  seat?: Prisma.seatUpdateManyWithoutHallNestedInput
}

export type hallUncheckedUpdateInput = {
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  hall_type_of?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hall_address?: Prisma.StringFieldUpdateOperationsInput | string
  hall_additional_seats?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  seance?: Prisma.seanceUncheckedUpdateManyWithoutHallNestedInput
  seat?: Prisma.seatUncheckedUpdateManyWithoutHallNestedInput
}

export type hallCreateManyInput = {
  ID_hall: number
  hall_type_of: boolean
  hall_address: string
  hall_additional_seats?: number | null
}

export type hallUpdateManyMutationInput = {
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  hall_type_of?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hall_address?: Prisma.StringFieldUpdateOperationsInput | string
  hall_additional_seats?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type hallUncheckedUpdateManyInput = {
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  hall_type_of?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hall_address?: Prisma.StringFieldUpdateOperationsInput | string
  hall_additional_seats?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type hallOrderByRelevanceInput = {
  fields: Prisma.hallOrderByRelevanceFieldEnum | Prisma.hallOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type hallCountOrderByAggregateInput = {
  ID_hall?: Prisma.SortOrder
  hall_type_of?: Prisma.SortOrder
  hall_address?: Prisma.SortOrder
  hall_additional_seats?: Prisma.SortOrder
}

export type hallAvgOrderByAggregateInput = {
  ID_hall?: Prisma.SortOrder
  hall_additional_seats?: Prisma.SortOrder
}

export type hallMaxOrderByAggregateInput = {
  ID_hall?: Prisma.SortOrder
  hall_type_of?: Prisma.SortOrder
  hall_address?: Prisma.SortOrder
  hall_additional_seats?: Prisma.SortOrder
}

export type hallMinOrderByAggregateInput = {
  ID_hall?: Prisma.SortOrder
  hall_type_of?: Prisma.SortOrder
  hall_address?: Prisma.SortOrder
  hall_additional_seats?: Prisma.SortOrder
}

export type hallSumOrderByAggregateInput = {
  ID_hall?: Prisma.SortOrder
  hall_additional_seats?: Prisma.SortOrder
}

export type HallScalarRelationFilter = {
  is?: Prisma.hallWhereInput
  isNot?: Prisma.hallWhereInput
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type hallCreateNestedOneWithoutSeanceInput = {
  create?: Prisma.XOR<Prisma.hallCreateWithoutSeanceInput, Prisma.hallUncheckedCreateWithoutSeanceInput>
  connectOrCreate?: Prisma.hallCreateOrConnectWithoutSeanceInput
  connect?: Prisma.hallWhereUniqueInput
}

export type hallUpdateOneRequiredWithoutSeanceNestedInput = {
  create?: Prisma.XOR<Prisma.hallCreateWithoutSeanceInput, Prisma.hallUncheckedCreateWithoutSeanceInput>
  connectOrCreate?: Prisma.hallCreateOrConnectWithoutSeanceInput
  upsert?: Prisma.hallUpsertWithoutSeanceInput
  connect?: Prisma.hallWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.hallUpdateToOneWithWhereWithoutSeanceInput, Prisma.hallUpdateWithoutSeanceInput>, Prisma.hallUncheckedUpdateWithoutSeanceInput>
}

export type hallCreateNestedOneWithoutSeatInput = {
  create?: Prisma.XOR<Prisma.hallCreateWithoutSeatInput, Prisma.hallUncheckedCreateWithoutSeatInput>
  connectOrCreate?: Prisma.hallCreateOrConnectWithoutSeatInput
  connect?: Prisma.hallWhereUniqueInput
}

export type hallUpdateOneRequiredWithoutSeatNestedInput = {
  create?: Prisma.XOR<Prisma.hallCreateWithoutSeatInput, Prisma.hallUncheckedCreateWithoutSeatInput>
  connectOrCreate?: Prisma.hallCreateOrConnectWithoutSeatInput
  upsert?: Prisma.hallUpsertWithoutSeatInput
  connect?: Prisma.hallWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.hallUpdateToOneWithWhereWithoutSeatInput, Prisma.hallUpdateWithoutSeatInput>, Prisma.hallUncheckedUpdateWithoutSeatInput>
}

export type hallCreateWithoutSeanceInput = {
  ID_hall: number
  hall_type_of: boolean
  hall_address: string
  hall_additional_seats?: number | null
  seat?: Prisma.seatCreateNestedManyWithoutHallInput
}

export type hallUncheckedCreateWithoutSeanceInput = {
  ID_hall: number
  hall_type_of: boolean
  hall_address: string
  hall_additional_seats?: number | null
  seat?: Prisma.seatUncheckedCreateNestedManyWithoutHallInput
}

export type hallCreateOrConnectWithoutSeanceInput = {
  where: Prisma.hallWhereUniqueInput
  create: Prisma.XOR<Prisma.hallCreateWithoutSeanceInput, Prisma.hallUncheckedCreateWithoutSeanceInput>
}

export type hallUpsertWithoutSeanceInput = {
  update: Prisma.XOR<Prisma.hallUpdateWithoutSeanceInput, Prisma.hallUncheckedUpdateWithoutSeanceInput>
  create: Prisma.XOR<Prisma.hallCreateWithoutSeanceInput, Prisma.hallUncheckedCreateWithoutSeanceInput>
  where?: Prisma.hallWhereInput
}

export type hallUpdateToOneWithWhereWithoutSeanceInput = {
  where?: Prisma.hallWhereInput
  data: Prisma.XOR<Prisma.hallUpdateWithoutSeanceInput, Prisma.hallUncheckedUpdateWithoutSeanceInput>
}

export type hallUpdateWithoutSeanceInput = {
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  hall_type_of?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hall_address?: Prisma.StringFieldUpdateOperationsInput | string
  hall_additional_seats?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  seat?: Prisma.seatUpdateManyWithoutHallNestedInput
}

export type hallUncheckedUpdateWithoutSeanceInput = {
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  hall_type_of?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hall_address?: Prisma.StringFieldUpdateOperationsInput | string
  hall_additional_seats?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  seat?: Prisma.seatUncheckedUpdateManyWithoutHallNestedInput
}

export type hallCreateWithoutSeatInput = {
  ID_hall: number
  hall_type_of: boolean
  hall_address: string
  hall_additional_seats?: number | null
  seance?: Prisma.seanceCreateNestedManyWithoutHallInput
}

export type hallUncheckedCreateWithoutSeatInput = {
  ID_hall: number
  hall_type_of: boolean
  hall_address: string
  hall_additional_seats?: number | null
  seance?: Prisma.seanceUncheckedCreateNestedManyWithoutHallInput
}

export type hallCreateOrConnectWithoutSeatInput = {
  where: Prisma.hallWhereUniqueInput
  create: Prisma.XOR<Prisma.hallCreateWithoutSeatInput, Prisma.hallUncheckedCreateWithoutSeatInput>
}

export type hallUpsertWithoutSeatInput = {
  update: Prisma.XOR<Prisma.hallUpdateWithoutSeatInput, Prisma.hallUncheckedUpdateWithoutSeatInput>
  create: Prisma.XOR<Prisma.hallCreateWithoutSeatInput, Prisma.hallUncheckedCreateWithoutSeatInput>
  where?: Prisma.hallWhereInput
}

export type hallUpdateToOneWithWhereWithoutSeatInput = {
  where?: Prisma.hallWhereInput
  data: Prisma.XOR<Prisma.hallUpdateWithoutSeatInput, Prisma.hallUncheckedUpdateWithoutSeatInput>
}

export type hallUpdateWithoutSeatInput = {
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  hall_type_of?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hall_address?: Prisma.StringFieldUpdateOperationsInput | string
  hall_additional_seats?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  seance?: Prisma.seanceUpdateManyWithoutHallNestedInput
}

export type hallUncheckedUpdateWithoutSeatInput = {
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  hall_type_of?: Prisma.BoolFieldUpdateOperationsInput | boolean
  hall_address?: Prisma.StringFieldUpdateOperationsInput | string
  hall_additional_seats?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  seance?: Prisma.seanceUncheckedUpdateManyWithoutHallNestedInput
}


/**
 * Count Type HallCountOutputType
 */

export type HallCountOutputType = {
  seance: number
  seat: number
}

export type HallCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  seance?: boolean | HallCountOutputTypeCountSeanceArgs
  seat?: boolean | HallCountOutputTypeCountSeatArgs
}

/**
 * HallCountOutputType without action
 */
export type HallCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HallCountOutputType
   */
  select?: Prisma.HallCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HallCountOutputType without action
 */
export type HallCountOutputTypeCountSeanceArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.seanceWhereInput
}

/**
 * HallCountOutputType without action
 */
export type HallCountOutputTypeCountSeatArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.seatWhereInput
}


export type hallSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  ID_hall?: boolean
  hall_type_of?: boolean
  hall_address?: boolean
  hall_additional_seats?: boolean
  seance?: boolean | Prisma.hall$seanceArgs<ExtArgs>
  seat?: boolean | Prisma.hall$seatArgs<ExtArgs>
  _count?: boolean | Prisma.HallCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hall"]>



export type hallSelectScalar = {
  ID_hall?: boolean
  hall_type_of?: boolean
  hall_address?: boolean
  hall_additional_seats?: boolean
}

export type hallOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"ID_hall" | "hall_type_of" | "hall_address" | "hall_additional_seats", ExtArgs["result"]["hall"]>
export type hallInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  seance?: boolean | Prisma.hall$seanceArgs<ExtArgs>
  seat?: boolean | Prisma.hall$seatArgs<ExtArgs>
  _count?: boolean | Prisma.HallCountOutputTypeDefaultArgs<ExtArgs>
}

export type $hallPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "hall"
  objects: {
    seance: Prisma.$seancePayload<ExtArgs>[]
    seat: Prisma.$seatPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    ID_hall: number
    hall_type_of: boolean
    hall_address: string
    hall_additional_seats: number | null
  }, ExtArgs["result"]["hall"]>
  composites: {}
}

export type hallGetPayload<S extends boolean | null | undefined | hallDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$hallPayload, S>

export type hallCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<hallFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HallCountAggregateInputType | true
  }

export interface hallDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['hall'], meta: { name: 'hall' } }
  /**
   * Find zero or one Hall that matches the filter.
   * @param {hallFindUniqueArgs} args - Arguments to find a Hall
   * @example
   * // Get one Hall
   * const hall = await prisma.hall.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends hallFindUniqueArgs>(args: Prisma.SelectSubset<T, hallFindUniqueArgs<ExtArgs>>): Prisma.Prisma__hallClient<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Hall that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {hallFindUniqueOrThrowArgs} args - Arguments to find a Hall
   * @example
   * // Get one Hall
   * const hall = await prisma.hall.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends hallFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, hallFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__hallClient<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hall that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hallFindFirstArgs} args - Arguments to find a Hall
   * @example
   * // Get one Hall
   * const hall = await prisma.hall.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends hallFindFirstArgs>(args?: Prisma.SelectSubset<T, hallFindFirstArgs<ExtArgs>>): Prisma.Prisma__hallClient<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hall that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hallFindFirstOrThrowArgs} args - Arguments to find a Hall
   * @example
   * // Get one Hall
   * const hall = await prisma.hall.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends hallFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, hallFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__hallClient<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Halls that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hallFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Halls
   * const halls = await prisma.hall.findMany()
   * 
   * // Get first 10 Halls
   * const halls = await prisma.hall.findMany({ take: 10 })
   * 
   * // Only select the `ID_hall`
   * const hallWithID_hallOnly = await prisma.hall.findMany({ select: { ID_hall: true } })
   * 
   */
  findMany<T extends hallFindManyArgs>(args?: Prisma.SelectSubset<T, hallFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Hall.
   * @param {hallCreateArgs} args - Arguments to create a Hall.
   * @example
   * // Create one Hall
   * const Hall = await prisma.hall.create({
   *   data: {
   *     // ... data to create a Hall
   *   }
   * })
   * 
   */
  create<T extends hallCreateArgs>(args: Prisma.SelectSubset<T, hallCreateArgs<ExtArgs>>): Prisma.Prisma__hallClient<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Halls.
   * @param {hallCreateManyArgs} args - Arguments to create many Halls.
   * @example
   * // Create many Halls
   * const hall = await prisma.hall.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends hallCreateManyArgs>(args?: Prisma.SelectSubset<T, hallCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Hall.
   * @param {hallDeleteArgs} args - Arguments to delete one Hall.
   * @example
   * // Delete one Hall
   * const Hall = await prisma.hall.delete({
   *   where: {
   *     // ... filter to delete one Hall
   *   }
   * })
   * 
   */
  delete<T extends hallDeleteArgs>(args: Prisma.SelectSubset<T, hallDeleteArgs<ExtArgs>>): Prisma.Prisma__hallClient<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Hall.
   * @param {hallUpdateArgs} args - Arguments to update one Hall.
   * @example
   * // Update one Hall
   * const hall = await prisma.hall.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends hallUpdateArgs>(args: Prisma.SelectSubset<T, hallUpdateArgs<ExtArgs>>): Prisma.Prisma__hallClient<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Halls.
   * @param {hallDeleteManyArgs} args - Arguments to filter Halls to delete.
   * @example
   * // Delete a few Halls
   * const { count } = await prisma.hall.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends hallDeleteManyArgs>(args?: Prisma.SelectSubset<T, hallDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Halls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hallUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Halls
   * const hall = await prisma.hall.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends hallUpdateManyArgs>(args: Prisma.SelectSubset<T, hallUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Hall.
   * @param {hallUpsertArgs} args - Arguments to update or create a Hall.
   * @example
   * // Update or create a Hall
   * const hall = await prisma.hall.upsert({
   *   create: {
   *     // ... data to create a Hall
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Hall we want to update
   *   }
   * })
   */
  upsert<T extends hallUpsertArgs>(args: Prisma.SelectSubset<T, hallUpsertArgs<ExtArgs>>): Prisma.Prisma__hallClient<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Halls.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hallCountArgs} args - Arguments to filter Halls to count.
   * @example
   * // Count the number of Halls
   * const count = await prisma.hall.count({
   *   where: {
   *     // ... the filter for the Halls we want to count
   *   }
   * })
  **/
  count<T extends hallCountArgs>(
    args?: Prisma.Subset<T, hallCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HallCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Hall.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HallAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HallAggregateArgs>(args: Prisma.Subset<T, HallAggregateArgs>): Prisma.PrismaPromise<GetHallAggregateType<T>>

  /**
   * Group by Hall.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {hallGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends hallGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: hallGroupByArgs['orderBy'] }
      : { orderBy?: hallGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, hallGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHallGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the hall model
 */
readonly fields: hallFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for hall.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__hallClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  seance<T extends Prisma.hall$seanceArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.hall$seanceArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  seat<T extends Prisma.hall$seatArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.hall$seatArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$seatPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the hall model
 */
export interface hallFieldRefs {
  readonly ID_hall: Prisma.FieldRef<"hall", 'Int'>
  readonly hall_type_of: Prisma.FieldRef<"hall", 'Boolean'>
  readonly hall_address: Prisma.FieldRef<"hall", 'String'>
  readonly hall_additional_seats: Prisma.FieldRef<"hall", 'Int'>
}
    

// Custom InputTypes
/**
 * hall findUnique
 */
export type hallFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
  /**
   * Filter, which hall to fetch.
   */
  where: Prisma.hallWhereUniqueInput
}

/**
 * hall findUniqueOrThrow
 */
export type hallFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
  /**
   * Filter, which hall to fetch.
   */
  where: Prisma.hallWhereUniqueInput
}

/**
 * hall findFirst
 */
export type hallFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
  /**
   * Filter, which hall to fetch.
   */
  where?: Prisma.hallWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of halls to fetch.
   */
  orderBy?: Prisma.hallOrderByWithRelationInput | Prisma.hallOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for halls.
   */
  cursor?: Prisma.hallWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` halls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` halls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of halls.
   */
  distinct?: Prisma.HallScalarFieldEnum | Prisma.HallScalarFieldEnum[]
}

/**
 * hall findFirstOrThrow
 */
export type hallFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
  /**
   * Filter, which hall to fetch.
   */
  where?: Prisma.hallWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of halls to fetch.
   */
  orderBy?: Prisma.hallOrderByWithRelationInput | Prisma.hallOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for halls.
   */
  cursor?: Prisma.hallWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` halls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` halls.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of halls.
   */
  distinct?: Prisma.HallScalarFieldEnum | Prisma.HallScalarFieldEnum[]
}

/**
 * hall findMany
 */
export type hallFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
  /**
   * Filter, which halls to fetch.
   */
  where?: Prisma.hallWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of halls to fetch.
   */
  orderBy?: Prisma.hallOrderByWithRelationInput | Prisma.hallOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing halls.
   */
  cursor?: Prisma.hallWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` halls from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` halls.
   */
  skip?: number
  distinct?: Prisma.HallScalarFieldEnum | Prisma.HallScalarFieldEnum[]
}

/**
 * hall create
 */
export type hallCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
  /**
   * The data needed to create a hall.
   */
  data: Prisma.XOR<Prisma.hallCreateInput, Prisma.hallUncheckedCreateInput>
}

/**
 * hall createMany
 */
export type hallCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many halls.
   */
  data: Prisma.hallCreateManyInput | Prisma.hallCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * hall update
 */
export type hallUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
  /**
   * The data needed to update a hall.
   */
  data: Prisma.XOR<Prisma.hallUpdateInput, Prisma.hallUncheckedUpdateInput>
  /**
   * Choose, which hall to update.
   */
  where: Prisma.hallWhereUniqueInput
}

/**
 * hall updateMany
 */
export type hallUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update halls.
   */
  data: Prisma.XOR<Prisma.hallUpdateManyMutationInput, Prisma.hallUncheckedUpdateManyInput>
  /**
   * Filter which halls to update
   */
  where?: Prisma.hallWhereInput
  /**
   * Limit how many halls to update.
   */
  limit?: number
}

/**
 * hall upsert
 */
export type hallUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
  /**
   * The filter to search for the hall to update in case it exists.
   */
  where: Prisma.hallWhereUniqueInput
  /**
   * In case the hall found by the `where` argument doesn't exist, create a new hall with this data.
   */
  create: Prisma.XOR<Prisma.hallCreateInput, Prisma.hallUncheckedCreateInput>
  /**
   * In case the hall was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.hallUpdateInput, Prisma.hallUncheckedUpdateInput>
}

/**
 * hall delete
 */
export type hallDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
  /**
   * Filter which hall to delete.
   */
  where: Prisma.hallWhereUniqueInput
}

/**
 * hall deleteMany
 */
export type hallDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which halls to delete
   */
  where?: Prisma.hallWhereInput
  /**
   * Limit how many halls to delete.
   */
  limit?: number
}

/**
 * hall.seance
 */
export type hall$seanceArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  where?: Prisma.seanceWhereInput
  orderBy?: Prisma.seanceOrderByWithRelationInput | Prisma.seanceOrderByWithRelationInput[]
  cursor?: Prisma.seanceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SeanceScalarFieldEnum | Prisma.SeanceScalarFieldEnum[]
}

/**
 * hall.seat
 */
export type hall$seatArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seat
   */
  select?: Prisma.seatSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seat
   */
  omit?: Prisma.seatOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seatInclude<ExtArgs> | null
  where?: Prisma.seatWhereInput
  orderBy?: Prisma.seatOrderByWithRelationInput | Prisma.seatOrderByWithRelationInput[]
  cursor?: Prisma.seatWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SeatScalarFieldEnum | Prisma.SeatScalarFieldEnum[]
}

/**
 * hall without action
 */
export type hallDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hall
   */
  select?: Prisma.hallSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hall
   */
  omit?: Prisma.hallOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.hallInclude<ExtArgs> | null
}
