
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `hero` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model hero
 * 
 */
export type heroModel = runtime.Types.Result.DefaultSelection<Prisma.$heroPayload>

export type AggregateHero = {
  _count: HeroCountAggregateOutputType | null
  _avg: HeroAvgAggregateOutputType | null
  _sum: HeroSumAggregateOutputType | null
  _min: HeroMinAggregateOutputType | null
  _max: HeroMaxAggregateOutputType | null
}

export type HeroAvgAggregateOutputType = {
  ID_hero: number | null
  ID_performance: number | null
}

export type HeroSumAggregateOutputType = {
  ID_hero: number | null
  ID_performance: number | null
}

export type HeroMinAggregateOutputType = {
  ID_hero: number | null
  ID_performance: number | null
  hero_description: string | null
  hero_name: string | null
}

export type HeroMaxAggregateOutputType = {
  ID_hero: number | null
  ID_performance: number | null
  hero_description: string | null
  hero_name: string | null
}

export type HeroCountAggregateOutputType = {
  ID_hero: number
  ID_performance: number
  hero_description: number
  hero_name: number
  _all: number
}


export type HeroAvgAggregateInputType = {
  ID_hero?: true
  ID_performance?: true
}

export type HeroSumAggregateInputType = {
  ID_hero?: true
  ID_performance?: true
}

export type HeroMinAggregateInputType = {
  ID_hero?: true
  ID_performance?: true
  hero_description?: true
  hero_name?: true
}

export type HeroMaxAggregateInputType = {
  ID_hero?: true
  ID_performance?: true
  hero_description?: true
  hero_name?: true
}

export type HeroCountAggregateInputType = {
  ID_hero?: true
  ID_performance?: true
  hero_description?: true
  hero_name?: true
  _all?: true
}

export type HeroAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which hero to aggregate.
   */
  where?: Prisma.heroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of heroes to fetch.
   */
  orderBy?: Prisma.heroOrderByWithRelationInput | Prisma.heroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.heroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` heroes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned heroes
  **/
  _count?: true | HeroCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HeroAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HeroSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HeroMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HeroMaxAggregateInputType
}

export type GetHeroAggregateType<T extends HeroAggregateArgs> = {
      [P in keyof T & keyof AggregateHero]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHero[P]>
    : Prisma.GetScalarType<T[P], AggregateHero[P]>
}




export type heroGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.heroWhereInput
  orderBy?: Prisma.heroOrderByWithAggregationInput | Prisma.heroOrderByWithAggregationInput[]
  by: Prisma.HeroScalarFieldEnum[] | Prisma.HeroScalarFieldEnum
  having?: Prisma.heroScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HeroCountAggregateInputType | true
  _avg?: HeroAvgAggregateInputType
  _sum?: HeroSumAggregateInputType
  _min?: HeroMinAggregateInputType
  _max?: HeroMaxAggregateInputType
}

export type HeroGroupByOutputType = {
  ID_hero: number
  ID_performance: number
  hero_description: string | null
  hero_name: string
  _count: HeroCountAggregateOutputType | null
  _avg: HeroAvgAggregateOutputType | null
  _sum: HeroSumAggregateOutputType | null
  _min: HeroMinAggregateOutputType | null
  _max: HeroMaxAggregateOutputType | null
}

type GetHeroGroupByPayload<T extends heroGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HeroGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HeroGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HeroGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HeroGroupByOutputType[P]>
      }
    >
  >



export type heroWhereInput = {
  AND?: Prisma.heroWhereInput | Prisma.heroWhereInput[]
  OR?: Prisma.heroWhereInput[]
  NOT?: Prisma.heroWhereInput | Prisma.heroWhereInput[]
  ID_hero?: Prisma.IntFilter<"hero"> | number
  ID_performance?: Prisma.IntFilter<"hero"> | number
  hero_description?: Prisma.StringNullableFilter<"hero"> | string | null
  hero_name?: Prisma.StringFilter<"hero"> | string
  actors_hero?: Prisma.Actors_heroListRelationFilter
  performance?: Prisma.XOR<Prisma.PerformanceScalarRelationFilter, Prisma.performanceWhereInput>
}

export type heroOrderByWithRelationInput = {
  ID_hero?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  hero_description?: Prisma.SortOrderInput | Prisma.SortOrder
  hero_name?: Prisma.SortOrder
  actors_hero?: Prisma.actors_heroOrderByRelationAggregateInput
  performance?: Prisma.performanceOrderByWithRelationInput
  _relevance?: Prisma.heroOrderByRelevanceInput
}

export type heroWhereUniqueInput = Prisma.AtLeast<{
  ID_hero?: number
  AND?: Prisma.heroWhereInput | Prisma.heroWhereInput[]
  OR?: Prisma.heroWhereInput[]
  NOT?: Prisma.heroWhereInput | Prisma.heroWhereInput[]
  ID_performance?: Prisma.IntFilter<"hero"> | number
  hero_description?: Prisma.StringNullableFilter<"hero"> | string | null
  hero_name?: Prisma.StringFilter<"hero"> | string
  actors_hero?: Prisma.Actors_heroListRelationFilter
  performance?: Prisma.XOR<Prisma.PerformanceScalarRelationFilter, Prisma.performanceWhereInput>
}, "ID_hero">

export type heroOrderByWithAggregationInput = {
  ID_hero?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  hero_description?: Prisma.SortOrderInput | Prisma.SortOrder
  hero_name?: Prisma.SortOrder
  _count?: Prisma.heroCountOrderByAggregateInput
  _avg?: Prisma.heroAvgOrderByAggregateInput
  _max?: Prisma.heroMaxOrderByAggregateInput
  _min?: Prisma.heroMinOrderByAggregateInput
  _sum?: Prisma.heroSumOrderByAggregateInput
}

export type heroScalarWhereWithAggregatesInput = {
  AND?: Prisma.heroScalarWhereWithAggregatesInput | Prisma.heroScalarWhereWithAggregatesInput[]
  OR?: Prisma.heroScalarWhereWithAggregatesInput[]
  NOT?: Prisma.heroScalarWhereWithAggregatesInput | Prisma.heroScalarWhereWithAggregatesInput[]
  ID_hero?: Prisma.IntWithAggregatesFilter<"hero"> | number
  ID_performance?: Prisma.IntWithAggregatesFilter<"hero"> | number
  hero_description?: Prisma.StringNullableWithAggregatesFilter<"hero"> | string | null
  hero_name?: Prisma.StringWithAggregatesFilter<"hero"> | string
}

export type heroCreateInput = {
  ID_hero: number
  hero_description?: string | null
  hero_name: string
  actors_hero?: Prisma.actors_heroCreateNestedManyWithoutHeroInput
  performance: Prisma.performanceCreateNestedOneWithoutHeroInput
}

export type heroUncheckedCreateInput = {
  ID_hero: number
  ID_performance: number
  hero_description?: string | null
  hero_name: string
  actors_hero?: Prisma.actors_heroUncheckedCreateNestedManyWithoutHeroInput
}

export type heroUpdateInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  hero_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hero_name?: Prisma.StringFieldUpdateOperationsInput | string
  actors_hero?: Prisma.actors_heroUpdateManyWithoutHeroNestedInput
  performance?: Prisma.performanceUpdateOneRequiredWithoutHeroNestedInput
}

export type heroUncheckedUpdateInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  ID_performance?: Prisma.IntFieldUpdateOperationsInput | number
  hero_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hero_name?: Prisma.StringFieldUpdateOperationsInput | string
  actors_hero?: Prisma.actors_heroUncheckedUpdateManyWithoutHeroNestedInput
}

export type heroCreateManyInput = {
  ID_hero: number
  ID_performance: number
  hero_description?: string | null
  hero_name: string
}

export type heroUpdateManyMutationInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  hero_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hero_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type heroUncheckedUpdateManyInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  ID_performance?: Prisma.IntFieldUpdateOperationsInput | number
  hero_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hero_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HeroScalarRelationFilter = {
  is?: Prisma.heroWhereInput
  isNot?: Prisma.heroWhereInput
}

export type heroOrderByRelevanceInput = {
  fields: Prisma.heroOrderByRelevanceFieldEnum | Prisma.heroOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type heroCountOrderByAggregateInput = {
  ID_hero?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  hero_description?: Prisma.SortOrder
  hero_name?: Prisma.SortOrder
}

export type heroAvgOrderByAggregateInput = {
  ID_hero?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
}

export type heroMaxOrderByAggregateInput = {
  ID_hero?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  hero_description?: Prisma.SortOrder
  hero_name?: Prisma.SortOrder
}

export type heroMinOrderByAggregateInput = {
  ID_hero?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  hero_description?: Prisma.SortOrder
  hero_name?: Prisma.SortOrder
}

export type heroSumOrderByAggregateInput = {
  ID_hero?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
}

export type HeroListRelationFilter = {
  every?: Prisma.heroWhereInput
  some?: Prisma.heroWhereInput
  none?: Prisma.heroWhereInput
}

export type heroOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type heroCreateNestedOneWithoutActors_heroInput = {
  create?: Prisma.XOR<Prisma.heroCreateWithoutActors_heroInput, Prisma.heroUncheckedCreateWithoutActors_heroInput>
  connectOrCreate?: Prisma.heroCreateOrConnectWithoutActors_heroInput
  connect?: Prisma.heroWhereUniqueInput
}

export type heroUpdateOneRequiredWithoutActors_heroNestedInput = {
  create?: Prisma.XOR<Prisma.heroCreateWithoutActors_heroInput, Prisma.heroUncheckedCreateWithoutActors_heroInput>
  connectOrCreate?: Prisma.heroCreateOrConnectWithoutActors_heroInput
  upsert?: Prisma.heroUpsertWithoutActors_heroInput
  connect?: Prisma.heroWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.heroUpdateToOneWithWhereWithoutActors_heroInput, Prisma.heroUpdateWithoutActors_heroInput>, Prisma.heroUncheckedUpdateWithoutActors_heroInput>
}

export type heroCreateNestedManyWithoutPerformanceInput = {
  create?: Prisma.XOR<Prisma.heroCreateWithoutPerformanceInput, Prisma.heroUncheckedCreateWithoutPerformanceInput> | Prisma.heroCreateWithoutPerformanceInput[] | Prisma.heroUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.heroCreateOrConnectWithoutPerformanceInput | Prisma.heroCreateOrConnectWithoutPerformanceInput[]
  createMany?: Prisma.heroCreateManyPerformanceInputEnvelope
  connect?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
}

export type heroUncheckedCreateNestedManyWithoutPerformanceInput = {
  create?: Prisma.XOR<Prisma.heroCreateWithoutPerformanceInput, Prisma.heroUncheckedCreateWithoutPerformanceInput> | Prisma.heroCreateWithoutPerformanceInput[] | Prisma.heroUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.heroCreateOrConnectWithoutPerformanceInput | Prisma.heroCreateOrConnectWithoutPerformanceInput[]
  createMany?: Prisma.heroCreateManyPerformanceInputEnvelope
  connect?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
}

export type heroUpdateManyWithoutPerformanceNestedInput = {
  create?: Prisma.XOR<Prisma.heroCreateWithoutPerformanceInput, Prisma.heroUncheckedCreateWithoutPerformanceInput> | Prisma.heroCreateWithoutPerformanceInput[] | Prisma.heroUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.heroCreateOrConnectWithoutPerformanceInput | Prisma.heroCreateOrConnectWithoutPerformanceInput[]
  upsert?: Prisma.heroUpsertWithWhereUniqueWithoutPerformanceInput | Prisma.heroUpsertWithWhereUniqueWithoutPerformanceInput[]
  createMany?: Prisma.heroCreateManyPerformanceInputEnvelope
  set?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
  disconnect?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
  delete?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
  connect?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
  update?: Prisma.heroUpdateWithWhereUniqueWithoutPerformanceInput | Prisma.heroUpdateWithWhereUniqueWithoutPerformanceInput[]
  updateMany?: Prisma.heroUpdateManyWithWhereWithoutPerformanceInput | Prisma.heroUpdateManyWithWhereWithoutPerformanceInput[]
  deleteMany?: Prisma.heroScalarWhereInput | Prisma.heroScalarWhereInput[]
}

export type heroUncheckedUpdateManyWithoutPerformanceNestedInput = {
  create?: Prisma.XOR<Prisma.heroCreateWithoutPerformanceInput, Prisma.heroUncheckedCreateWithoutPerformanceInput> | Prisma.heroCreateWithoutPerformanceInput[] | Prisma.heroUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.heroCreateOrConnectWithoutPerformanceInput | Prisma.heroCreateOrConnectWithoutPerformanceInput[]
  upsert?: Prisma.heroUpsertWithWhereUniqueWithoutPerformanceInput | Prisma.heroUpsertWithWhereUniqueWithoutPerformanceInput[]
  createMany?: Prisma.heroCreateManyPerformanceInputEnvelope
  set?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
  disconnect?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
  delete?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
  connect?: Prisma.heroWhereUniqueInput | Prisma.heroWhereUniqueInput[]
  update?: Prisma.heroUpdateWithWhereUniqueWithoutPerformanceInput | Prisma.heroUpdateWithWhereUniqueWithoutPerformanceInput[]
  updateMany?: Prisma.heroUpdateManyWithWhereWithoutPerformanceInput | Prisma.heroUpdateManyWithWhereWithoutPerformanceInput[]
  deleteMany?: Prisma.heroScalarWhereInput | Prisma.heroScalarWhereInput[]
}

export type heroCreateWithoutActors_heroInput = {
  ID_hero: number
  hero_description?: string | null
  hero_name: string
  performance: Prisma.performanceCreateNestedOneWithoutHeroInput
}

export type heroUncheckedCreateWithoutActors_heroInput = {
  ID_hero: number
  ID_performance: number
  hero_description?: string | null
  hero_name: string
}

export type heroCreateOrConnectWithoutActors_heroInput = {
  where: Prisma.heroWhereUniqueInput
  create: Prisma.XOR<Prisma.heroCreateWithoutActors_heroInput, Prisma.heroUncheckedCreateWithoutActors_heroInput>
}

export type heroUpsertWithoutActors_heroInput = {
  update: Prisma.XOR<Prisma.heroUpdateWithoutActors_heroInput, Prisma.heroUncheckedUpdateWithoutActors_heroInput>
  create: Prisma.XOR<Prisma.heroCreateWithoutActors_heroInput, Prisma.heroUncheckedCreateWithoutActors_heroInput>
  where?: Prisma.heroWhereInput
}

export type heroUpdateToOneWithWhereWithoutActors_heroInput = {
  where?: Prisma.heroWhereInput
  data: Prisma.XOR<Prisma.heroUpdateWithoutActors_heroInput, Prisma.heroUncheckedUpdateWithoutActors_heroInput>
}

export type heroUpdateWithoutActors_heroInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  hero_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hero_name?: Prisma.StringFieldUpdateOperationsInput | string
  performance?: Prisma.performanceUpdateOneRequiredWithoutHeroNestedInput
}

export type heroUncheckedUpdateWithoutActors_heroInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  ID_performance?: Prisma.IntFieldUpdateOperationsInput | number
  hero_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hero_name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type heroCreateWithoutPerformanceInput = {
  ID_hero: number
  hero_description?: string | null
  hero_name: string
  actors_hero?: Prisma.actors_heroCreateNestedManyWithoutHeroInput
}

export type heroUncheckedCreateWithoutPerformanceInput = {
  ID_hero: number
  hero_description?: string | null
  hero_name: string
  actors_hero?: Prisma.actors_heroUncheckedCreateNestedManyWithoutHeroInput
}

export type heroCreateOrConnectWithoutPerformanceInput = {
  where: Prisma.heroWhereUniqueInput
  create: Prisma.XOR<Prisma.heroCreateWithoutPerformanceInput, Prisma.heroUncheckedCreateWithoutPerformanceInput>
}

export type heroCreateManyPerformanceInputEnvelope = {
  data: Prisma.heroCreateManyPerformanceInput | Prisma.heroCreateManyPerformanceInput[]
  skipDuplicates?: boolean
}

export type heroUpsertWithWhereUniqueWithoutPerformanceInput = {
  where: Prisma.heroWhereUniqueInput
  update: Prisma.XOR<Prisma.heroUpdateWithoutPerformanceInput, Prisma.heroUncheckedUpdateWithoutPerformanceInput>
  create: Prisma.XOR<Prisma.heroCreateWithoutPerformanceInput, Prisma.heroUncheckedCreateWithoutPerformanceInput>
}

export type heroUpdateWithWhereUniqueWithoutPerformanceInput = {
  where: Prisma.heroWhereUniqueInput
  data: Prisma.XOR<Prisma.heroUpdateWithoutPerformanceInput, Prisma.heroUncheckedUpdateWithoutPerformanceInput>
}

export type heroUpdateManyWithWhereWithoutPerformanceInput = {
  where: Prisma.heroScalarWhereInput
  data: Prisma.XOR<Prisma.heroUpdateManyMutationInput, Prisma.heroUncheckedUpdateManyWithoutPerformanceInput>
}

export type heroScalarWhereInput = {
  AND?: Prisma.heroScalarWhereInput | Prisma.heroScalarWhereInput[]
  OR?: Prisma.heroScalarWhereInput[]
  NOT?: Prisma.heroScalarWhereInput | Prisma.heroScalarWhereInput[]
  ID_hero?: Prisma.IntFilter<"hero"> | number
  ID_performance?: Prisma.IntFilter<"hero"> | number
  hero_description?: Prisma.StringNullableFilter<"hero"> | string | null
  hero_name?: Prisma.StringFilter<"hero"> | string
}

export type heroCreateManyPerformanceInput = {
  ID_hero: number
  hero_description?: string | null
  hero_name: string
}

export type heroUpdateWithoutPerformanceInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  hero_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hero_name?: Prisma.StringFieldUpdateOperationsInput | string
  actors_hero?: Prisma.actors_heroUpdateManyWithoutHeroNestedInput
}

export type heroUncheckedUpdateWithoutPerformanceInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  hero_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hero_name?: Prisma.StringFieldUpdateOperationsInput | string
  actors_hero?: Prisma.actors_heroUncheckedUpdateManyWithoutHeroNestedInput
}

export type heroUncheckedUpdateManyWithoutPerformanceInput = {
  ID_hero?: Prisma.IntFieldUpdateOperationsInput | number
  hero_description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  hero_name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type HeroCountOutputType
 */

export type HeroCountOutputType = {
  actors_hero: number
}

export type HeroCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actors_hero?: boolean | HeroCountOutputTypeCountActors_heroArgs
}

/**
 * HeroCountOutputType without action
 */
export type HeroCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeroCountOutputType
   */
  select?: Prisma.HeroCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HeroCountOutputType without action
 */
export type HeroCountOutputTypeCountActors_heroArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.actors_heroWhereInput
}


export type heroSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  ID_hero?: boolean
  ID_performance?: boolean
  hero_description?: boolean
  hero_name?: boolean
  actors_hero?: boolean | Prisma.hero$actors_heroArgs<ExtArgs>
  performance?: boolean | Prisma.performanceDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.HeroCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["hero"]>



export type heroSelectScalar = {
  ID_hero?: boolean
  ID_performance?: boolean
  hero_description?: boolean
  hero_name?: boolean
}

export type heroOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"ID_hero" | "ID_performance" | "hero_description" | "hero_name", ExtArgs["result"]["hero"]>
export type heroInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  actors_hero?: boolean | Prisma.hero$actors_heroArgs<ExtArgs>
  performance?: boolean | Prisma.performanceDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.HeroCountOutputTypeDefaultArgs<ExtArgs>
}

export type $heroPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "hero"
  objects: {
    actors_hero: Prisma.$actors_heroPayload<ExtArgs>[]
    performance: Prisma.$performancePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    ID_hero: number
    ID_performance: number
    hero_description: string | null
    hero_name: string
  }, ExtArgs["result"]["hero"]>
  composites: {}
}

export type heroGetPayload<S extends boolean | null | undefined | heroDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$heroPayload, S>

export type heroCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<heroFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HeroCountAggregateInputType | true
  }

export interface heroDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['hero'], meta: { name: 'hero' } }
  /**
   * Find zero or one Hero that matches the filter.
   * @param {heroFindUniqueArgs} args - Arguments to find a Hero
   * @example
   * // Get one Hero
   * const hero = await prisma.hero.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends heroFindUniqueArgs>(args: Prisma.SelectSubset<T, heroFindUniqueArgs<ExtArgs>>): Prisma.Prisma__heroClient<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Hero that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {heroFindUniqueOrThrowArgs} args - Arguments to find a Hero
   * @example
   * // Get one Hero
   * const hero = await prisma.hero.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends heroFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, heroFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__heroClient<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hero that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {heroFindFirstArgs} args - Arguments to find a Hero
   * @example
   * // Get one Hero
   * const hero = await prisma.hero.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends heroFindFirstArgs>(args?: Prisma.SelectSubset<T, heroFindFirstArgs<ExtArgs>>): Prisma.Prisma__heroClient<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Hero that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {heroFindFirstOrThrowArgs} args - Arguments to find a Hero
   * @example
   * // Get one Hero
   * const hero = await prisma.hero.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends heroFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, heroFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__heroClient<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Heroes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {heroFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Heroes
   * const heroes = await prisma.hero.findMany()
   * 
   * // Get first 10 Heroes
   * const heroes = await prisma.hero.findMany({ take: 10 })
   * 
   * // Only select the `ID_hero`
   * const heroWithID_heroOnly = await prisma.hero.findMany({ select: { ID_hero: true } })
   * 
   */
  findMany<T extends heroFindManyArgs>(args?: Prisma.SelectSubset<T, heroFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Hero.
   * @param {heroCreateArgs} args - Arguments to create a Hero.
   * @example
   * // Create one Hero
   * const Hero = await prisma.hero.create({
   *   data: {
   *     // ... data to create a Hero
   *   }
   * })
   * 
   */
  create<T extends heroCreateArgs>(args: Prisma.SelectSubset<T, heroCreateArgs<ExtArgs>>): Prisma.Prisma__heroClient<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Heroes.
   * @param {heroCreateManyArgs} args - Arguments to create many Heroes.
   * @example
   * // Create many Heroes
   * const hero = await prisma.hero.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends heroCreateManyArgs>(args?: Prisma.SelectSubset<T, heroCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Hero.
   * @param {heroDeleteArgs} args - Arguments to delete one Hero.
   * @example
   * // Delete one Hero
   * const Hero = await prisma.hero.delete({
   *   where: {
   *     // ... filter to delete one Hero
   *   }
   * })
   * 
   */
  delete<T extends heroDeleteArgs>(args: Prisma.SelectSubset<T, heroDeleteArgs<ExtArgs>>): Prisma.Prisma__heroClient<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Hero.
   * @param {heroUpdateArgs} args - Arguments to update one Hero.
   * @example
   * // Update one Hero
   * const hero = await prisma.hero.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends heroUpdateArgs>(args: Prisma.SelectSubset<T, heroUpdateArgs<ExtArgs>>): Prisma.Prisma__heroClient<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Heroes.
   * @param {heroDeleteManyArgs} args - Arguments to filter Heroes to delete.
   * @example
   * // Delete a few Heroes
   * const { count } = await prisma.hero.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends heroDeleteManyArgs>(args?: Prisma.SelectSubset<T, heroDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Heroes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {heroUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Heroes
   * const hero = await prisma.hero.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends heroUpdateManyArgs>(args: Prisma.SelectSubset<T, heroUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Hero.
   * @param {heroUpsertArgs} args - Arguments to update or create a Hero.
   * @example
   * // Update or create a Hero
   * const hero = await prisma.hero.upsert({
   *   create: {
   *     // ... data to create a Hero
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Hero we want to update
   *   }
   * })
   */
  upsert<T extends heroUpsertArgs>(args: Prisma.SelectSubset<T, heroUpsertArgs<ExtArgs>>): Prisma.Prisma__heroClient<runtime.Types.Result.GetResult<Prisma.$heroPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Heroes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {heroCountArgs} args - Arguments to filter Heroes to count.
   * @example
   * // Count the number of Heroes
   * const count = await prisma.hero.count({
   *   where: {
   *     // ... the filter for the Heroes we want to count
   *   }
   * })
  **/
  count<T extends heroCountArgs>(
    args?: Prisma.Subset<T, heroCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HeroCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Hero.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeroAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HeroAggregateArgs>(args: Prisma.Subset<T, HeroAggregateArgs>): Prisma.PrismaPromise<GetHeroAggregateType<T>>

  /**
   * Group by Hero.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {heroGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends heroGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: heroGroupByArgs['orderBy'] }
      : { orderBy?: heroGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, heroGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHeroGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the hero model
 */
readonly fields: heroFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for hero.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__heroClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  actors_hero<T extends Prisma.hero$actors_heroArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.hero$actors_heroArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$actors_heroPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  performance<T extends Prisma.performanceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.performanceDefaultArgs<ExtArgs>>): Prisma.Prisma__performanceClient<runtime.Types.Result.GetResult<Prisma.$performancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the hero model
 */
export interface heroFieldRefs {
  readonly ID_hero: Prisma.FieldRef<"hero", 'Int'>
  readonly ID_performance: Prisma.FieldRef<"hero", 'Int'>
  readonly hero_description: Prisma.FieldRef<"hero", 'String'>
  readonly hero_name: Prisma.FieldRef<"hero", 'String'>
}
    

// Custom InputTypes
/**
 * hero findUnique
 */
export type heroFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
  /**
   * Filter, which hero to fetch.
   */
  where: Prisma.heroWhereUniqueInput
}

/**
 * hero findUniqueOrThrow
 */
export type heroFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
  /**
   * Filter, which hero to fetch.
   */
  where: Prisma.heroWhereUniqueInput
}

/**
 * hero findFirst
 */
export type heroFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
  /**
   * Filter, which hero to fetch.
   */
  where?: Prisma.heroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of heroes to fetch.
   */
  orderBy?: Prisma.heroOrderByWithRelationInput | Prisma.heroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for heroes.
   */
  cursor?: Prisma.heroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` heroes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of heroes.
   */
  distinct?: Prisma.HeroScalarFieldEnum | Prisma.HeroScalarFieldEnum[]
}

/**
 * hero findFirstOrThrow
 */
export type heroFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
  /**
   * Filter, which hero to fetch.
   */
  where?: Prisma.heroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of heroes to fetch.
   */
  orderBy?: Prisma.heroOrderByWithRelationInput | Prisma.heroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for heroes.
   */
  cursor?: Prisma.heroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` heroes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of heroes.
   */
  distinct?: Prisma.HeroScalarFieldEnum | Prisma.HeroScalarFieldEnum[]
}

/**
 * hero findMany
 */
export type heroFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
  /**
   * Filter, which heroes to fetch.
   */
  where?: Prisma.heroWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of heroes to fetch.
   */
  orderBy?: Prisma.heroOrderByWithRelationInput | Prisma.heroOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing heroes.
   */
  cursor?: Prisma.heroWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` heroes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` heroes.
   */
  skip?: number
  distinct?: Prisma.HeroScalarFieldEnum | Prisma.HeroScalarFieldEnum[]
}

/**
 * hero create
 */
export type heroCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
  /**
   * The data needed to create a hero.
   */
  data: Prisma.XOR<Prisma.heroCreateInput, Prisma.heroUncheckedCreateInput>
}

/**
 * hero createMany
 */
export type heroCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many heroes.
   */
  data: Prisma.heroCreateManyInput | Prisma.heroCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * hero update
 */
export type heroUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
  /**
   * The data needed to update a hero.
   */
  data: Prisma.XOR<Prisma.heroUpdateInput, Prisma.heroUncheckedUpdateInput>
  /**
   * Choose, which hero to update.
   */
  where: Prisma.heroWhereUniqueInput
}

/**
 * hero updateMany
 */
export type heroUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update heroes.
   */
  data: Prisma.XOR<Prisma.heroUpdateManyMutationInput, Prisma.heroUncheckedUpdateManyInput>
  /**
   * Filter which heroes to update
   */
  where?: Prisma.heroWhereInput
  /**
   * Limit how many heroes to update.
   */
  limit?: number
}

/**
 * hero upsert
 */
export type heroUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
  /**
   * The filter to search for the hero to update in case it exists.
   */
  where: Prisma.heroWhereUniqueInput
  /**
   * In case the hero found by the `where` argument doesn't exist, create a new hero with this data.
   */
  create: Prisma.XOR<Prisma.heroCreateInput, Prisma.heroUncheckedCreateInput>
  /**
   * In case the hero was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.heroUpdateInput, Prisma.heroUncheckedUpdateInput>
}

/**
 * hero delete
 */
export type heroDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
  /**
   * Filter which hero to delete.
   */
  where: Prisma.heroWhereUniqueInput
}

/**
 * hero deleteMany
 */
export type heroDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which heroes to delete
   */
  where?: Prisma.heroWhereInput
  /**
   * Limit how many heroes to delete.
   */
  limit?: number
}

/**
 * hero.actors_hero
 */
export type hero$actors_heroArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the actors_hero
   */
  select?: Prisma.actors_heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the actors_hero
   */
  omit?: Prisma.actors_heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.actors_heroInclude<ExtArgs> | null
  where?: Prisma.actors_heroWhereInput
  orderBy?: Prisma.actors_heroOrderByWithRelationInput | Prisma.actors_heroOrderByWithRelationInput[]
  cursor?: Prisma.actors_heroWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Actors_heroScalarFieldEnum | Prisma.Actors_heroScalarFieldEnum[]
}

/**
 * hero without action
 */
export type heroDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the hero
   */
  select?: Prisma.heroSelect<ExtArgs> | null
  /**
   * Omit specific fields from the hero
   */
  omit?: Prisma.heroOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.heroInclude<ExtArgs> | null
}
