
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `regisseur` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model regisseur
 * 
 */
export type regisseurModel = runtime.Types.Result.DefaultSelection<Prisma.$regisseurPayload>

export type AggregateRegisseur = {
  _count: RegisseurCountAggregateOutputType | null
  _avg: RegisseurAvgAggregateOutputType | null
  _sum: RegisseurSumAggregateOutputType | null
  _min: RegisseurMinAggregateOutputType | null
  _max: RegisseurMaxAggregateOutputType | null
}

export type RegisseurAvgAggregateOutputType = {
  ID_regisseur: number | null
}

export type RegisseurSumAggregateOutputType = {
  ID_regisseur: number | null
}

export type RegisseurMinAggregateOutputType = {
  ID_regisseur: number | null
  regisseur_full_name: string | null
  regisseur_text: string | null
}

export type RegisseurMaxAggregateOutputType = {
  ID_regisseur: number | null
  regisseur_full_name: string | null
  regisseur_text: string | null
}

export type RegisseurCountAggregateOutputType = {
  ID_regisseur: number
  regisseur_full_name: number
  regisseur_text: number
  _all: number
}


export type RegisseurAvgAggregateInputType = {
  ID_regisseur?: true
}

export type RegisseurSumAggregateInputType = {
  ID_regisseur?: true
}

export type RegisseurMinAggregateInputType = {
  ID_regisseur?: true
  regisseur_full_name?: true
  regisseur_text?: true
}

export type RegisseurMaxAggregateInputType = {
  ID_regisseur?: true
  regisseur_full_name?: true
  regisseur_text?: true
}

export type RegisseurCountAggregateInputType = {
  ID_regisseur?: true
  regisseur_full_name?: true
  regisseur_text?: true
  _all?: true
}

export type RegisseurAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which regisseur to aggregate.
   */
  where?: Prisma.regisseurWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of regisseurs to fetch.
   */
  orderBy?: Prisma.regisseurOrderByWithRelationInput | Prisma.regisseurOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.regisseurWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` regisseurs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` regisseurs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned regisseurs
  **/
  _count?: true | RegisseurCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RegisseurAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RegisseurSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RegisseurMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RegisseurMaxAggregateInputType
}

export type GetRegisseurAggregateType<T extends RegisseurAggregateArgs> = {
      [P in keyof T & keyof AggregateRegisseur]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRegisseur[P]>
    : Prisma.GetScalarType<T[P], AggregateRegisseur[P]>
}




export type regisseurGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.regisseurWhereInput
  orderBy?: Prisma.regisseurOrderByWithAggregationInput | Prisma.regisseurOrderByWithAggregationInput[]
  by: Prisma.RegisseurScalarFieldEnum[] | Prisma.RegisseurScalarFieldEnum
  having?: Prisma.regisseurScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RegisseurCountAggregateInputType | true
  _avg?: RegisseurAvgAggregateInputType
  _sum?: RegisseurSumAggregateInputType
  _min?: RegisseurMinAggregateInputType
  _max?: RegisseurMaxAggregateInputType
}

export type RegisseurGroupByOutputType = {
  ID_regisseur: number
  regisseur_full_name: string | null
  regisseur_text: string | null
  _count: RegisseurCountAggregateOutputType | null
  _avg: RegisseurAvgAggregateOutputType | null
  _sum: RegisseurSumAggregateOutputType | null
  _min: RegisseurMinAggregateOutputType | null
  _max: RegisseurMaxAggregateOutputType | null
}

type GetRegisseurGroupByPayload<T extends regisseurGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RegisseurGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RegisseurGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RegisseurGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RegisseurGroupByOutputType[P]>
      }
    >
  >



export type regisseurWhereInput = {
  AND?: Prisma.regisseurWhereInput | Prisma.regisseurWhereInput[]
  OR?: Prisma.regisseurWhereInput[]
  NOT?: Prisma.regisseurWhereInput | Prisma.regisseurWhereInput[]
  ID_regisseur?: Prisma.IntFilter<"regisseur"> | number
  regisseur_full_name?: Prisma.StringNullableFilter<"regisseur"> | string | null
  regisseur_text?: Prisma.StringNullableFilter<"regisseur"> | string | null
  performance?: Prisma.PerformanceListRelationFilter
}

export type regisseurOrderByWithRelationInput = {
  ID_regisseur?: Prisma.SortOrder
  regisseur_full_name?: Prisma.SortOrderInput | Prisma.SortOrder
  regisseur_text?: Prisma.SortOrderInput | Prisma.SortOrder
  performance?: Prisma.performanceOrderByRelationAggregateInput
  _relevance?: Prisma.regisseurOrderByRelevanceInput
}

export type regisseurWhereUniqueInput = Prisma.AtLeast<{
  ID_regisseur?: number
  AND?: Prisma.regisseurWhereInput | Prisma.regisseurWhereInput[]
  OR?: Prisma.regisseurWhereInput[]
  NOT?: Prisma.regisseurWhereInput | Prisma.regisseurWhereInput[]
  regisseur_full_name?: Prisma.StringNullableFilter<"regisseur"> | string | null
  regisseur_text?: Prisma.StringNullableFilter<"regisseur"> | string | null
  performance?: Prisma.PerformanceListRelationFilter
}, "ID_regisseur">

export type regisseurOrderByWithAggregationInput = {
  ID_regisseur?: Prisma.SortOrder
  regisseur_full_name?: Prisma.SortOrderInput | Prisma.SortOrder
  regisseur_text?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.regisseurCountOrderByAggregateInput
  _avg?: Prisma.regisseurAvgOrderByAggregateInput
  _max?: Prisma.regisseurMaxOrderByAggregateInput
  _min?: Prisma.regisseurMinOrderByAggregateInput
  _sum?: Prisma.regisseurSumOrderByAggregateInput
}

export type regisseurScalarWhereWithAggregatesInput = {
  AND?: Prisma.regisseurScalarWhereWithAggregatesInput | Prisma.regisseurScalarWhereWithAggregatesInput[]
  OR?: Prisma.regisseurScalarWhereWithAggregatesInput[]
  NOT?: Prisma.regisseurScalarWhereWithAggregatesInput | Prisma.regisseurScalarWhereWithAggregatesInput[]
  ID_regisseur?: Prisma.IntWithAggregatesFilter<"regisseur"> | number
  regisseur_full_name?: Prisma.StringNullableWithAggregatesFilter<"regisseur"> | string | null
  regisseur_text?: Prisma.StringNullableWithAggregatesFilter<"regisseur"> | string | null
}

export type regisseurCreateInput = {
  ID_regisseur: number
  regisseur_full_name?: string | null
  regisseur_text?: string | null
  performance?: Prisma.performanceCreateNestedManyWithoutRegisseurInput
}

export type regisseurUncheckedCreateInput = {
  ID_regisseur: number
  regisseur_full_name?: string | null
  regisseur_text?: string | null
  performance?: Prisma.performanceUncheckedCreateNestedManyWithoutRegisseurInput
}

export type regisseurUpdateInput = {
  ID_regisseur?: Prisma.IntFieldUpdateOperationsInput | number
  regisseur_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  regisseur_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performance?: Prisma.performanceUpdateManyWithoutRegisseurNestedInput
}

export type regisseurUncheckedUpdateInput = {
  ID_regisseur?: Prisma.IntFieldUpdateOperationsInput | number
  regisseur_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  regisseur_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  performance?: Prisma.performanceUncheckedUpdateManyWithoutRegisseurNestedInput
}

export type regisseurCreateManyInput = {
  ID_regisseur: number
  regisseur_full_name?: string | null
  regisseur_text?: string | null
}

export type regisseurUpdateManyMutationInput = {
  ID_regisseur?: Prisma.IntFieldUpdateOperationsInput | number
  regisseur_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  regisseur_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type regisseurUncheckedUpdateManyInput = {
  ID_regisseur?: Prisma.IntFieldUpdateOperationsInput | number
  regisseur_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  regisseur_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type RegisseurScalarRelationFilter = {
  is?: Prisma.regisseurWhereInput
  isNot?: Prisma.regisseurWhereInput
}

export type regisseurOrderByRelevanceInput = {
  fields: Prisma.regisseurOrderByRelevanceFieldEnum | Prisma.regisseurOrderByRelevanceFieldEnum[]
  sort: Prisma.SortOrder
  search: string
}

export type regisseurCountOrderByAggregateInput = {
  ID_regisseur?: Prisma.SortOrder
  regisseur_full_name?: Prisma.SortOrder
  regisseur_text?: Prisma.SortOrder
}

export type regisseurAvgOrderByAggregateInput = {
  ID_regisseur?: Prisma.SortOrder
}

export type regisseurMaxOrderByAggregateInput = {
  ID_regisseur?: Prisma.SortOrder
  regisseur_full_name?: Prisma.SortOrder
  regisseur_text?: Prisma.SortOrder
}

export type regisseurMinOrderByAggregateInput = {
  ID_regisseur?: Prisma.SortOrder
  regisseur_full_name?: Prisma.SortOrder
  regisseur_text?: Prisma.SortOrder
}

export type regisseurSumOrderByAggregateInput = {
  ID_regisseur?: Prisma.SortOrder
}

export type regisseurCreateNestedOneWithoutPerformanceInput = {
  create?: Prisma.XOR<Prisma.regisseurCreateWithoutPerformanceInput, Prisma.regisseurUncheckedCreateWithoutPerformanceInput>
  connectOrCreate?: Prisma.regisseurCreateOrConnectWithoutPerformanceInput
  connect?: Prisma.regisseurWhereUniqueInput
}

export type regisseurUpdateOneRequiredWithoutPerformanceNestedInput = {
  create?: Prisma.XOR<Prisma.regisseurCreateWithoutPerformanceInput, Prisma.regisseurUncheckedCreateWithoutPerformanceInput>
  connectOrCreate?: Prisma.regisseurCreateOrConnectWithoutPerformanceInput
  upsert?: Prisma.regisseurUpsertWithoutPerformanceInput
  connect?: Prisma.regisseurWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.regisseurUpdateToOneWithWhereWithoutPerformanceInput, Prisma.regisseurUpdateWithoutPerformanceInput>, Prisma.regisseurUncheckedUpdateWithoutPerformanceInput>
}

export type regisseurCreateWithoutPerformanceInput = {
  ID_regisseur: number
  regisseur_full_name?: string | null
  regisseur_text?: string | null
}

export type regisseurUncheckedCreateWithoutPerformanceInput = {
  ID_regisseur: number
  regisseur_full_name?: string | null
  regisseur_text?: string | null
}

export type regisseurCreateOrConnectWithoutPerformanceInput = {
  where: Prisma.regisseurWhereUniqueInput
  create: Prisma.XOR<Prisma.regisseurCreateWithoutPerformanceInput, Prisma.regisseurUncheckedCreateWithoutPerformanceInput>
}

export type regisseurUpsertWithoutPerformanceInput = {
  update: Prisma.XOR<Prisma.regisseurUpdateWithoutPerformanceInput, Prisma.regisseurUncheckedUpdateWithoutPerformanceInput>
  create: Prisma.XOR<Prisma.regisseurCreateWithoutPerformanceInput, Prisma.regisseurUncheckedCreateWithoutPerformanceInput>
  where?: Prisma.regisseurWhereInput
}

export type regisseurUpdateToOneWithWhereWithoutPerformanceInput = {
  where?: Prisma.regisseurWhereInput
  data: Prisma.XOR<Prisma.regisseurUpdateWithoutPerformanceInput, Prisma.regisseurUncheckedUpdateWithoutPerformanceInput>
}

export type regisseurUpdateWithoutPerformanceInput = {
  ID_regisseur?: Prisma.IntFieldUpdateOperationsInput | number
  regisseur_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  regisseur_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type regisseurUncheckedUpdateWithoutPerformanceInput = {
  ID_regisseur?: Prisma.IntFieldUpdateOperationsInput | number
  regisseur_full_name?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  regisseur_text?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type RegisseurCountOutputType
 */

export type RegisseurCountOutputType = {
  performance: number
}

export type RegisseurCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  performance?: boolean | RegisseurCountOutputTypeCountPerformanceArgs
}

/**
 * RegisseurCountOutputType without action
 */
export type RegisseurCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RegisseurCountOutputType
   */
  select?: Prisma.RegisseurCountOutputTypeSelect<ExtArgs> | null
}

/**
 * RegisseurCountOutputType without action
 */
export type RegisseurCountOutputTypeCountPerformanceArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.performanceWhereInput
}


export type regisseurSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  ID_regisseur?: boolean
  regisseur_full_name?: boolean
  regisseur_text?: boolean
  performance?: boolean | Prisma.regisseur$performanceArgs<ExtArgs>
  _count?: boolean | Prisma.RegisseurCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["regisseur"]>



export type regisseurSelectScalar = {
  ID_regisseur?: boolean
  regisseur_full_name?: boolean
  regisseur_text?: boolean
}

export type regisseurOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"ID_regisseur" | "regisseur_full_name" | "regisseur_text", ExtArgs["result"]["regisseur"]>
export type regisseurInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  performance?: boolean | Prisma.regisseur$performanceArgs<ExtArgs>
  _count?: boolean | Prisma.RegisseurCountOutputTypeDefaultArgs<ExtArgs>
}

export type $regisseurPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "regisseur"
  objects: {
    performance: Prisma.$performancePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    ID_regisseur: number
    regisseur_full_name: string | null
    regisseur_text: string | null
  }, ExtArgs["result"]["regisseur"]>
  composites: {}
}

export type regisseurGetPayload<S extends boolean | null | undefined | regisseurDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$regisseurPayload, S>

export type regisseurCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<regisseurFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RegisseurCountAggregateInputType | true
  }

export interface regisseurDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['regisseur'], meta: { name: 'regisseur' } }
  /**
   * Find zero or one Regisseur that matches the filter.
   * @param {regisseurFindUniqueArgs} args - Arguments to find a Regisseur
   * @example
   * // Get one Regisseur
   * const regisseur = await prisma.regisseur.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends regisseurFindUniqueArgs>(args: Prisma.SelectSubset<T, regisseurFindUniqueArgs<ExtArgs>>): Prisma.Prisma__regisseurClient<runtime.Types.Result.GetResult<Prisma.$regisseurPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Regisseur that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {regisseurFindUniqueOrThrowArgs} args - Arguments to find a Regisseur
   * @example
   * // Get one Regisseur
   * const regisseur = await prisma.regisseur.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends regisseurFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, regisseurFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__regisseurClient<runtime.Types.Result.GetResult<Prisma.$regisseurPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Regisseur that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {regisseurFindFirstArgs} args - Arguments to find a Regisseur
   * @example
   * // Get one Regisseur
   * const regisseur = await prisma.regisseur.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends regisseurFindFirstArgs>(args?: Prisma.SelectSubset<T, regisseurFindFirstArgs<ExtArgs>>): Prisma.Prisma__regisseurClient<runtime.Types.Result.GetResult<Prisma.$regisseurPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Regisseur that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {regisseurFindFirstOrThrowArgs} args - Arguments to find a Regisseur
   * @example
   * // Get one Regisseur
   * const regisseur = await prisma.regisseur.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends regisseurFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, regisseurFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__regisseurClient<runtime.Types.Result.GetResult<Prisma.$regisseurPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Regisseurs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {regisseurFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Regisseurs
   * const regisseurs = await prisma.regisseur.findMany()
   * 
   * // Get first 10 Regisseurs
   * const regisseurs = await prisma.regisseur.findMany({ take: 10 })
   * 
   * // Only select the `ID_regisseur`
   * const regisseurWithID_regisseurOnly = await prisma.regisseur.findMany({ select: { ID_regisseur: true } })
   * 
   */
  findMany<T extends regisseurFindManyArgs>(args?: Prisma.SelectSubset<T, regisseurFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$regisseurPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Regisseur.
   * @param {regisseurCreateArgs} args - Arguments to create a Regisseur.
   * @example
   * // Create one Regisseur
   * const Regisseur = await prisma.regisseur.create({
   *   data: {
   *     // ... data to create a Regisseur
   *   }
   * })
   * 
   */
  create<T extends regisseurCreateArgs>(args: Prisma.SelectSubset<T, regisseurCreateArgs<ExtArgs>>): Prisma.Prisma__regisseurClient<runtime.Types.Result.GetResult<Prisma.$regisseurPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Regisseurs.
   * @param {regisseurCreateManyArgs} args - Arguments to create many Regisseurs.
   * @example
   * // Create many Regisseurs
   * const regisseur = await prisma.regisseur.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends regisseurCreateManyArgs>(args?: Prisma.SelectSubset<T, regisseurCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Regisseur.
   * @param {regisseurDeleteArgs} args - Arguments to delete one Regisseur.
   * @example
   * // Delete one Regisseur
   * const Regisseur = await prisma.regisseur.delete({
   *   where: {
   *     // ... filter to delete one Regisseur
   *   }
   * })
   * 
   */
  delete<T extends regisseurDeleteArgs>(args: Prisma.SelectSubset<T, regisseurDeleteArgs<ExtArgs>>): Prisma.Prisma__regisseurClient<runtime.Types.Result.GetResult<Prisma.$regisseurPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Regisseur.
   * @param {regisseurUpdateArgs} args - Arguments to update one Regisseur.
   * @example
   * // Update one Regisseur
   * const regisseur = await prisma.regisseur.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends regisseurUpdateArgs>(args: Prisma.SelectSubset<T, regisseurUpdateArgs<ExtArgs>>): Prisma.Prisma__regisseurClient<runtime.Types.Result.GetResult<Prisma.$regisseurPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Regisseurs.
   * @param {regisseurDeleteManyArgs} args - Arguments to filter Regisseurs to delete.
   * @example
   * // Delete a few Regisseurs
   * const { count } = await prisma.regisseur.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends regisseurDeleteManyArgs>(args?: Prisma.SelectSubset<T, regisseurDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Regisseurs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {regisseurUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Regisseurs
   * const regisseur = await prisma.regisseur.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends regisseurUpdateManyArgs>(args: Prisma.SelectSubset<T, regisseurUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Regisseur.
   * @param {regisseurUpsertArgs} args - Arguments to update or create a Regisseur.
   * @example
   * // Update or create a Regisseur
   * const regisseur = await prisma.regisseur.upsert({
   *   create: {
   *     // ... data to create a Regisseur
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Regisseur we want to update
   *   }
   * })
   */
  upsert<T extends regisseurUpsertArgs>(args: Prisma.SelectSubset<T, regisseurUpsertArgs<ExtArgs>>): Prisma.Prisma__regisseurClient<runtime.Types.Result.GetResult<Prisma.$regisseurPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Regisseurs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {regisseurCountArgs} args - Arguments to filter Regisseurs to count.
   * @example
   * // Count the number of Regisseurs
   * const count = await prisma.regisseur.count({
   *   where: {
   *     // ... the filter for the Regisseurs we want to count
   *   }
   * })
  **/
  count<T extends regisseurCountArgs>(
    args?: Prisma.Subset<T, regisseurCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RegisseurCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Regisseur.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RegisseurAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RegisseurAggregateArgs>(args: Prisma.Subset<T, RegisseurAggregateArgs>): Prisma.PrismaPromise<GetRegisseurAggregateType<T>>

  /**
   * Group by Regisseur.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {regisseurGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends regisseurGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: regisseurGroupByArgs['orderBy'] }
      : { orderBy?: regisseurGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, regisseurGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRegisseurGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the regisseur model
 */
readonly fields: regisseurFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for regisseur.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__regisseurClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  performance<T extends Prisma.regisseur$performanceArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.regisseur$performanceArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$performancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the regisseur model
 */
export interface regisseurFieldRefs {
  readonly ID_regisseur: Prisma.FieldRef<"regisseur", 'Int'>
  readonly regisseur_full_name: Prisma.FieldRef<"regisseur", 'String'>
  readonly regisseur_text: Prisma.FieldRef<"regisseur", 'String'>
}
    

// Custom InputTypes
/**
 * regisseur findUnique
 */
export type regisseurFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
  /**
   * Filter, which regisseur to fetch.
   */
  where: Prisma.regisseurWhereUniqueInput
}

/**
 * regisseur findUniqueOrThrow
 */
export type regisseurFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
  /**
   * Filter, which regisseur to fetch.
   */
  where: Prisma.regisseurWhereUniqueInput
}

/**
 * regisseur findFirst
 */
export type regisseurFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
  /**
   * Filter, which regisseur to fetch.
   */
  where?: Prisma.regisseurWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of regisseurs to fetch.
   */
  orderBy?: Prisma.regisseurOrderByWithRelationInput | Prisma.regisseurOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for regisseurs.
   */
  cursor?: Prisma.regisseurWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` regisseurs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` regisseurs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of regisseurs.
   */
  distinct?: Prisma.RegisseurScalarFieldEnum | Prisma.RegisseurScalarFieldEnum[]
}

/**
 * regisseur findFirstOrThrow
 */
export type regisseurFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
  /**
   * Filter, which regisseur to fetch.
   */
  where?: Prisma.regisseurWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of regisseurs to fetch.
   */
  orderBy?: Prisma.regisseurOrderByWithRelationInput | Prisma.regisseurOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for regisseurs.
   */
  cursor?: Prisma.regisseurWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` regisseurs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` regisseurs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of regisseurs.
   */
  distinct?: Prisma.RegisseurScalarFieldEnum | Prisma.RegisseurScalarFieldEnum[]
}

/**
 * regisseur findMany
 */
export type regisseurFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
  /**
   * Filter, which regisseurs to fetch.
   */
  where?: Prisma.regisseurWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of regisseurs to fetch.
   */
  orderBy?: Prisma.regisseurOrderByWithRelationInput | Prisma.regisseurOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing regisseurs.
   */
  cursor?: Prisma.regisseurWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` regisseurs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` regisseurs.
   */
  skip?: number
  distinct?: Prisma.RegisseurScalarFieldEnum | Prisma.RegisseurScalarFieldEnum[]
}

/**
 * regisseur create
 */
export type regisseurCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
  /**
   * The data needed to create a regisseur.
   */
  data: Prisma.XOR<Prisma.regisseurCreateInput, Prisma.regisseurUncheckedCreateInput>
}

/**
 * regisseur createMany
 */
export type regisseurCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many regisseurs.
   */
  data: Prisma.regisseurCreateManyInput | Prisma.regisseurCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * regisseur update
 */
export type regisseurUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
  /**
   * The data needed to update a regisseur.
   */
  data: Prisma.XOR<Prisma.regisseurUpdateInput, Prisma.regisseurUncheckedUpdateInput>
  /**
   * Choose, which regisseur to update.
   */
  where: Prisma.regisseurWhereUniqueInput
}

/**
 * regisseur updateMany
 */
export type regisseurUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update regisseurs.
   */
  data: Prisma.XOR<Prisma.regisseurUpdateManyMutationInput, Prisma.regisseurUncheckedUpdateManyInput>
  /**
   * Filter which regisseurs to update
   */
  where?: Prisma.regisseurWhereInput
  /**
   * Limit how many regisseurs to update.
   */
  limit?: number
}

/**
 * regisseur upsert
 */
export type regisseurUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
  /**
   * The filter to search for the regisseur to update in case it exists.
   */
  where: Prisma.regisseurWhereUniqueInput
  /**
   * In case the regisseur found by the `where` argument doesn't exist, create a new regisseur with this data.
   */
  create: Prisma.XOR<Prisma.regisseurCreateInput, Prisma.regisseurUncheckedCreateInput>
  /**
   * In case the regisseur was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.regisseurUpdateInput, Prisma.regisseurUncheckedUpdateInput>
}

/**
 * regisseur delete
 */
export type regisseurDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
  /**
   * Filter which regisseur to delete.
   */
  where: Prisma.regisseurWhereUniqueInput
}

/**
 * regisseur deleteMany
 */
export type regisseurDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which regisseurs to delete
   */
  where?: Prisma.regisseurWhereInput
  /**
   * Limit how many regisseurs to delete.
   */
  limit?: number
}

/**
 * regisseur.performance
 */
export type regisseur$performanceArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the performance
   */
  select?: Prisma.performanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the performance
   */
  omit?: Prisma.performanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.performanceInclude<ExtArgs> | null
  where?: Prisma.performanceWhereInput
  orderBy?: Prisma.performanceOrderByWithRelationInput | Prisma.performanceOrderByWithRelationInput[]
  cursor?: Prisma.performanceWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.PerformanceScalarFieldEnum | Prisma.PerformanceScalarFieldEnum[]
}

/**
 * regisseur without action
 */
export type regisseurDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the regisseur
   */
  select?: Prisma.regisseurSelect<ExtArgs> | null
  /**
   * Omit specific fields from the regisseur
   */
  omit?: Prisma.regisseurOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.regisseurInclude<ExtArgs> | null
}
