
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `seance` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model seance
 * 
 */
export type seanceModel = runtime.Types.Result.DefaultSelection<Prisma.$seancePayload>

export type AggregateSeance = {
  _count: SeanceCountAggregateOutputType | null
  _avg: SeanceAvgAggregateOutputType | null
  _sum: SeanceSumAggregateOutputType | null
  _min: SeanceMinAggregateOutputType | null
  _max: SeanceMaxAggregateOutputType | null
}

export type SeanceAvgAggregateOutputType = {
  ID_seance: number | null
  ID_performance: number | null
  ID_hall: number | null
}

export type SeanceSumAggregateOutputType = {
  ID_seance: number | null
  ID_performance: number | null
  ID_hall: number | null
}

export type SeanceMinAggregateOutputType = {
  ID_seance: number | null
  ID_performance: number | null
  seance_time: Date | null
  seance_date: Date | null
  ID_hall: number | null
}

export type SeanceMaxAggregateOutputType = {
  ID_seance: number | null
  ID_performance: number | null
  seance_time: Date | null
  seance_date: Date | null
  ID_hall: number | null
}

export type SeanceCountAggregateOutputType = {
  ID_seance: number
  ID_performance: number
  seance_time: number
  seance_date: number
  ID_hall: number
  _all: number
}


export type SeanceAvgAggregateInputType = {
  ID_seance?: true
  ID_performance?: true
  ID_hall?: true
}

export type SeanceSumAggregateInputType = {
  ID_seance?: true
  ID_performance?: true
  ID_hall?: true
}

export type SeanceMinAggregateInputType = {
  ID_seance?: true
  ID_performance?: true
  seance_time?: true
  seance_date?: true
  ID_hall?: true
}

export type SeanceMaxAggregateInputType = {
  ID_seance?: true
  ID_performance?: true
  seance_time?: true
  seance_date?: true
  ID_hall?: true
}

export type SeanceCountAggregateInputType = {
  ID_seance?: true
  ID_performance?: true
  seance_time?: true
  seance_date?: true
  ID_hall?: true
  _all?: true
}

export type SeanceAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which seance to aggregate.
   */
  where?: Prisma.seanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of seances to fetch.
   */
  orderBy?: Prisma.seanceOrderByWithRelationInput | Prisma.seanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.seanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` seances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` seances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned seances
  **/
  _count?: true | SeanceCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: SeanceAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: SeanceSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: SeanceMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: SeanceMaxAggregateInputType
}

export type GetSeanceAggregateType<T extends SeanceAggregateArgs> = {
      [P in keyof T & keyof AggregateSeance]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateSeance[P]>
    : Prisma.GetScalarType<T[P], AggregateSeance[P]>
}




export type seanceGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.seanceWhereInput
  orderBy?: Prisma.seanceOrderByWithAggregationInput | Prisma.seanceOrderByWithAggregationInput[]
  by: Prisma.SeanceScalarFieldEnum[] | Prisma.SeanceScalarFieldEnum
  having?: Prisma.seanceScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: SeanceCountAggregateInputType | true
  _avg?: SeanceAvgAggregateInputType
  _sum?: SeanceSumAggregateInputType
  _min?: SeanceMinAggregateInputType
  _max?: SeanceMaxAggregateInputType
}

export type SeanceGroupByOutputType = {
  ID_seance: number
  ID_performance: number
  seance_time: Date | null
  seance_date: Date
  ID_hall: number
  _count: SeanceCountAggregateOutputType | null
  _avg: SeanceAvgAggregateOutputType | null
  _sum: SeanceSumAggregateOutputType | null
  _min: SeanceMinAggregateOutputType | null
  _max: SeanceMaxAggregateOutputType | null
}

type GetSeanceGroupByPayload<T extends seanceGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<SeanceGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof SeanceGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], SeanceGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], SeanceGroupByOutputType[P]>
      }
    >
  >



export type seanceWhereInput = {
  AND?: Prisma.seanceWhereInput | Prisma.seanceWhereInput[]
  OR?: Prisma.seanceWhereInput[]
  NOT?: Prisma.seanceWhereInput | Prisma.seanceWhereInput[]
  ID_seance?: Prisma.IntFilter<"seance"> | number
  ID_performance?: Prisma.IntFilter<"seance"> | number
  seance_time?: Prisma.DateTimeNullableFilter<"seance"> | Date | string | null
  seance_date?: Prisma.DateTimeFilter<"seance"> | Date | string
  ID_hall?: Prisma.IntFilter<"seance"> | number
  comm?: Prisma.CommListRelationFilter
  performance?: Prisma.XOR<Prisma.PerformanceScalarRelationFilter, Prisma.performanceWhereInput>
  hall?: Prisma.XOR<Prisma.HallScalarRelationFilter, Prisma.hallWhereInput>
  ticket?: Prisma.TicketListRelationFilter
}

export type seanceOrderByWithRelationInput = {
  ID_seance?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  seance_time?: Prisma.SortOrderInput | Prisma.SortOrder
  seance_date?: Prisma.SortOrder
  ID_hall?: Prisma.SortOrder
  comm?: Prisma.commOrderByRelationAggregateInput
  performance?: Prisma.performanceOrderByWithRelationInput
  hall?: Prisma.hallOrderByWithRelationInput
  ticket?: Prisma.ticketOrderByRelationAggregateInput
}

export type seanceWhereUniqueInput = Prisma.AtLeast<{
  ID_seance?: number
  AND?: Prisma.seanceWhereInput | Prisma.seanceWhereInput[]
  OR?: Prisma.seanceWhereInput[]
  NOT?: Prisma.seanceWhereInput | Prisma.seanceWhereInput[]
  ID_performance?: Prisma.IntFilter<"seance"> | number
  seance_time?: Prisma.DateTimeNullableFilter<"seance"> | Date | string | null
  seance_date?: Prisma.DateTimeFilter<"seance"> | Date | string
  ID_hall?: Prisma.IntFilter<"seance"> | number
  comm?: Prisma.CommListRelationFilter
  performance?: Prisma.XOR<Prisma.PerformanceScalarRelationFilter, Prisma.performanceWhereInput>
  hall?: Prisma.XOR<Prisma.HallScalarRelationFilter, Prisma.hallWhereInput>
  ticket?: Prisma.TicketListRelationFilter
}, "ID_seance">

export type seanceOrderByWithAggregationInput = {
  ID_seance?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  seance_time?: Prisma.SortOrderInput | Prisma.SortOrder
  seance_date?: Prisma.SortOrder
  ID_hall?: Prisma.SortOrder
  _count?: Prisma.seanceCountOrderByAggregateInput
  _avg?: Prisma.seanceAvgOrderByAggregateInput
  _max?: Prisma.seanceMaxOrderByAggregateInput
  _min?: Prisma.seanceMinOrderByAggregateInput
  _sum?: Prisma.seanceSumOrderByAggregateInput
}

export type seanceScalarWhereWithAggregatesInput = {
  AND?: Prisma.seanceScalarWhereWithAggregatesInput | Prisma.seanceScalarWhereWithAggregatesInput[]
  OR?: Prisma.seanceScalarWhereWithAggregatesInput[]
  NOT?: Prisma.seanceScalarWhereWithAggregatesInput | Prisma.seanceScalarWhereWithAggregatesInput[]
  ID_seance?: Prisma.IntWithAggregatesFilter<"seance"> | number
  ID_performance?: Prisma.IntWithAggregatesFilter<"seance"> | number
  seance_time?: Prisma.DateTimeNullableWithAggregatesFilter<"seance"> | Date | string | null
  seance_date?: Prisma.DateTimeWithAggregatesFilter<"seance"> | Date | string
  ID_hall?: Prisma.IntWithAggregatesFilter<"seance"> | number
}

export type seanceCreateInput = {
  ID_seance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  comm?: Prisma.commCreateNestedManyWithoutSeanceInput
  performance: Prisma.performanceCreateNestedOneWithoutSeanceInput
  hall: Prisma.hallCreateNestedOneWithoutSeanceInput
  ticket?: Prisma.ticketCreateNestedManyWithoutSeanceInput
}

export type seanceUncheckedCreateInput = {
  ID_seance: number
  ID_performance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  ID_hall: number
  comm?: Prisma.commUncheckedCreateNestedManyWithoutSeanceInput
  ticket?: Prisma.ticketUncheckedCreateNestedManyWithoutSeanceInput
}

export type seanceUpdateInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  comm?: Prisma.commUpdateManyWithoutSeanceNestedInput
  performance?: Prisma.performanceUpdateOneRequiredWithoutSeanceNestedInput
  hall?: Prisma.hallUpdateOneRequiredWithoutSeanceNestedInput
  ticket?: Prisma.ticketUpdateManyWithoutSeanceNestedInput
}

export type seanceUncheckedUpdateInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_performance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  comm?: Prisma.commUncheckedUpdateManyWithoutSeanceNestedInput
  ticket?: Prisma.ticketUncheckedUpdateManyWithoutSeanceNestedInput
}

export type seanceCreateManyInput = {
  ID_seance: number
  ID_performance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  ID_hall: number
}

export type seanceUpdateManyMutationInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type seanceUncheckedUpdateManyInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_performance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
}

export type SeanceScalarRelationFilter = {
  is?: Prisma.seanceWhereInput
  isNot?: Prisma.seanceWhereInput
}

export type SeanceListRelationFilter = {
  every?: Prisma.seanceWhereInput
  some?: Prisma.seanceWhereInput
  none?: Prisma.seanceWhereInput
}

export type seanceOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type seanceCountOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  seance_time?: Prisma.SortOrder
  seance_date?: Prisma.SortOrder
  ID_hall?: Prisma.SortOrder
}

export type seanceAvgOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  ID_hall?: Prisma.SortOrder
}

export type seanceMaxOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  seance_time?: Prisma.SortOrder
  seance_date?: Prisma.SortOrder
  ID_hall?: Prisma.SortOrder
}

export type seanceMinOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  seance_time?: Prisma.SortOrder
  seance_date?: Prisma.SortOrder
  ID_hall?: Prisma.SortOrder
}

export type seanceSumOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_performance?: Prisma.SortOrder
  ID_hall?: Prisma.SortOrder
}

export type seanceCreateNestedOneWithoutCommInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutCommInput, Prisma.seanceUncheckedCreateWithoutCommInput>
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutCommInput
  connect?: Prisma.seanceWhereUniqueInput
}

export type seanceUpdateOneRequiredWithoutCommNestedInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutCommInput, Prisma.seanceUncheckedCreateWithoutCommInput>
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutCommInput
  upsert?: Prisma.seanceUpsertWithoutCommInput
  connect?: Prisma.seanceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.seanceUpdateToOneWithWhereWithoutCommInput, Prisma.seanceUpdateWithoutCommInput>, Prisma.seanceUncheckedUpdateWithoutCommInput>
}

export type seanceCreateNestedManyWithoutHallInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutHallInput, Prisma.seanceUncheckedCreateWithoutHallInput> | Prisma.seanceCreateWithoutHallInput[] | Prisma.seanceUncheckedCreateWithoutHallInput[]
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutHallInput | Prisma.seanceCreateOrConnectWithoutHallInput[]
  createMany?: Prisma.seanceCreateManyHallInputEnvelope
  connect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
}

export type seanceUncheckedCreateNestedManyWithoutHallInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutHallInput, Prisma.seanceUncheckedCreateWithoutHallInput> | Prisma.seanceCreateWithoutHallInput[] | Prisma.seanceUncheckedCreateWithoutHallInput[]
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutHallInput | Prisma.seanceCreateOrConnectWithoutHallInput[]
  createMany?: Prisma.seanceCreateManyHallInputEnvelope
  connect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
}

export type seanceUpdateManyWithoutHallNestedInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutHallInput, Prisma.seanceUncheckedCreateWithoutHallInput> | Prisma.seanceCreateWithoutHallInput[] | Prisma.seanceUncheckedCreateWithoutHallInput[]
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutHallInput | Prisma.seanceCreateOrConnectWithoutHallInput[]
  upsert?: Prisma.seanceUpsertWithWhereUniqueWithoutHallInput | Prisma.seanceUpsertWithWhereUniqueWithoutHallInput[]
  createMany?: Prisma.seanceCreateManyHallInputEnvelope
  set?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  disconnect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  delete?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  connect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  update?: Prisma.seanceUpdateWithWhereUniqueWithoutHallInput | Prisma.seanceUpdateWithWhereUniqueWithoutHallInput[]
  updateMany?: Prisma.seanceUpdateManyWithWhereWithoutHallInput | Prisma.seanceUpdateManyWithWhereWithoutHallInput[]
  deleteMany?: Prisma.seanceScalarWhereInput | Prisma.seanceScalarWhereInput[]
}

export type seanceUncheckedUpdateManyWithoutHallNestedInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutHallInput, Prisma.seanceUncheckedCreateWithoutHallInput> | Prisma.seanceCreateWithoutHallInput[] | Prisma.seanceUncheckedCreateWithoutHallInput[]
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutHallInput | Prisma.seanceCreateOrConnectWithoutHallInput[]
  upsert?: Prisma.seanceUpsertWithWhereUniqueWithoutHallInput | Prisma.seanceUpsertWithWhereUniqueWithoutHallInput[]
  createMany?: Prisma.seanceCreateManyHallInputEnvelope
  set?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  disconnect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  delete?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  connect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  update?: Prisma.seanceUpdateWithWhereUniqueWithoutHallInput | Prisma.seanceUpdateWithWhereUniqueWithoutHallInput[]
  updateMany?: Prisma.seanceUpdateManyWithWhereWithoutHallInput | Prisma.seanceUpdateManyWithWhereWithoutHallInput[]
  deleteMany?: Prisma.seanceScalarWhereInput | Prisma.seanceScalarWhereInput[]
}

export type seanceCreateNestedManyWithoutPerformanceInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutPerformanceInput, Prisma.seanceUncheckedCreateWithoutPerformanceInput> | Prisma.seanceCreateWithoutPerformanceInput[] | Prisma.seanceUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutPerformanceInput | Prisma.seanceCreateOrConnectWithoutPerformanceInput[]
  createMany?: Prisma.seanceCreateManyPerformanceInputEnvelope
  connect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
}

export type seanceUncheckedCreateNestedManyWithoutPerformanceInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutPerformanceInput, Prisma.seanceUncheckedCreateWithoutPerformanceInput> | Prisma.seanceCreateWithoutPerformanceInput[] | Prisma.seanceUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutPerformanceInput | Prisma.seanceCreateOrConnectWithoutPerformanceInput[]
  createMany?: Prisma.seanceCreateManyPerformanceInputEnvelope
  connect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
}

export type seanceUpdateManyWithoutPerformanceNestedInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutPerformanceInput, Prisma.seanceUncheckedCreateWithoutPerformanceInput> | Prisma.seanceCreateWithoutPerformanceInput[] | Prisma.seanceUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutPerformanceInput | Prisma.seanceCreateOrConnectWithoutPerformanceInput[]
  upsert?: Prisma.seanceUpsertWithWhereUniqueWithoutPerformanceInput | Prisma.seanceUpsertWithWhereUniqueWithoutPerformanceInput[]
  createMany?: Prisma.seanceCreateManyPerformanceInputEnvelope
  set?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  disconnect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  delete?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  connect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  update?: Prisma.seanceUpdateWithWhereUniqueWithoutPerformanceInput | Prisma.seanceUpdateWithWhereUniqueWithoutPerformanceInput[]
  updateMany?: Prisma.seanceUpdateManyWithWhereWithoutPerformanceInput | Prisma.seanceUpdateManyWithWhereWithoutPerformanceInput[]
  deleteMany?: Prisma.seanceScalarWhereInput | Prisma.seanceScalarWhereInput[]
}

export type seanceUncheckedUpdateManyWithoutPerformanceNestedInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutPerformanceInput, Prisma.seanceUncheckedCreateWithoutPerformanceInput> | Prisma.seanceCreateWithoutPerformanceInput[] | Prisma.seanceUncheckedCreateWithoutPerformanceInput[]
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutPerformanceInput | Prisma.seanceCreateOrConnectWithoutPerformanceInput[]
  upsert?: Prisma.seanceUpsertWithWhereUniqueWithoutPerformanceInput | Prisma.seanceUpsertWithWhereUniqueWithoutPerformanceInput[]
  createMany?: Prisma.seanceCreateManyPerformanceInputEnvelope
  set?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  disconnect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  delete?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  connect?: Prisma.seanceWhereUniqueInput | Prisma.seanceWhereUniqueInput[]
  update?: Prisma.seanceUpdateWithWhereUniqueWithoutPerformanceInput | Prisma.seanceUpdateWithWhereUniqueWithoutPerformanceInput[]
  updateMany?: Prisma.seanceUpdateManyWithWhereWithoutPerformanceInput | Prisma.seanceUpdateManyWithWhereWithoutPerformanceInput[]
  deleteMany?: Prisma.seanceScalarWhereInput | Prisma.seanceScalarWhereInput[]
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type seanceCreateNestedOneWithoutTicketInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutTicketInput, Prisma.seanceUncheckedCreateWithoutTicketInput>
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutTicketInput
  connect?: Prisma.seanceWhereUniqueInput
}

export type seanceUpdateOneRequiredWithoutTicketNestedInput = {
  create?: Prisma.XOR<Prisma.seanceCreateWithoutTicketInput, Prisma.seanceUncheckedCreateWithoutTicketInput>
  connectOrCreate?: Prisma.seanceCreateOrConnectWithoutTicketInput
  upsert?: Prisma.seanceUpsertWithoutTicketInput
  connect?: Prisma.seanceWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.seanceUpdateToOneWithWhereWithoutTicketInput, Prisma.seanceUpdateWithoutTicketInput>, Prisma.seanceUncheckedUpdateWithoutTicketInput>
}

export type seanceCreateWithoutCommInput = {
  ID_seance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  performance: Prisma.performanceCreateNestedOneWithoutSeanceInput
  hall: Prisma.hallCreateNestedOneWithoutSeanceInput
  ticket?: Prisma.ticketCreateNestedManyWithoutSeanceInput
}

export type seanceUncheckedCreateWithoutCommInput = {
  ID_seance: number
  ID_performance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  ID_hall: number
  ticket?: Prisma.ticketUncheckedCreateNestedManyWithoutSeanceInput
}

export type seanceCreateOrConnectWithoutCommInput = {
  where: Prisma.seanceWhereUniqueInput
  create: Prisma.XOR<Prisma.seanceCreateWithoutCommInput, Prisma.seanceUncheckedCreateWithoutCommInput>
}

export type seanceUpsertWithoutCommInput = {
  update: Prisma.XOR<Prisma.seanceUpdateWithoutCommInput, Prisma.seanceUncheckedUpdateWithoutCommInput>
  create: Prisma.XOR<Prisma.seanceCreateWithoutCommInput, Prisma.seanceUncheckedCreateWithoutCommInput>
  where?: Prisma.seanceWhereInput
}

export type seanceUpdateToOneWithWhereWithoutCommInput = {
  where?: Prisma.seanceWhereInput
  data: Prisma.XOR<Prisma.seanceUpdateWithoutCommInput, Prisma.seanceUncheckedUpdateWithoutCommInput>
}

export type seanceUpdateWithoutCommInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  performance?: Prisma.performanceUpdateOneRequiredWithoutSeanceNestedInput
  hall?: Prisma.hallUpdateOneRequiredWithoutSeanceNestedInput
  ticket?: Prisma.ticketUpdateManyWithoutSeanceNestedInput
}

export type seanceUncheckedUpdateWithoutCommInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_performance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  ticket?: Prisma.ticketUncheckedUpdateManyWithoutSeanceNestedInput
}

export type seanceCreateWithoutHallInput = {
  ID_seance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  comm?: Prisma.commCreateNestedManyWithoutSeanceInput
  performance: Prisma.performanceCreateNestedOneWithoutSeanceInput
  ticket?: Prisma.ticketCreateNestedManyWithoutSeanceInput
}

export type seanceUncheckedCreateWithoutHallInput = {
  ID_seance: number
  ID_performance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  comm?: Prisma.commUncheckedCreateNestedManyWithoutSeanceInput
  ticket?: Prisma.ticketUncheckedCreateNestedManyWithoutSeanceInput
}

export type seanceCreateOrConnectWithoutHallInput = {
  where: Prisma.seanceWhereUniqueInput
  create: Prisma.XOR<Prisma.seanceCreateWithoutHallInput, Prisma.seanceUncheckedCreateWithoutHallInput>
}

export type seanceCreateManyHallInputEnvelope = {
  data: Prisma.seanceCreateManyHallInput | Prisma.seanceCreateManyHallInput[]
  skipDuplicates?: boolean
}

export type seanceUpsertWithWhereUniqueWithoutHallInput = {
  where: Prisma.seanceWhereUniqueInput
  update: Prisma.XOR<Prisma.seanceUpdateWithoutHallInput, Prisma.seanceUncheckedUpdateWithoutHallInput>
  create: Prisma.XOR<Prisma.seanceCreateWithoutHallInput, Prisma.seanceUncheckedCreateWithoutHallInput>
}

export type seanceUpdateWithWhereUniqueWithoutHallInput = {
  where: Prisma.seanceWhereUniqueInput
  data: Prisma.XOR<Prisma.seanceUpdateWithoutHallInput, Prisma.seanceUncheckedUpdateWithoutHallInput>
}

export type seanceUpdateManyWithWhereWithoutHallInput = {
  where: Prisma.seanceScalarWhereInput
  data: Prisma.XOR<Prisma.seanceUpdateManyMutationInput, Prisma.seanceUncheckedUpdateManyWithoutHallInput>
}

export type seanceScalarWhereInput = {
  AND?: Prisma.seanceScalarWhereInput | Prisma.seanceScalarWhereInput[]
  OR?: Prisma.seanceScalarWhereInput[]
  NOT?: Prisma.seanceScalarWhereInput | Prisma.seanceScalarWhereInput[]
  ID_seance?: Prisma.IntFilter<"seance"> | number
  ID_performance?: Prisma.IntFilter<"seance"> | number
  seance_time?: Prisma.DateTimeNullableFilter<"seance"> | Date | string | null
  seance_date?: Prisma.DateTimeFilter<"seance"> | Date | string
  ID_hall?: Prisma.IntFilter<"seance"> | number
}

export type seanceCreateWithoutPerformanceInput = {
  ID_seance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  comm?: Prisma.commCreateNestedManyWithoutSeanceInput
  hall: Prisma.hallCreateNestedOneWithoutSeanceInput
  ticket?: Prisma.ticketCreateNestedManyWithoutSeanceInput
}

export type seanceUncheckedCreateWithoutPerformanceInput = {
  ID_seance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  ID_hall: number
  comm?: Prisma.commUncheckedCreateNestedManyWithoutSeanceInput
  ticket?: Prisma.ticketUncheckedCreateNestedManyWithoutSeanceInput
}

export type seanceCreateOrConnectWithoutPerformanceInput = {
  where: Prisma.seanceWhereUniqueInput
  create: Prisma.XOR<Prisma.seanceCreateWithoutPerformanceInput, Prisma.seanceUncheckedCreateWithoutPerformanceInput>
}

export type seanceCreateManyPerformanceInputEnvelope = {
  data: Prisma.seanceCreateManyPerformanceInput | Prisma.seanceCreateManyPerformanceInput[]
  skipDuplicates?: boolean
}

export type seanceUpsertWithWhereUniqueWithoutPerformanceInput = {
  where: Prisma.seanceWhereUniqueInput
  update: Prisma.XOR<Prisma.seanceUpdateWithoutPerformanceInput, Prisma.seanceUncheckedUpdateWithoutPerformanceInput>
  create: Prisma.XOR<Prisma.seanceCreateWithoutPerformanceInput, Prisma.seanceUncheckedCreateWithoutPerformanceInput>
}

export type seanceUpdateWithWhereUniqueWithoutPerformanceInput = {
  where: Prisma.seanceWhereUniqueInput
  data: Prisma.XOR<Prisma.seanceUpdateWithoutPerformanceInput, Prisma.seanceUncheckedUpdateWithoutPerformanceInput>
}

export type seanceUpdateManyWithWhereWithoutPerformanceInput = {
  where: Prisma.seanceScalarWhereInput
  data: Prisma.XOR<Prisma.seanceUpdateManyMutationInput, Prisma.seanceUncheckedUpdateManyWithoutPerformanceInput>
}

export type seanceCreateWithoutTicketInput = {
  ID_seance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  comm?: Prisma.commCreateNestedManyWithoutSeanceInput
  performance: Prisma.performanceCreateNestedOneWithoutSeanceInput
  hall: Prisma.hallCreateNestedOneWithoutSeanceInput
}

export type seanceUncheckedCreateWithoutTicketInput = {
  ID_seance: number
  ID_performance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  ID_hall: number
  comm?: Prisma.commUncheckedCreateNestedManyWithoutSeanceInput
}

export type seanceCreateOrConnectWithoutTicketInput = {
  where: Prisma.seanceWhereUniqueInput
  create: Prisma.XOR<Prisma.seanceCreateWithoutTicketInput, Prisma.seanceUncheckedCreateWithoutTicketInput>
}

export type seanceUpsertWithoutTicketInput = {
  update: Prisma.XOR<Prisma.seanceUpdateWithoutTicketInput, Prisma.seanceUncheckedUpdateWithoutTicketInput>
  create: Prisma.XOR<Prisma.seanceCreateWithoutTicketInput, Prisma.seanceUncheckedCreateWithoutTicketInput>
  where?: Prisma.seanceWhereInput
}

export type seanceUpdateToOneWithWhereWithoutTicketInput = {
  where?: Prisma.seanceWhereInput
  data: Prisma.XOR<Prisma.seanceUpdateWithoutTicketInput, Prisma.seanceUncheckedUpdateWithoutTicketInput>
}

export type seanceUpdateWithoutTicketInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  comm?: Prisma.commUpdateManyWithoutSeanceNestedInput
  performance?: Prisma.performanceUpdateOneRequiredWithoutSeanceNestedInput
  hall?: Prisma.hallUpdateOneRequiredWithoutSeanceNestedInput
}

export type seanceUncheckedUpdateWithoutTicketInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_performance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  comm?: Prisma.commUncheckedUpdateManyWithoutSeanceNestedInput
}

export type seanceCreateManyHallInput = {
  ID_seance: number
  ID_performance: number
  seance_time?: Date | string | null
  seance_date: Date | string
}

export type seanceUpdateWithoutHallInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  comm?: Prisma.commUpdateManyWithoutSeanceNestedInput
  performance?: Prisma.performanceUpdateOneRequiredWithoutSeanceNestedInput
  ticket?: Prisma.ticketUpdateManyWithoutSeanceNestedInput
}

export type seanceUncheckedUpdateWithoutHallInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_performance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  comm?: Prisma.commUncheckedUpdateManyWithoutSeanceNestedInput
  ticket?: Prisma.ticketUncheckedUpdateManyWithoutSeanceNestedInput
}

export type seanceUncheckedUpdateManyWithoutHallInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_performance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type seanceCreateManyPerformanceInput = {
  ID_seance: number
  seance_time?: Date | string | null
  seance_date: Date | string
  ID_hall: number
}

export type seanceUpdateWithoutPerformanceInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  comm?: Prisma.commUpdateManyWithoutSeanceNestedInput
  hall?: Prisma.hallUpdateOneRequiredWithoutSeanceNestedInput
  ticket?: Prisma.ticketUpdateManyWithoutSeanceNestedInput
}

export type seanceUncheckedUpdateWithoutPerformanceInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
  comm?: Prisma.commUncheckedUpdateManyWithoutSeanceNestedInput
  ticket?: Prisma.ticketUncheckedUpdateManyWithoutSeanceNestedInput
}

export type seanceUncheckedUpdateManyWithoutPerformanceInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  seance_time?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  seance_date?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  ID_hall?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type SeanceCountOutputType
 */

export type SeanceCountOutputType = {
  comm: number
  ticket: number
}

export type SeanceCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comm?: boolean | SeanceCountOutputTypeCountCommArgs
  ticket?: boolean | SeanceCountOutputTypeCountTicketArgs
}

/**
 * SeanceCountOutputType without action
 */
export type SeanceCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SeanceCountOutputType
   */
  select?: Prisma.SeanceCountOutputTypeSelect<ExtArgs> | null
}

/**
 * SeanceCountOutputType without action
 */
export type SeanceCountOutputTypeCountCommArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.commWhereInput
}

/**
 * SeanceCountOutputType without action
 */
export type SeanceCountOutputTypeCountTicketArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ticketWhereInput
}


export type seanceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  ID_seance?: boolean
  ID_performance?: boolean
  seance_time?: boolean
  seance_date?: boolean
  ID_hall?: boolean
  comm?: boolean | Prisma.seance$commArgs<ExtArgs>
  performance?: boolean | Prisma.performanceDefaultArgs<ExtArgs>
  hall?: boolean | Prisma.hallDefaultArgs<ExtArgs>
  ticket?: boolean | Prisma.seance$ticketArgs<ExtArgs>
  _count?: boolean | Prisma.SeanceCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["seance"]>



export type seanceSelectScalar = {
  ID_seance?: boolean
  ID_performance?: boolean
  seance_time?: boolean
  seance_date?: boolean
  ID_hall?: boolean
}

export type seanceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"ID_seance" | "ID_performance" | "seance_time" | "seance_date" | "ID_hall", ExtArgs["result"]["seance"]>
export type seanceInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  comm?: boolean | Prisma.seance$commArgs<ExtArgs>
  performance?: boolean | Prisma.performanceDefaultArgs<ExtArgs>
  hall?: boolean | Prisma.hallDefaultArgs<ExtArgs>
  ticket?: boolean | Prisma.seance$ticketArgs<ExtArgs>
  _count?: boolean | Prisma.SeanceCountOutputTypeDefaultArgs<ExtArgs>
}

export type $seancePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "seance"
  objects: {
    comm: Prisma.$commPayload<ExtArgs>[]
    performance: Prisma.$performancePayload<ExtArgs>
    hall: Prisma.$hallPayload<ExtArgs>
    ticket: Prisma.$ticketPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    ID_seance: number
    ID_performance: number
    seance_time: Date | null
    seance_date: Date
    ID_hall: number
  }, ExtArgs["result"]["seance"]>
  composites: {}
}

export type seanceGetPayload<S extends boolean | null | undefined | seanceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$seancePayload, S>

export type seanceCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<seanceFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: SeanceCountAggregateInputType | true
  }

export interface seanceDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['seance'], meta: { name: 'seance' } }
  /**
   * Find zero or one Seance that matches the filter.
   * @param {seanceFindUniqueArgs} args - Arguments to find a Seance
   * @example
   * // Get one Seance
   * const seance = await prisma.seance.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends seanceFindUniqueArgs>(args: Prisma.SelectSubset<T, seanceFindUniqueArgs<ExtArgs>>): Prisma.Prisma__seanceClient<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Seance that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {seanceFindUniqueOrThrowArgs} args - Arguments to find a Seance
   * @example
   * // Get one Seance
   * const seance = await prisma.seance.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends seanceFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, seanceFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__seanceClient<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Seance that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {seanceFindFirstArgs} args - Arguments to find a Seance
   * @example
   * // Get one Seance
   * const seance = await prisma.seance.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends seanceFindFirstArgs>(args?: Prisma.SelectSubset<T, seanceFindFirstArgs<ExtArgs>>): Prisma.Prisma__seanceClient<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Seance that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {seanceFindFirstOrThrowArgs} args - Arguments to find a Seance
   * @example
   * // Get one Seance
   * const seance = await prisma.seance.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends seanceFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, seanceFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__seanceClient<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Seances that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {seanceFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Seances
   * const seances = await prisma.seance.findMany()
   * 
   * // Get first 10 Seances
   * const seances = await prisma.seance.findMany({ take: 10 })
   * 
   * // Only select the `ID_seance`
   * const seanceWithID_seanceOnly = await prisma.seance.findMany({ select: { ID_seance: true } })
   * 
   */
  findMany<T extends seanceFindManyArgs>(args?: Prisma.SelectSubset<T, seanceFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Seance.
   * @param {seanceCreateArgs} args - Arguments to create a Seance.
   * @example
   * // Create one Seance
   * const Seance = await prisma.seance.create({
   *   data: {
   *     // ... data to create a Seance
   *   }
   * })
   * 
   */
  create<T extends seanceCreateArgs>(args: Prisma.SelectSubset<T, seanceCreateArgs<ExtArgs>>): Prisma.Prisma__seanceClient<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Seances.
   * @param {seanceCreateManyArgs} args - Arguments to create many Seances.
   * @example
   * // Create many Seances
   * const seance = await prisma.seance.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends seanceCreateManyArgs>(args?: Prisma.SelectSubset<T, seanceCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Seance.
   * @param {seanceDeleteArgs} args - Arguments to delete one Seance.
   * @example
   * // Delete one Seance
   * const Seance = await prisma.seance.delete({
   *   where: {
   *     // ... filter to delete one Seance
   *   }
   * })
   * 
   */
  delete<T extends seanceDeleteArgs>(args: Prisma.SelectSubset<T, seanceDeleteArgs<ExtArgs>>): Prisma.Prisma__seanceClient<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Seance.
   * @param {seanceUpdateArgs} args - Arguments to update one Seance.
   * @example
   * // Update one Seance
   * const seance = await prisma.seance.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends seanceUpdateArgs>(args: Prisma.SelectSubset<T, seanceUpdateArgs<ExtArgs>>): Prisma.Prisma__seanceClient<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Seances.
   * @param {seanceDeleteManyArgs} args - Arguments to filter Seances to delete.
   * @example
   * // Delete a few Seances
   * const { count } = await prisma.seance.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends seanceDeleteManyArgs>(args?: Prisma.SelectSubset<T, seanceDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Seances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {seanceUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Seances
   * const seance = await prisma.seance.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends seanceUpdateManyArgs>(args: Prisma.SelectSubset<T, seanceUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Seance.
   * @param {seanceUpsertArgs} args - Arguments to update or create a Seance.
   * @example
   * // Update or create a Seance
   * const seance = await prisma.seance.upsert({
   *   create: {
   *     // ... data to create a Seance
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Seance we want to update
   *   }
   * })
   */
  upsert<T extends seanceUpsertArgs>(args: Prisma.SelectSubset<T, seanceUpsertArgs<ExtArgs>>): Prisma.Prisma__seanceClient<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Seances.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {seanceCountArgs} args - Arguments to filter Seances to count.
   * @example
   * // Count the number of Seances
   * const count = await prisma.seance.count({
   *   where: {
   *     // ... the filter for the Seances we want to count
   *   }
   * })
  **/
  count<T extends seanceCountArgs>(
    args?: Prisma.Subset<T, seanceCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], SeanceCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Seance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {SeanceAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends SeanceAggregateArgs>(args: Prisma.Subset<T, SeanceAggregateArgs>): Prisma.PrismaPromise<GetSeanceAggregateType<T>>

  /**
   * Group by Seance.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {seanceGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends seanceGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: seanceGroupByArgs['orderBy'] }
      : { orderBy?: seanceGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, seanceGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetSeanceGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the seance model
 */
readonly fields: seanceFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for seance.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__seanceClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  comm<T extends Prisma.seance$commArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.seance$commArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$commPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  performance<T extends Prisma.performanceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.performanceDefaultArgs<ExtArgs>>): Prisma.Prisma__performanceClient<runtime.Types.Result.GetResult<Prisma.$performancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  hall<T extends Prisma.hallDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.hallDefaultArgs<ExtArgs>>): Prisma.Prisma__hallClient<runtime.Types.Result.GetResult<Prisma.$hallPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  ticket<T extends Prisma.seance$ticketArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.seance$ticketArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the seance model
 */
export interface seanceFieldRefs {
  readonly ID_seance: Prisma.FieldRef<"seance", 'Int'>
  readonly ID_performance: Prisma.FieldRef<"seance", 'Int'>
  readonly seance_time: Prisma.FieldRef<"seance", 'DateTime'>
  readonly seance_date: Prisma.FieldRef<"seance", 'DateTime'>
  readonly ID_hall: Prisma.FieldRef<"seance", 'Int'>
}
    

// Custom InputTypes
/**
 * seance findUnique
 */
export type seanceFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  /**
   * Filter, which seance to fetch.
   */
  where: Prisma.seanceWhereUniqueInput
}

/**
 * seance findUniqueOrThrow
 */
export type seanceFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  /**
   * Filter, which seance to fetch.
   */
  where: Prisma.seanceWhereUniqueInput
}

/**
 * seance findFirst
 */
export type seanceFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  /**
   * Filter, which seance to fetch.
   */
  where?: Prisma.seanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of seances to fetch.
   */
  orderBy?: Prisma.seanceOrderByWithRelationInput | Prisma.seanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for seances.
   */
  cursor?: Prisma.seanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` seances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` seances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of seances.
   */
  distinct?: Prisma.SeanceScalarFieldEnum | Prisma.SeanceScalarFieldEnum[]
}

/**
 * seance findFirstOrThrow
 */
export type seanceFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  /**
   * Filter, which seance to fetch.
   */
  where?: Prisma.seanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of seances to fetch.
   */
  orderBy?: Prisma.seanceOrderByWithRelationInput | Prisma.seanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for seances.
   */
  cursor?: Prisma.seanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` seances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` seances.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of seances.
   */
  distinct?: Prisma.SeanceScalarFieldEnum | Prisma.SeanceScalarFieldEnum[]
}

/**
 * seance findMany
 */
export type seanceFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  /**
   * Filter, which seances to fetch.
   */
  where?: Prisma.seanceWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of seances to fetch.
   */
  orderBy?: Prisma.seanceOrderByWithRelationInput | Prisma.seanceOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing seances.
   */
  cursor?: Prisma.seanceWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` seances from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` seances.
   */
  skip?: number
  distinct?: Prisma.SeanceScalarFieldEnum | Prisma.SeanceScalarFieldEnum[]
}

/**
 * seance create
 */
export type seanceCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  /**
   * The data needed to create a seance.
   */
  data: Prisma.XOR<Prisma.seanceCreateInput, Prisma.seanceUncheckedCreateInput>
}

/**
 * seance createMany
 */
export type seanceCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many seances.
   */
  data: Prisma.seanceCreateManyInput | Prisma.seanceCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * seance update
 */
export type seanceUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  /**
   * The data needed to update a seance.
   */
  data: Prisma.XOR<Prisma.seanceUpdateInput, Prisma.seanceUncheckedUpdateInput>
  /**
   * Choose, which seance to update.
   */
  where: Prisma.seanceWhereUniqueInput
}

/**
 * seance updateMany
 */
export type seanceUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update seances.
   */
  data: Prisma.XOR<Prisma.seanceUpdateManyMutationInput, Prisma.seanceUncheckedUpdateManyInput>
  /**
   * Filter which seances to update
   */
  where?: Prisma.seanceWhereInput
  /**
   * Limit how many seances to update.
   */
  limit?: number
}

/**
 * seance upsert
 */
export type seanceUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  /**
   * The filter to search for the seance to update in case it exists.
   */
  where: Prisma.seanceWhereUniqueInput
  /**
   * In case the seance found by the `where` argument doesn't exist, create a new seance with this data.
   */
  create: Prisma.XOR<Prisma.seanceCreateInput, Prisma.seanceUncheckedCreateInput>
  /**
   * In case the seance was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.seanceUpdateInput, Prisma.seanceUncheckedUpdateInput>
}

/**
 * seance delete
 */
export type seanceDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
  /**
   * Filter which seance to delete.
   */
  where: Prisma.seanceWhereUniqueInput
}

/**
 * seance deleteMany
 */
export type seanceDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which seances to delete
   */
  where?: Prisma.seanceWhereInput
  /**
   * Limit how many seances to delete.
   */
  limit?: number
}

/**
 * seance.comm
 */
export type seance$commArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the comm
   */
  select?: Prisma.commSelect<ExtArgs> | null
  /**
   * Omit specific fields from the comm
   */
  omit?: Prisma.commOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.commInclude<ExtArgs> | null
  where?: Prisma.commWhereInput
  orderBy?: Prisma.commOrderByWithRelationInput | Prisma.commOrderByWithRelationInput[]
  cursor?: Prisma.commWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CommScalarFieldEnum | Prisma.CommScalarFieldEnum[]
}

/**
 * seance.ticket
 */
export type seance$ticketArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  where?: Prisma.ticketWhereInput
  orderBy?: Prisma.ticketOrderByWithRelationInput | Prisma.ticketOrderByWithRelationInput[]
  cursor?: Prisma.ticketWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * seance without action
 */
export type seanceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seance
   */
  select?: Prisma.seanceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seance
   */
  omit?: Prisma.seanceOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seanceInclude<ExtArgs> | null
}
