
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ticket` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ticket
 * 
 */
export type ticketModel = runtime.Types.Result.DefaultSelection<Prisma.$ticketPayload>

export type AggregateTicket = {
  _count: TicketCountAggregateOutputType | null
  _avg: TicketAvgAggregateOutputType | null
  _sum: TicketSumAggregateOutputType | null
  _min: TicketMinAggregateOutputType | null
  _max: TicketMaxAggregateOutputType | null
}

export type TicketAvgAggregateOutputType = {
  ID_seance: number | null
  ID_viewer: number | null
  ID_ticket: number | null
}

export type TicketSumAggregateOutputType = {
  ID_seance: number | null
  ID_viewer: number | null
  ID_ticket: number | null
}

export type TicketMinAggregateOutputType = {
  ID_seance: number | null
  ID_viewer: number | null
  ID_ticket: number | null
}

export type TicketMaxAggregateOutputType = {
  ID_seance: number | null
  ID_viewer: number | null
  ID_ticket: number | null
}

export type TicketCountAggregateOutputType = {
  ID_seance: number
  ID_viewer: number
  ID_ticket: number
  _all: number
}


export type TicketAvgAggregateInputType = {
  ID_seance?: true
  ID_viewer?: true
  ID_ticket?: true
}

export type TicketSumAggregateInputType = {
  ID_seance?: true
  ID_viewer?: true
  ID_ticket?: true
}

export type TicketMinAggregateInputType = {
  ID_seance?: true
  ID_viewer?: true
  ID_ticket?: true
}

export type TicketMaxAggregateInputType = {
  ID_seance?: true
  ID_viewer?: true
  ID_ticket?: true
}

export type TicketCountAggregateInputType = {
  ID_seance?: true
  ID_viewer?: true
  ID_ticket?: true
  _all?: true
}

export type TicketAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ticket to aggregate.
   */
  where?: Prisma.ticketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tickets to fetch.
   */
  orderBy?: Prisma.ticketOrderByWithRelationInput | Prisma.ticketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ticketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned tickets
  **/
  _count?: true | TicketCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TicketAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TicketSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TicketMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TicketMaxAggregateInputType
}

export type GetTicketAggregateType<T extends TicketAggregateArgs> = {
      [P in keyof T & keyof AggregateTicket]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTicket[P]>
    : Prisma.GetScalarType<T[P], AggregateTicket[P]>
}




export type ticketGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ticketWhereInput
  orderBy?: Prisma.ticketOrderByWithAggregationInput | Prisma.ticketOrderByWithAggregationInput[]
  by: Prisma.TicketScalarFieldEnum[] | Prisma.TicketScalarFieldEnum
  having?: Prisma.ticketScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TicketCountAggregateInputType | true
  _avg?: TicketAvgAggregateInputType
  _sum?: TicketSumAggregateInputType
  _min?: TicketMinAggregateInputType
  _max?: TicketMaxAggregateInputType
}

export type TicketGroupByOutputType = {
  ID_seance: number
  ID_viewer: number
  ID_ticket: number
  _count: TicketCountAggregateOutputType | null
  _avg: TicketAvgAggregateOutputType | null
  _sum: TicketSumAggregateOutputType | null
  _min: TicketMinAggregateOutputType | null
  _max: TicketMaxAggregateOutputType | null
}

type GetTicketGroupByPayload<T extends ticketGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TicketGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TicketGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TicketGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TicketGroupByOutputType[P]>
      }
    >
  >



export type ticketWhereInput = {
  AND?: Prisma.ticketWhereInput | Prisma.ticketWhereInput[]
  OR?: Prisma.ticketWhereInput[]
  NOT?: Prisma.ticketWhereInput | Prisma.ticketWhereInput[]
  ID_seance?: Prisma.IntFilter<"ticket"> | number
  ID_viewer?: Prisma.IntFilter<"ticket"> | number
  ID_ticket?: Prisma.IntFilter<"ticket"> | number
  seat_by_ticket?: Prisma.Seat_by_ticketListRelationFilter
  seance?: Prisma.XOR<Prisma.SeanceScalarRelationFilter, Prisma.seanceWhereInput>
  viewer?: Prisma.XOR<Prisma.ViewerScalarRelationFilter, Prisma.viewerWhereInput>
}

export type ticketOrderByWithRelationInput = {
  ID_seance?: Prisma.SortOrder
  ID_viewer?: Prisma.SortOrder
  ID_ticket?: Prisma.SortOrder
  seat_by_ticket?: Prisma.seat_by_ticketOrderByRelationAggregateInput
  seance?: Prisma.seanceOrderByWithRelationInput
  viewer?: Prisma.viewerOrderByWithRelationInput
}

export type ticketWhereUniqueInput = Prisma.AtLeast<{
  ID_ticket?: number
  AND?: Prisma.ticketWhereInput | Prisma.ticketWhereInput[]
  OR?: Prisma.ticketWhereInput[]
  NOT?: Prisma.ticketWhereInput | Prisma.ticketWhereInput[]
  ID_seance?: Prisma.IntFilter<"ticket"> | number
  ID_viewer?: Prisma.IntFilter<"ticket"> | number
  seat_by_ticket?: Prisma.Seat_by_ticketListRelationFilter
  seance?: Prisma.XOR<Prisma.SeanceScalarRelationFilter, Prisma.seanceWhereInput>
  viewer?: Prisma.XOR<Prisma.ViewerScalarRelationFilter, Prisma.viewerWhereInput>
}, "ID_ticket">

export type ticketOrderByWithAggregationInput = {
  ID_seance?: Prisma.SortOrder
  ID_viewer?: Prisma.SortOrder
  ID_ticket?: Prisma.SortOrder
  _count?: Prisma.ticketCountOrderByAggregateInput
  _avg?: Prisma.ticketAvgOrderByAggregateInput
  _max?: Prisma.ticketMaxOrderByAggregateInput
  _min?: Prisma.ticketMinOrderByAggregateInput
  _sum?: Prisma.ticketSumOrderByAggregateInput
}

export type ticketScalarWhereWithAggregatesInput = {
  AND?: Prisma.ticketScalarWhereWithAggregatesInput | Prisma.ticketScalarWhereWithAggregatesInput[]
  OR?: Prisma.ticketScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ticketScalarWhereWithAggregatesInput | Prisma.ticketScalarWhereWithAggregatesInput[]
  ID_seance?: Prisma.IntWithAggregatesFilter<"ticket"> | number
  ID_viewer?: Prisma.IntWithAggregatesFilter<"ticket"> | number
  ID_ticket?: Prisma.IntWithAggregatesFilter<"ticket"> | number
}

export type ticketCreateInput = {
  ID_ticket: number
  seat_by_ticket?: Prisma.seat_by_ticketCreateNestedManyWithoutTicketInput
  seance: Prisma.seanceCreateNestedOneWithoutTicketInput
  viewer: Prisma.viewerCreateNestedOneWithoutTicketInput
}

export type ticketUncheckedCreateInput = {
  ID_seance: number
  ID_viewer: number
  ID_ticket: number
  seat_by_ticket?: Prisma.seat_by_ticketUncheckedCreateNestedManyWithoutTicketInput
}

export type ticketUpdateInput = {
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
  seat_by_ticket?: Prisma.seat_by_ticketUpdateManyWithoutTicketNestedInput
  seance?: Prisma.seanceUpdateOneRequiredWithoutTicketNestedInput
  viewer?: Prisma.viewerUpdateOneRequiredWithoutTicketNestedInput
}

export type ticketUncheckedUpdateInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_viewer?: Prisma.IntFieldUpdateOperationsInput | number
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
  seat_by_ticket?: Prisma.seat_by_ticketUncheckedUpdateManyWithoutTicketNestedInput
}

export type ticketCreateManyInput = {
  ID_seance: number
  ID_viewer: number
  ID_ticket: number
}

export type ticketUpdateManyMutationInput = {
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ticketUncheckedUpdateManyInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_viewer?: Prisma.IntFieldUpdateOperationsInput | number
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
}

export type TicketListRelationFilter = {
  every?: Prisma.ticketWhereInput
  some?: Prisma.ticketWhereInput
  none?: Prisma.ticketWhereInput
}

export type ticketOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TicketScalarRelationFilter = {
  is?: Prisma.ticketWhereInput
  isNot?: Prisma.ticketWhereInput
}

export type ticketCountOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_viewer?: Prisma.SortOrder
  ID_ticket?: Prisma.SortOrder
}

export type ticketAvgOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_viewer?: Prisma.SortOrder
  ID_ticket?: Prisma.SortOrder
}

export type ticketMaxOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_viewer?: Prisma.SortOrder
  ID_ticket?: Prisma.SortOrder
}

export type ticketMinOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_viewer?: Prisma.SortOrder
  ID_ticket?: Prisma.SortOrder
}

export type ticketSumOrderByAggregateInput = {
  ID_seance?: Prisma.SortOrder
  ID_viewer?: Prisma.SortOrder
  ID_ticket?: Prisma.SortOrder
}

export type ticketCreateNestedManyWithoutSeanceInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutSeanceInput, Prisma.ticketUncheckedCreateWithoutSeanceInput> | Prisma.ticketCreateWithoutSeanceInput[] | Prisma.ticketUncheckedCreateWithoutSeanceInput[]
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutSeanceInput | Prisma.ticketCreateOrConnectWithoutSeanceInput[]
  createMany?: Prisma.ticketCreateManySeanceInputEnvelope
  connect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
}

export type ticketUncheckedCreateNestedManyWithoutSeanceInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutSeanceInput, Prisma.ticketUncheckedCreateWithoutSeanceInput> | Prisma.ticketCreateWithoutSeanceInput[] | Prisma.ticketUncheckedCreateWithoutSeanceInput[]
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutSeanceInput | Prisma.ticketCreateOrConnectWithoutSeanceInput[]
  createMany?: Prisma.ticketCreateManySeanceInputEnvelope
  connect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
}

export type ticketUpdateManyWithoutSeanceNestedInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutSeanceInput, Prisma.ticketUncheckedCreateWithoutSeanceInput> | Prisma.ticketCreateWithoutSeanceInput[] | Prisma.ticketUncheckedCreateWithoutSeanceInput[]
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutSeanceInput | Prisma.ticketCreateOrConnectWithoutSeanceInput[]
  upsert?: Prisma.ticketUpsertWithWhereUniqueWithoutSeanceInput | Prisma.ticketUpsertWithWhereUniqueWithoutSeanceInput[]
  createMany?: Prisma.ticketCreateManySeanceInputEnvelope
  set?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  disconnect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  delete?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  connect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  update?: Prisma.ticketUpdateWithWhereUniqueWithoutSeanceInput | Prisma.ticketUpdateWithWhereUniqueWithoutSeanceInput[]
  updateMany?: Prisma.ticketUpdateManyWithWhereWithoutSeanceInput | Prisma.ticketUpdateManyWithWhereWithoutSeanceInput[]
  deleteMany?: Prisma.ticketScalarWhereInput | Prisma.ticketScalarWhereInput[]
}

export type ticketUncheckedUpdateManyWithoutSeanceNestedInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutSeanceInput, Prisma.ticketUncheckedCreateWithoutSeanceInput> | Prisma.ticketCreateWithoutSeanceInput[] | Prisma.ticketUncheckedCreateWithoutSeanceInput[]
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutSeanceInput | Prisma.ticketCreateOrConnectWithoutSeanceInput[]
  upsert?: Prisma.ticketUpsertWithWhereUniqueWithoutSeanceInput | Prisma.ticketUpsertWithWhereUniqueWithoutSeanceInput[]
  createMany?: Prisma.ticketCreateManySeanceInputEnvelope
  set?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  disconnect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  delete?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  connect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  update?: Prisma.ticketUpdateWithWhereUniqueWithoutSeanceInput | Prisma.ticketUpdateWithWhereUniqueWithoutSeanceInput[]
  updateMany?: Prisma.ticketUpdateManyWithWhereWithoutSeanceInput | Prisma.ticketUpdateManyWithWhereWithoutSeanceInput[]
  deleteMany?: Prisma.ticketScalarWhereInput | Prisma.ticketScalarWhereInput[]
}

export type ticketCreateNestedOneWithoutSeat_by_ticketInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutSeat_by_ticketInput, Prisma.ticketUncheckedCreateWithoutSeat_by_ticketInput>
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutSeat_by_ticketInput
  connect?: Prisma.ticketWhereUniqueInput
}

export type ticketUpdateOneRequiredWithoutSeat_by_ticketNestedInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutSeat_by_ticketInput, Prisma.ticketUncheckedCreateWithoutSeat_by_ticketInput>
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutSeat_by_ticketInput
  upsert?: Prisma.ticketUpsertWithoutSeat_by_ticketInput
  connect?: Prisma.ticketWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ticketUpdateToOneWithWhereWithoutSeat_by_ticketInput, Prisma.ticketUpdateWithoutSeat_by_ticketInput>, Prisma.ticketUncheckedUpdateWithoutSeat_by_ticketInput>
}

export type ticketCreateNestedManyWithoutViewerInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutViewerInput, Prisma.ticketUncheckedCreateWithoutViewerInput> | Prisma.ticketCreateWithoutViewerInput[] | Prisma.ticketUncheckedCreateWithoutViewerInput[]
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutViewerInput | Prisma.ticketCreateOrConnectWithoutViewerInput[]
  createMany?: Prisma.ticketCreateManyViewerInputEnvelope
  connect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
}

export type ticketUncheckedCreateNestedManyWithoutViewerInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutViewerInput, Prisma.ticketUncheckedCreateWithoutViewerInput> | Prisma.ticketCreateWithoutViewerInput[] | Prisma.ticketUncheckedCreateWithoutViewerInput[]
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutViewerInput | Prisma.ticketCreateOrConnectWithoutViewerInput[]
  createMany?: Prisma.ticketCreateManyViewerInputEnvelope
  connect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
}

export type ticketUpdateManyWithoutViewerNestedInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutViewerInput, Prisma.ticketUncheckedCreateWithoutViewerInput> | Prisma.ticketCreateWithoutViewerInput[] | Prisma.ticketUncheckedCreateWithoutViewerInput[]
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutViewerInput | Prisma.ticketCreateOrConnectWithoutViewerInput[]
  upsert?: Prisma.ticketUpsertWithWhereUniqueWithoutViewerInput | Prisma.ticketUpsertWithWhereUniqueWithoutViewerInput[]
  createMany?: Prisma.ticketCreateManyViewerInputEnvelope
  set?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  disconnect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  delete?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  connect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  update?: Prisma.ticketUpdateWithWhereUniqueWithoutViewerInput | Prisma.ticketUpdateWithWhereUniqueWithoutViewerInput[]
  updateMany?: Prisma.ticketUpdateManyWithWhereWithoutViewerInput | Prisma.ticketUpdateManyWithWhereWithoutViewerInput[]
  deleteMany?: Prisma.ticketScalarWhereInput | Prisma.ticketScalarWhereInput[]
}

export type ticketUncheckedUpdateManyWithoutViewerNestedInput = {
  create?: Prisma.XOR<Prisma.ticketCreateWithoutViewerInput, Prisma.ticketUncheckedCreateWithoutViewerInput> | Prisma.ticketCreateWithoutViewerInput[] | Prisma.ticketUncheckedCreateWithoutViewerInput[]
  connectOrCreate?: Prisma.ticketCreateOrConnectWithoutViewerInput | Prisma.ticketCreateOrConnectWithoutViewerInput[]
  upsert?: Prisma.ticketUpsertWithWhereUniqueWithoutViewerInput | Prisma.ticketUpsertWithWhereUniqueWithoutViewerInput[]
  createMany?: Prisma.ticketCreateManyViewerInputEnvelope
  set?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  disconnect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  delete?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  connect?: Prisma.ticketWhereUniqueInput | Prisma.ticketWhereUniqueInput[]
  update?: Prisma.ticketUpdateWithWhereUniqueWithoutViewerInput | Prisma.ticketUpdateWithWhereUniqueWithoutViewerInput[]
  updateMany?: Prisma.ticketUpdateManyWithWhereWithoutViewerInput | Prisma.ticketUpdateManyWithWhereWithoutViewerInput[]
  deleteMany?: Prisma.ticketScalarWhereInput | Prisma.ticketScalarWhereInput[]
}

export type ticketCreateWithoutSeanceInput = {
  ID_ticket: number
  seat_by_ticket?: Prisma.seat_by_ticketCreateNestedManyWithoutTicketInput
  viewer: Prisma.viewerCreateNestedOneWithoutTicketInput
}

export type ticketUncheckedCreateWithoutSeanceInput = {
  ID_viewer: number
  ID_ticket: number
  seat_by_ticket?: Prisma.seat_by_ticketUncheckedCreateNestedManyWithoutTicketInput
}

export type ticketCreateOrConnectWithoutSeanceInput = {
  where: Prisma.ticketWhereUniqueInput
  create: Prisma.XOR<Prisma.ticketCreateWithoutSeanceInput, Prisma.ticketUncheckedCreateWithoutSeanceInput>
}

export type ticketCreateManySeanceInputEnvelope = {
  data: Prisma.ticketCreateManySeanceInput | Prisma.ticketCreateManySeanceInput[]
  skipDuplicates?: boolean
}

export type ticketUpsertWithWhereUniqueWithoutSeanceInput = {
  where: Prisma.ticketWhereUniqueInput
  update: Prisma.XOR<Prisma.ticketUpdateWithoutSeanceInput, Prisma.ticketUncheckedUpdateWithoutSeanceInput>
  create: Prisma.XOR<Prisma.ticketCreateWithoutSeanceInput, Prisma.ticketUncheckedCreateWithoutSeanceInput>
}

export type ticketUpdateWithWhereUniqueWithoutSeanceInput = {
  where: Prisma.ticketWhereUniqueInput
  data: Prisma.XOR<Prisma.ticketUpdateWithoutSeanceInput, Prisma.ticketUncheckedUpdateWithoutSeanceInput>
}

export type ticketUpdateManyWithWhereWithoutSeanceInput = {
  where: Prisma.ticketScalarWhereInput
  data: Prisma.XOR<Prisma.ticketUpdateManyMutationInput, Prisma.ticketUncheckedUpdateManyWithoutSeanceInput>
}

export type ticketScalarWhereInput = {
  AND?: Prisma.ticketScalarWhereInput | Prisma.ticketScalarWhereInput[]
  OR?: Prisma.ticketScalarWhereInput[]
  NOT?: Prisma.ticketScalarWhereInput | Prisma.ticketScalarWhereInput[]
  ID_seance?: Prisma.IntFilter<"ticket"> | number
  ID_viewer?: Prisma.IntFilter<"ticket"> | number
  ID_ticket?: Prisma.IntFilter<"ticket"> | number
}

export type ticketCreateWithoutSeat_by_ticketInput = {
  ID_ticket: number
  seance: Prisma.seanceCreateNestedOneWithoutTicketInput
  viewer: Prisma.viewerCreateNestedOneWithoutTicketInput
}

export type ticketUncheckedCreateWithoutSeat_by_ticketInput = {
  ID_seance: number
  ID_viewer: number
  ID_ticket: number
}

export type ticketCreateOrConnectWithoutSeat_by_ticketInput = {
  where: Prisma.ticketWhereUniqueInput
  create: Prisma.XOR<Prisma.ticketCreateWithoutSeat_by_ticketInput, Prisma.ticketUncheckedCreateWithoutSeat_by_ticketInput>
}

export type ticketUpsertWithoutSeat_by_ticketInput = {
  update: Prisma.XOR<Prisma.ticketUpdateWithoutSeat_by_ticketInput, Prisma.ticketUncheckedUpdateWithoutSeat_by_ticketInput>
  create: Prisma.XOR<Prisma.ticketCreateWithoutSeat_by_ticketInput, Prisma.ticketUncheckedCreateWithoutSeat_by_ticketInput>
  where?: Prisma.ticketWhereInput
}

export type ticketUpdateToOneWithWhereWithoutSeat_by_ticketInput = {
  where?: Prisma.ticketWhereInput
  data: Prisma.XOR<Prisma.ticketUpdateWithoutSeat_by_ticketInput, Prisma.ticketUncheckedUpdateWithoutSeat_by_ticketInput>
}

export type ticketUpdateWithoutSeat_by_ticketInput = {
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
  seance?: Prisma.seanceUpdateOneRequiredWithoutTicketNestedInput
  viewer?: Prisma.viewerUpdateOneRequiredWithoutTicketNestedInput
}

export type ticketUncheckedUpdateWithoutSeat_by_ticketInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_viewer?: Prisma.IntFieldUpdateOperationsInput | number
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ticketCreateWithoutViewerInput = {
  ID_ticket: number
  seat_by_ticket?: Prisma.seat_by_ticketCreateNestedManyWithoutTicketInput
  seance: Prisma.seanceCreateNestedOneWithoutTicketInput
}

export type ticketUncheckedCreateWithoutViewerInput = {
  ID_seance: number
  ID_ticket: number
  seat_by_ticket?: Prisma.seat_by_ticketUncheckedCreateNestedManyWithoutTicketInput
}

export type ticketCreateOrConnectWithoutViewerInput = {
  where: Prisma.ticketWhereUniqueInput
  create: Prisma.XOR<Prisma.ticketCreateWithoutViewerInput, Prisma.ticketUncheckedCreateWithoutViewerInput>
}

export type ticketCreateManyViewerInputEnvelope = {
  data: Prisma.ticketCreateManyViewerInput | Prisma.ticketCreateManyViewerInput[]
  skipDuplicates?: boolean
}

export type ticketUpsertWithWhereUniqueWithoutViewerInput = {
  where: Prisma.ticketWhereUniqueInput
  update: Prisma.XOR<Prisma.ticketUpdateWithoutViewerInput, Prisma.ticketUncheckedUpdateWithoutViewerInput>
  create: Prisma.XOR<Prisma.ticketCreateWithoutViewerInput, Prisma.ticketUncheckedCreateWithoutViewerInput>
}

export type ticketUpdateWithWhereUniqueWithoutViewerInput = {
  where: Prisma.ticketWhereUniqueInput
  data: Prisma.XOR<Prisma.ticketUpdateWithoutViewerInput, Prisma.ticketUncheckedUpdateWithoutViewerInput>
}

export type ticketUpdateManyWithWhereWithoutViewerInput = {
  where: Prisma.ticketScalarWhereInput
  data: Prisma.XOR<Prisma.ticketUpdateManyMutationInput, Prisma.ticketUncheckedUpdateManyWithoutViewerInput>
}

export type ticketCreateManySeanceInput = {
  ID_viewer: number
  ID_ticket: number
}

export type ticketUpdateWithoutSeanceInput = {
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
  seat_by_ticket?: Prisma.seat_by_ticketUpdateManyWithoutTicketNestedInput
  viewer?: Prisma.viewerUpdateOneRequiredWithoutTicketNestedInput
}

export type ticketUncheckedUpdateWithoutSeanceInput = {
  ID_viewer?: Prisma.IntFieldUpdateOperationsInput | number
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
  seat_by_ticket?: Prisma.seat_by_ticketUncheckedUpdateManyWithoutTicketNestedInput
}

export type ticketUncheckedUpdateManyWithoutSeanceInput = {
  ID_viewer?: Prisma.IntFieldUpdateOperationsInput | number
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ticketCreateManyViewerInput = {
  ID_seance: number
  ID_ticket: number
}

export type ticketUpdateWithoutViewerInput = {
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
  seat_by_ticket?: Prisma.seat_by_ticketUpdateManyWithoutTicketNestedInput
  seance?: Prisma.seanceUpdateOneRequiredWithoutTicketNestedInput
}

export type ticketUncheckedUpdateWithoutViewerInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
  seat_by_ticket?: Prisma.seat_by_ticketUncheckedUpdateManyWithoutTicketNestedInput
}

export type ticketUncheckedUpdateManyWithoutViewerInput = {
  ID_seance?: Prisma.IntFieldUpdateOperationsInput | number
  ID_ticket?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type TicketCountOutputType
 */

export type TicketCountOutputType = {
  seat_by_ticket: number
}

export type TicketCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  seat_by_ticket?: boolean | TicketCountOutputTypeCountSeat_by_ticketArgs
}

/**
 * TicketCountOutputType without action
 */
export type TicketCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TicketCountOutputType
   */
  select?: Prisma.TicketCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TicketCountOutputType without action
 */
export type TicketCountOutputTypeCountSeat_by_ticketArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.seat_by_ticketWhereInput
}


export type ticketSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  ID_seance?: boolean
  ID_viewer?: boolean
  ID_ticket?: boolean
  seat_by_ticket?: boolean | Prisma.ticket$seat_by_ticketArgs<ExtArgs>
  seance?: boolean | Prisma.seanceDefaultArgs<ExtArgs>
  viewer?: boolean | Prisma.viewerDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TicketCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["ticket"]>



export type ticketSelectScalar = {
  ID_seance?: boolean
  ID_viewer?: boolean
  ID_ticket?: boolean
}

export type ticketOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"ID_seance" | "ID_viewer" | "ID_ticket", ExtArgs["result"]["ticket"]>
export type ticketInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  seat_by_ticket?: boolean | Prisma.ticket$seat_by_ticketArgs<ExtArgs>
  seance?: boolean | Prisma.seanceDefaultArgs<ExtArgs>
  viewer?: boolean | Prisma.viewerDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TicketCountOutputTypeDefaultArgs<ExtArgs>
}

export type $ticketPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ticket"
  objects: {
    seat_by_ticket: Prisma.$seat_by_ticketPayload<ExtArgs>[]
    seance: Prisma.$seancePayload<ExtArgs>
    viewer: Prisma.$viewerPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    ID_seance: number
    ID_viewer: number
    ID_ticket: number
  }, ExtArgs["result"]["ticket"]>
  composites: {}
}

export type ticketGetPayload<S extends boolean | null | undefined | ticketDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ticketPayload, S>

export type ticketCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ticketFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TicketCountAggregateInputType | true
  }

export interface ticketDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ticket'], meta: { name: 'ticket' } }
  /**
   * Find zero or one Ticket that matches the filter.
   * @param {ticketFindUniqueArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ticketFindUniqueArgs>(args: Prisma.SelectSubset<T, ticketFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ticketClient<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Ticket that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ticketFindUniqueOrThrowArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ticketFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ticketFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ticketClient<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ticket that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketFindFirstArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ticketFindFirstArgs>(args?: Prisma.SelectSubset<T, ticketFindFirstArgs<ExtArgs>>): Prisma.Prisma__ticketClient<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Ticket that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketFindFirstOrThrowArgs} args - Arguments to find a Ticket
   * @example
   * // Get one Ticket
   * const ticket = await prisma.ticket.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ticketFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ticketFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ticketClient<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Tickets that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Tickets
   * const tickets = await prisma.ticket.findMany()
   * 
   * // Get first 10 Tickets
   * const tickets = await prisma.ticket.findMany({ take: 10 })
   * 
   * // Only select the `ID_seance`
   * const ticketWithID_seanceOnly = await prisma.ticket.findMany({ select: { ID_seance: true } })
   * 
   */
  findMany<T extends ticketFindManyArgs>(args?: Prisma.SelectSubset<T, ticketFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Ticket.
   * @param {ticketCreateArgs} args - Arguments to create a Ticket.
   * @example
   * // Create one Ticket
   * const Ticket = await prisma.ticket.create({
   *   data: {
   *     // ... data to create a Ticket
   *   }
   * })
   * 
   */
  create<T extends ticketCreateArgs>(args: Prisma.SelectSubset<T, ticketCreateArgs<ExtArgs>>): Prisma.Prisma__ticketClient<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Tickets.
   * @param {ticketCreateManyArgs} args - Arguments to create many Tickets.
   * @example
   * // Create many Tickets
   * const ticket = await prisma.ticket.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ticketCreateManyArgs>(args?: Prisma.SelectSubset<T, ticketCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Ticket.
   * @param {ticketDeleteArgs} args - Arguments to delete one Ticket.
   * @example
   * // Delete one Ticket
   * const Ticket = await prisma.ticket.delete({
   *   where: {
   *     // ... filter to delete one Ticket
   *   }
   * })
   * 
   */
  delete<T extends ticketDeleteArgs>(args: Prisma.SelectSubset<T, ticketDeleteArgs<ExtArgs>>): Prisma.Prisma__ticketClient<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Ticket.
   * @param {ticketUpdateArgs} args - Arguments to update one Ticket.
   * @example
   * // Update one Ticket
   * const ticket = await prisma.ticket.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ticketUpdateArgs>(args: Prisma.SelectSubset<T, ticketUpdateArgs<ExtArgs>>): Prisma.Prisma__ticketClient<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Tickets.
   * @param {ticketDeleteManyArgs} args - Arguments to filter Tickets to delete.
   * @example
   * // Delete a few Tickets
   * const { count } = await prisma.ticket.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ticketDeleteManyArgs>(args?: Prisma.SelectSubset<T, ticketDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Tickets
   * const ticket = await prisma.ticket.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ticketUpdateManyArgs>(args: Prisma.SelectSubset<T, ticketUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Ticket.
   * @param {ticketUpsertArgs} args - Arguments to update or create a Ticket.
   * @example
   * // Update or create a Ticket
   * const ticket = await prisma.ticket.upsert({
   *   create: {
   *     // ... data to create a Ticket
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Ticket we want to update
   *   }
   * })
   */
  upsert<T extends ticketUpsertArgs>(args: Prisma.SelectSubset<T, ticketUpsertArgs<ExtArgs>>): Prisma.Prisma__ticketClient<runtime.Types.Result.GetResult<Prisma.$ticketPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Tickets.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketCountArgs} args - Arguments to filter Tickets to count.
   * @example
   * // Count the number of Tickets
   * const count = await prisma.ticket.count({
   *   where: {
   *     // ... the filter for the Tickets we want to count
   *   }
   * })
  **/
  count<T extends ticketCountArgs>(
    args?: Prisma.Subset<T, ticketCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TicketCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Ticket.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TicketAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TicketAggregateArgs>(args: Prisma.Subset<T, TicketAggregateArgs>): Prisma.PrismaPromise<GetTicketAggregateType<T>>

  /**
   * Group by Ticket.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ticketGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ticketGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ticketGroupByArgs['orderBy'] }
      : { orderBy?: ticketGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ticketGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTicketGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ticket model
 */
readonly fields: ticketFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ticket.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ticketClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  seat_by_ticket<T extends Prisma.ticket$seat_by_ticketArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ticket$seat_by_ticketArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$seat_by_ticketPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  seance<T extends Prisma.seanceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.seanceDefaultArgs<ExtArgs>>): Prisma.Prisma__seanceClient<runtime.Types.Result.GetResult<Prisma.$seancePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  viewer<T extends Prisma.viewerDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.viewerDefaultArgs<ExtArgs>>): Prisma.Prisma__viewerClient<runtime.Types.Result.GetResult<Prisma.$viewerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ticket model
 */
export interface ticketFieldRefs {
  readonly ID_seance: Prisma.FieldRef<"ticket", 'Int'>
  readonly ID_viewer: Prisma.FieldRef<"ticket", 'Int'>
  readonly ID_ticket: Prisma.FieldRef<"ticket", 'Int'>
}
    

// Custom InputTypes
/**
 * ticket findUnique
 */
export type ticketFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  /**
   * Filter, which ticket to fetch.
   */
  where: Prisma.ticketWhereUniqueInput
}

/**
 * ticket findUniqueOrThrow
 */
export type ticketFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  /**
   * Filter, which ticket to fetch.
   */
  where: Prisma.ticketWhereUniqueInput
}

/**
 * ticket findFirst
 */
export type ticketFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  /**
   * Filter, which ticket to fetch.
   */
  where?: Prisma.ticketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tickets to fetch.
   */
  orderBy?: Prisma.ticketOrderByWithRelationInput | Prisma.ticketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tickets.
   */
  cursor?: Prisma.ticketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * ticket findFirstOrThrow
 */
export type ticketFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  /**
   * Filter, which ticket to fetch.
   */
  where?: Prisma.ticketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tickets to fetch.
   */
  orderBy?: Prisma.ticketOrderByWithRelationInput | Prisma.ticketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for tickets.
   */
  cursor?: Prisma.ticketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tickets.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of tickets.
   */
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * ticket findMany
 */
export type ticketFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  /**
   * Filter, which tickets to fetch.
   */
  where?: Prisma.ticketWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of tickets to fetch.
   */
  orderBy?: Prisma.ticketOrderByWithRelationInput | Prisma.ticketOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing tickets.
   */
  cursor?: Prisma.ticketWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` tickets from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` tickets.
   */
  skip?: number
  distinct?: Prisma.TicketScalarFieldEnum | Prisma.TicketScalarFieldEnum[]
}

/**
 * ticket create
 */
export type ticketCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  /**
   * The data needed to create a ticket.
   */
  data: Prisma.XOR<Prisma.ticketCreateInput, Prisma.ticketUncheckedCreateInput>
}

/**
 * ticket createMany
 */
export type ticketCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many tickets.
   */
  data: Prisma.ticketCreateManyInput | Prisma.ticketCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ticket update
 */
export type ticketUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  /**
   * The data needed to update a ticket.
   */
  data: Prisma.XOR<Prisma.ticketUpdateInput, Prisma.ticketUncheckedUpdateInput>
  /**
   * Choose, which ticket to update.
   */
  where: Prisma.ticketWhereUniqueInput
}

/**
 * ticket updateMany
 */
export type ticketUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update tickets.
   */
  data: Prisma.XOR<Prisma.ticketUpdateManyMutationInput, Prisma.ticketUncheckedUpdateManyInput>
  /**
   * Filter which tickets to update
   */
  where?: Prisma.ticketWhereInput
  /**
   * Limit how many tickets to update.
   */
  limit?: number
}

/**
 * ticket upsert
 */
export type ticketUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  /**
   * The filter to search for the ticket to update in case it exists.
   */
  where: Prisma.ticketWhereUniqueInput
  /**
   * In case the ticket found by the `where` argument doesn't exist, create a new ticket with this data.
   */
  create: Prisma.XOR<Prisma.ticketCreateInput, Prisma.ticketUncheckedCreateInput>
  /**
   * In case the ticket was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ticketUpdateInput, Prisma.ticketUncheckedUpdateInput>
}

/**
 * ticket delete
 */
export type ticketDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
  /**
   * Filter which ticket to delete.
   */
  where: Prisma.ticketWhereUniqueInput
}

/**
 * ticket deleteMany
 */
export type ticketDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which tickets to delete
   */
  where?: Prisma.ticketWhereInput
  /**
   * Limit how many tickets to delete.
   */
  limit?: number
}

/**
 * ticket.seat_by_ticket
 */
export type ticket$seat_by_ticketArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the seat_by_ticket
   */
  select?: Prisma.seat_by_ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the seat_by_ticket
   */
  omit?: Prisma.seat_by_ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.seat_by_ticketInclude<ExtArgs> | null
  where?: Prisma.seat_by_ticketWhereInput
  orderBy?: Prisma.seat_by_ticketOrderByWithRelationInput | Prisma.seat_by_ticketOrderByWithRelationInput[]
  cursor?: Prisma.seat_by_ticketWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.Seat_by_ticketScalarFieldEnum | Prisma.Seat_by_ticketScalarFieldEnum[]
}

/**
 * ticket without action
 */
export type ticketDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ticket
   */
  select?: Prisma.ticketSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ticket
   */
  omit?: Prisma.ticketOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ticketInclude<ExtArgs> | null
}
