
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma. Through it you get access to all the models, enums, and input types.
 * If you're looking for something you can import in the client-side of your application, please refer to the `browser.ts` file instead.
 * 
 * 🟢 You can import this file directly.
 */

import * as process from 'node:process'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
globalThis['__dirname'] = path.dirname(fileURLToPath(import.meta.url))

import * as runtime from "@prisma/client/runtime/library"
import * as $Enums from "./enums"
import * as $Class from "./internal/class"
import * as Prisma from "./internal/prismaNamespace"

export * as $Enums from './enums'
export * from "./enums"
/**
 * ## Prisma Client
 * 
 * Type-safe database client for TypeScript
 * @example
 * ```
 * const prisma = new PrismaClient()
 * // Fetch zero or more Actors
 * const actors = await prisma.actor.findMany()
 * ```
 * 
 * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client).
 */
export const PrismaClient = $Class.getPrismaClientClass(__dirname)
export type PrismaClient<LogOpts extends Prisma.LogLevel = never, OmitOpts extends Prisma.PrismaClientOptions["omit"] = Prisma.PrismaClientOptions["omit"], ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = $Class.PrismaClient<LogOpts, OmitOpts, ExtArgs>
export { Prisma }


// file annotations for bundling tools to include these files
path.join(__dirname, "query_engine-windows.dll.node")
path.join(process.cwd(), "prisma/prisma/query_engine-windows.dll.node")

/**
 * Model actor
 * 
 */
export type actor = Prisma.actorModel
/**
 * Model actors_hero
 * 
 */
export type actors_hero = Prisma.actors_heroModel
/**
 * Model comm
 * 
 */
export type comm = Prisma.commModel
/**
 * Model hall
 * 
 */
export type hall = Prisma.hallModel
/**
 * Model hero
 * 
 */
export type hero = Prisma.heroModel
/**
 * Model performance
 * 
 */
export type performance = Prisma.performanceModel
/**
 * Model regisseur
 * 
 */
export type regisseur = Prisma.regisseurModel
/**
 * Model seance
 * 
 */
export type seance = Prisma.seanceModel
/**
 * Model seat
 * 
 */
export type seat = Prisma.seatModel
/**
 * Model seat_by_ticket
 * 
 */
export type seat_by_ticket = Prisma.seat_by_ticketModel
/**
 * Model ticket
 * 
 */
export type ticket = Prisma.ticketModel
/**
 * Model viewer
 * 
 */
export type viewer = Prisma.viewerModel
