
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/actor'
export type * from './models/actors_hero'
export type * from './models/comm'
export type * from './models/hall'
export type * from './models/hero'
export type * from './models/performance'
export type * from './models/regisseur'
export type * from './models/seance'
export type * from './models/seat'
export type * from './models/seat_by_ticket'
export type * from './models/ticket'
export type * from './models/viewer'
export type * from './commonInputTypes'