import type { Metadata } from "next";
import afisha from "./components/afisha";
export const metadata: Metadata = {
  title: "Театр сатиры",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div>
      <h1>Афиша</h1>
      {afisha()}
    </div>
  );
}
